### ISSUE TITLE
[BUG] Telegramme löschen funktioniert nicht

### ISSUE THREAD

**Issue by Twacker2** [Sundown-Rising/sundown-rising-issues#102]
**Beschreibe den Fehler**
Hallo,
Wenn man an der Telegrammstation ein Telegramm löschen möchte ist dies einem nicht möglich und man bekommt die Meldung "Du darfst dieses Telegramm nicht löschen.".

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Geh zur Telegrammstation.
2. Versuch ein Telegramm zu löschen.
3. Telegramme löschen geht nicht.

**Erwartetes Verhalten**
Telegramm lässt sich löschen und verschwindet aus der Liste.

**Screenshots/Videos**
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/138940026/ca92edc2-e544-47d2-a123-c90098651e6e)

**Kontaktdaten Melder**
 - IC-Name: Mirella Edison
 - Discord: 884021556404166676 / SR Amnesia

**Sonstiges**
Nichts, danke fürs machen. <3

**Comment by SRCaesar** [comment]
Telegrame Von Gewerbe an Privatpersonen können von Privatpersonen nicht beantwortet werden.

Hier noch ein Clip:
https://cdn.discordapp.com/attachments/1250217965509677076/1250221869311721473/uncapped_MedalTVRedM20240612005236.mp4?ex=666c2199&is=666ad019&hm=1c9ffafbae5bbacd24e993d33e044d2eed042cfdfc99e5f68f805288187edeca&

**Comment by XPeTerchenX** [comment]
Beschreibe den Fehler:
Telekram Kontakte Speichern funktioniert bei mir nicht.


Fehler:
Individuel

Nachstellbar
bei mir nicht andere Ja
Falls Ja, folgende Schritte:
1. Kontakt speichern
2. Fehler KOntakt wird nicht gespeichert in Liste

Cache löschen half nicht

Kontaktdaten Melder
IC-Name: Edward Lange
Discord: 302440363270995969
& 
497722051415769089 -Janco Peppone

https://youtu.be/saoeU0O2hFE

**Comment by Twackerino** [comment]
> Telegrame Von Gewerbe an Privatpersonen können von Privatpersonen nicht beantwortet werden.
> 
> Hier noch ein Clip: https://cdn.discordapp.com/attachments/1250217965509677076/1250221869311721473/uncapped_MedalTVRedM20240612005236.mp4?ex=666c2199&is=666ad019&hm=1c9ffafbae5bbacd24e993d33e044d2eed042cfdfc99e5f68f805288187edeca&

Kein Fehler

**Comment by Twackerino** [comment]
> **Beschreibe den Fehler** Hallo, Wenn man an der Telegrammstation ein Telegramm löschen möchte ist dies einem nicht möglich und man bekommt die Meldung "Du darfst dieses Telegramm nicht löschen.".
> 
> **Nachstellbar** JA Falls Ja, folgende Schritte:
> 
>     1. Geh zur Telegrammstation.
> 
>     2. Versuch ein Telegramm zu löschen.
> 
>     3. Telegramme löschen geht nicht.
> 
> 
> **Erwartetes Verhalten** Telegramm lässt sich löschen und verschwindet aus der Liste.
> 
> **Screenshots/Videos** ![image](https://private-user-images.githubusercontent.com/138940026/339323332-ca92edc2-e544-47d2-a123-c90098651e6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODkyMjAsIm5iZiI6MTcxODI4ODkyMCwicGF0aCI6Ii8xMzg5NDAwMjYvMzM5MzIzMzMyLWNhOTJlZGMyLWU1NDQtNDdkMi1hMTIzLWM5MDA5ODY1MWU2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxNDI4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODY2YWNlNjQzMWQ1NmM5ODFjYzZhYjgzYzk2ZDBhM2YzMDIwMzc2N2JmMjJkYjc1MzQ1YzU4NWJhNTJlMjRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AQuIdFyGOTHyNJYD2pC0PGTTCbjH0wamHdaMWi5fCC4)
> 
> **Kontaktdaten Melder**
> 
>     * IC-Name: Mirella Edison
> 
>     * Discord: 884021556404166676 / SR Amnesia
> 
> 
> **Sonstiges** Nichts, danke fürs machen. <3

Bitte ganze Telegramm noch anhängen. Muss sonst raten welches da versucht wird zu löschen

**Comment by Twacker2** [comment]
Alle

**Comment by Twacker2** [comment]
Ich habe grad noch einen weiteren Bug gefunden. Die Telegramme lassen sich auch nicht mehr ungelesen machen.

https://medal.tv/games/red-dead-2/clips/i3RAMQx7eDYCJXJoB/d1337PgZoMOQ?invite=cr-MSxKZWYsMzcwNDQwNzcs

**Comment by Twackerino** [comment]
Löschen sowie Ungelesen behoben.

@XPeTerchenX Sollte ein Spieler keine Kontakte speichern können, diesen bitte an die DB verweisen. Diese sollen in der tp_mailbox_contacts tabelle einen neuen Eintrag anlegen. User_id = Charid , Contacts = [ ]
