### ISSUE TITLE
[BUG]Haus ID 426 Schlüssel

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#103]
**Beschreibe den Fehler**
Schlösser am Haus sind nicht funktionsfähig nachdem der Spieler das Haus gekauft hat.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Geh zum Haus und dann schauen ob die Schlösser gehen.

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Tür schließt auf und zu 

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1250162380197859559/1250219579805012088/Red_Dead_Haus_426_Bug.mp4?ex=666c1f77&is=666acdf7&hm=a16a39c41903d414451569f260013d414bab31ddc47f3708eee6cfab7918a0dc&

**Kontaktdaten Melder**
 - IC-Name: Johan Hill
 - Discord: doofenshmirtz_69

**Comment by MrBurns010** [comment]
Da ist kein Haus ... Schlösser entfernen wir. Bitte Rückerstattung des Geldes veranlassen @SRCaesar
