### ISSUE TITLE
[BUG] Munition ist unendlich

### ISSUE THREAD

**Issue by MrBurns010** [Sundown-Rising/sundown-rising-issues#106]
**Beschreibe den Fehler**
Nach einem Relog ist die Munition immer wieder voll. Egal wieviel man verschossen hat.
Ausgeloggt mit 37 Schuss -> Eingeloggt mit 100 Schuss

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Schießen 
2. Munition merken
3. Ausloggen
4. Einloggen
5. Munition wieder voll

**Erwartetes Verhalten**
Munition wird gespeichert und nicht bei jedem Relog wieder aufgefüllt.

**Comment by Twackerino** [comment]
Noch ein Ticket hilft nicht. Duplikat #71 . Wird geschlossen.
