### ISSUE TITLE
[BUG] Haaransätze bei Männern weg.

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#107]
**Beschreibe den Fehler**
Die ganzen Haaransätze bei Männern die in der Charerstellung gemacht wurden oder durch Second Chance Items erstellt wurden sind nicht mehr da seit dem neuen Friseur Script. Man hat dort auch keine Möglichkeit sich den Haaransatz zu ändern.
Dadurch sehen viele Frisuren "komisch" aus mit einem Hut. Beispiel sieht man im Clip weiter unten.

Gibt es die Möglichkeit dieses beim Friseur einzubauen? 

**Screenshots/Videos**
https://medal.tv/games/red-dead-2/clips/i4jQ0202pTYza0VGs/spok?invite=cr-MSxmSTMsNzcyMDI1Njks

**Kontaktdaten Melder**
 - IC-Name: Jack Winchester
 - Discord: stormi_gaming

**Comment by MrBurns010** [comment]
Gibt es ein Video von vorher zum Vergleich? Es wurde nichts am Hairdresser Script verändert. Eine Änderung an den Frisuren ist eigentlich unmöglich. Diese Funktion hat nichts mit dem neuen Script fürs Makeup zu tun.
@SRIcely

**Comment by MrBurns010** [comment]
Habs gerade im Video gesehen das sich was an den Haaren verändert. Kannst du den Spieler mal fragen welche Option im Charcreator das war womit er sich die Haare dort gemacht hat? Dann können wir uns das anschauen. Nur wir müssen wissen welche Option er für diese Haare gewählt hat.

Danke :-) 

 @SRIcely

**Comment by SRIcely** [comment]
Ich erkundige mich mal. Der Spieler selbst weiß leider nicht mehr wie die Option im Charcreator heißt...

**Comment by MrBurns010** [comment]
@SRIcely 

Sonst gerne nochmal ein Secound Chance Item geben, damit er schauen kann. Das würde uns die Fehlersuche sehr, sehr viel einfacher machen. :-)

**Comment by SRIcely** [comment]
Zufällig war gerade jemand im Support der ein Problem bei der Charerstellung hatte :D
Die Haaransätze laufen in der Charerstellung unter dem Punkt. Hab auch noch einen zweiten Screen gemacht mit den Möglichkeiten die man einstellen kann.
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170888142/cce17519-c047-442c-8a5f-e3c31413aac6)
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170888142/191cca40-f1ca-4dfe-b5cf-a6bad91b3f4a)

**Comment by SRIcely** [comment]
Info:
Wir haben es gerade auch mit einem Second Chance Item versucht bei ihm.
In der Veränderung hat man es gesehen aber als er wieder draussen war, waren die Haare weg. Selbst nach relog.

**Comment by MrBurns010** [comment]
@SRIcely 
Entwickler weiß bescheid. Das hat geholfen! Danke.
Er kümmert sich um einen Bugfix und wir werden diesen, sobald verfügbar direkt aufspielen. Bitte Spieler darüber informieren. :-)

Vielen Dank!

**Comment by MrBurns010** [comment]
@SRIcely 
Laut Entwickler wurde der Fehler mit dem 2 Uhr Update, welches gleich kommt, behoben. Sollte die Anzeige nun korrekt sein, bitte dieses Issue schließen. 

Vielen Dank

**Comment by SRIcely** [comment]
Ich habe gerade beim Friseur nachgeschaut. Dort habe ich keine Option gefunden bezüglich Zusätze.
Oder war es darauf bezogen dass es bei ihm wieder gehen sollte durch das second chance item welches er genutzt hat?
Er selbst kann erst Freitag schauen da er da erst wieder zuhause ist.

@MrBurns010 
Danke schon mal für eine Antwort

**Comment by MrBurns010** [comment]
@SRIcely 

Die Haaransätze sollten angezeigt werden, ohne zum Frisör zu müssen-

**Comment by SRIcely** [comment]
User hat bestätigt. Funktioniert so wie es soll. 

@MrBurns010
