### ISSUE TITLE
[BUG]Kleiner Rucksack nicht nutzbar

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#108]
**Beschreibe den Fehler**
Kleiner Rucksack nicht nutzbar. Wenn man ihn ins Inventar zieht zieht er ihn automatisch an aber man kann ihn nicht öffnen, abstellen oder wegpacken.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Ziehe einen kleinen Rucksack in dein Inventar
2. Versuche in deiner Tasche doppelklick auf ihn zu machen

**Erwartetes Verhalten**
Man zieht den Rucksack in sein Inventar. Dort kann man ihn mit Doppelklick ausrüsten und mit erneutem Doppelklick öffnet sich ein Menü um ihn beispielsweise abzustellen, zu öffnen oder wieder weg zu packen.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i4AXj71HkT2sAvz-x/d13374BiHOf3?invite=cr-MSxjMjksMTkxMjM3Mzc4LA 
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170888142/7b564e44-1b15-4e79-ae6c-aff70b3125e3)

**Kontaktdaten Melder**
 - IC-Name: Jack Hunter
 - Discord: mario_1890

- IC-Name: Jody Holliday
- Discord: hundnala

**Comment by Twackerino** [comment]
Inventargröße des Spielers liegt bei? Sofern sie über 250 liegt funktioniert der Rucksack

**Comment by MrBurns010** [comment]
https://discord.com/channels/1123352191751704606/1123558498127585321/1251490747191132250
