### ISSUE TITLE
[BUG]Grabschaufel

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#111]
**Beschreibe den Fehler**
Eine klare Fehler beschreibung.
Ich hab mir beim Schwarzmarkthändler eine Grabräuberschaufel gekauft und wollte sie natürlich auch ausprobieren.
Gesagt getan - Schaufel lässt sich einwandfrei ausrüsten - Stehe ich jedoch auf dem Grab und fange an zu buddeln, werde ich ins Hauptmenü geworfen.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Geh zum Schwarzmarkthändler
2. Kaufe eine Schaufel
3. Probiee die Schaufel aus

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Das man danach rgaben kann.

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1250836997459804161/1251179687451820143/uncapped_MedalTVScreenRecording20240613173347.mp4?ex=666e4c23&is=666cfaa3&hm=18b6d32ad1c522765e4b158d754a7c65e56e072ae62ab3bde4baa31b611c821a&

**Kontaktdaten Melder**
 - IC-Name: Bayar Batjargal
 - Discord: hase6630 (282905517318471681)

**Comment by MrBurns010** [comment]
@SRCaesar 
gefixt zu 21 Uhr. Bitte Spieler informieren. :-)
