### ISSUE TITLE
[BUG]Gebewerbetelegram

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#112]
**Beschreibe den Fehler**
bei dem Gewerbetelegramm wird nur ca. die Hälfte angezeigt, des Weiteren lassen sich alte Telegramm nicht löschen.

**Nachstellbar**
JA/
Falls Ja, folgende Schritte:
1. Geh zur Telegramstadion
2. Prüfe die Gewerbetelegrame

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Das man alles sieht und die Telegramme löschen kann

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1250727753142243388/1251064309820424242/telegramm.PNG?ex=666e896f&is=666d37ef&hm=b0600351c38a086994b42ea7b6441b826273754d735838b7a31396b2798087c0&

https://cdn.discordapp.com/attachments/1250727753142243388/1251064427214540800/telegramm2.PNG?ex=666e898b&is=666d380b&hm=a0678c89ae66dea786300e6abde7df7705f0d414530a9e7e728f856a7fb92446&

**Kontaktdaten Melder**
 - IC-Name: Mitchell Lewis
 - Discord: tholang (810133059503915049)

**Comment by Twackerino** [comment]
Oberer fehler behoben bei neuen telegrammen

**Comment by Twackerino** [comment]
Unterer bitte bild vom telegramm das gelöscht werden soll. Also vor löschen klick

**Comment by MrBurns010** [comment]
@SRCaesar

**Comment by SRCaesar** [comment]
https://cdn.discordapp.com/attachments/1250727753142243388/1251866813407559732/image.png?ex=66702352&is=666ed1d2&hm=c11c864884b93801f2b96e92dab76addea8b4ed7ac574f001f106d6da7add117&

https://cdn.discordapp.com/attachments/1250727753142243388/1251866813890035815/image.png?ex=66702352&is=666ed1d2&hm=019b337d901cbabf93878903742bf4928ce5efbb93ee42e83f5306065196c497&


Da die verlangten Screens :)

**Comment by Twackerino** [comment]
> https://cdn.discordapp.com/attachments/1250727753142243388/1251866813407559732/image.png?ex=66702352&is=666ed1d2&hm=c11c864884b93801f2b96e92dab76addea8b4ed7ac574f001f106d6da7add117&
> 
> https://cdn.discordapp.com/attachments/1250727753142243388/1251866813890035815/image.png?ex=66702352&is=666ed1d2&hm=019b337d901cbabf93878903742bf4928ce5efbb93ee42e83f5306065196c497&
> 
> Da die verlangten Screens :)

Spieler kann keine versendeten Telegramme zurückrufen. Lediglich erhaltene.

**Comment by SRCaesar** [comment]
So wie ich es verstanden habe will er für eine bessere Übersicht diese bei sich löschen nicht zurückrufen.

**Comment by SRCaesar** [comment]
So wie ich es verstanden habe will er für eine bessere Übersicht diese bei sich löschen nicht zurückrufen. @Twackerino

**Comment by Twackerino** [comment]
Keine versendeten. Nur erhaltene.
