### ISSUE TITLE
[BUG]Ich war gerade beim Trappershop in Rhodes und kann dort nichts mehr verkaufen, weil ich scheinbar nicht den richtigen job habe.

### ISSUE THREAD

**Issue by SRKoch** [Sundown-Rising/sundown-rising-issues#114]
**Beschreibe den Fehler**
Eine klare Fehler beschreibung.

**Nachstellbar**
NEIN

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Fallen inhalte verkaufen oder fallen vkn

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.
https://discord.com/channels/1123352191751704606/1250845541655511140
https://medal.tv/games/red-dead-2/clips/i3RYEd0OeeMJhx6FS/d1337tYlS3wr?invite=cr-MSxZT24sNDg1MDAzMDcs
Ich war gerade beim Trappershop in Rhodes und kann dort nichts mehr verkaufen, weil ich scheinbar nicht den richtigen job habe. 
Ich baue und verkaufe die Fallen und kann die paar Sachen die man aus den Fallen kriegt nichtmal mehr verkaufen?  Clip Füge ich dann gerne ein.
**Kontaktdaten Melder**
 - IC-Name: Wesley Moon
 - Discord:gamerworld92

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
Joblock gewünscht durch CM - Wirtschaft.
https://github.com/Sundown-Rising/sundown-rising-issues/issues/44

**Comment by SRKoch** [comment]
was soll ich dem user nun sagen? oder soll ich es weiterleiten an cm wirtschaft=?

**Comment by Twackerino** [comment]
Deine Entscheidung, ich sag dir nur wer es veranlasst hat ^^
