### ISSUE TITLE
[BUG] Krokodilauftrag Jagdmission

### ISSUE THREAD

**Issue by SR-Morli** [Sundown-Rising/sundown-rising-issues#115]
**Beschreibe den Fehler**
Eine klare Fehler beschreibung.
Beim Häuten des Krokodil´s passiert es, dass der Krokodilkörper nach dem Häuten despawnt. Taucht dieser Fehler auf, kann man die Mission nicht beenden oder abschließen.

Ob der Fehler immerauftaucht kann ich leider nicht sagen :)

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Krokodilauftrag annehmen
2. Krokodil jagen
3. Krokodil häuten (wenn despawnt Fehler bei Abschluss)

**Erwartetes Verhalten**
Die Mission kann abgeschlossen werden und die Belohnungen übergeben.

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.
https://medal.tv/de/games/red-dead-2/clips/i4QE3X3jaZLpC9HHN/d1337JnbDF5u?invite=cr-MSxBcHMsMjA5NjA0MTAyLA

**Kontaktdaten Melder**
 - IC-Name: Shanti Schmidtkowski
 - Discord: mitchel5647

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by MrBurns010** [comment]
an Entwickler weitergeleitet...

**Comment by MrBurns010** [comment]
@SR-Morli 
Der Despawn des Körpers ist gewollt. Hier wird auf die Serverperformance geachtet. Der despawn hat auch nichts damit zu tun, dass man die Mission nicht abschließen kann. Dieses hängt mit dem bekannten Fellbug zusammen. Das Fell darf nicht verschwinden. Hierfür wird es mit dem Fleischer Update aber die Möglichkeit des Bugfixes geben.

Vorher lässt sich dieser Fehler leider nicht beheben. Wir sind allerdings mit Hochdruck am Update dran und werden dies schnellstmöglich veröffentlichen.

Bitte den Spieler informieren und das Discord Ticket gerne schließen. Der Spieler soll auf die Changelogs achten. :-)
