### ISSUE TITLE
[BUG] Baukreisanzeige in der Luft

### ISSUE THREAD

**Issue by SR-Morli** [Sundown-Rising/sundown-rising-issues#116]
**Beschreibe den Fehler**
Bei der Spielerin Jackie Moon ist der Baukreis für  das Campmenü weit in der Luft, so dass es schwierig wird den Wochenmarkt aufzubauen. (siehe Screenshot).

**Nachstellbar**
Weiß ich ehrlich gesagt nicht ob andere auch das Problem haben.

**Erwartetes Verhalten**
Baukreis am Boden um  eine Gute Platzierung zu ermöglichen

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.
![grafik](https://github.com/Sundown-Rising/sundown-rising-issues/assets/172885539/0d275452-7d4c-4c46-997a-0e20265a0150)

**Kontaktdaten Melder**
 - IC-Name: Jackie Moon
 - Discord: fuxine

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by MrBurns010** [comment]
@SR-Morli 

Fehler kann **nicht** reproduziert werden

![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/e194981e-fb1b-4831-ab50-3d2ad3473fb3)

Bitte noch mal prüfen, ob der Fehler weiterhin besteht. Falls ja, bitte mitteilen, welches Möbelstück aufgebaut werden soll. Bitte Clip einreichen, wie versucht wurde, das Möbelstück aufzubauen.

Bitte diesen Hinweis an die Spieler geben:
https://discord.com/channels/1123352191751704606/1166702635487871026
