### ISSUE TITLE
[BUG] Pflanzen

### ISSUE THREAD

**Issue by SR-Morli** [Sundown-Rising/sundown-rising-issues#117]
**Beschreibe den Fehler**
Bei schönem Wetter werden gepflanzte Pflanzen gegossen, bei Regen muss man mit Eimern per Hand gießen.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Anpflanzen
2. Düngen um die Zeit zum versorgen zu überbrücken.
3. Wenn nicht automatisch gegossen wird bei Regen Fehler?

**Erwartetes Verhalten**
Das die Pflanzen den gegossen Status bekommen

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.
https://youtu.be/GwfNCj3V6cQ

**Kontaktdaten Melder**
 - IC-Name: Mavis Miller
 - Discord: tigress255

**Sonstiges**
Bitte bei den Native´s auch mal nachsehen wenn das mit dem automatischen gießen implementiert sein soll. Bei Native´s müssen wir egal ob Sonnenschein oder Regen immer mit Eimer gießen.

**Comment by MrBurns010** [comment]
Wetterscript zu 16 Uhr wieder aufs alte Script getauscht
