### ISSUE TITLE
[BUG] Spielabsturz bei Telegrammen

### ISSUE THREAD

**Issue by SR-Morli** [Sundown-Rising/sundown-rising-issues#118]
**Beschreibe den Fehler**
RedM stürtzt ab ohne Fehlermeldungen, sobald Spielerin versucht Telegramme zu öffnen.

**Nachstellbar**
NEIN

**Erwartetes Verhalten**
Telegramme öffnen sich und können gelesen werden.

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.
Werden nachgereicht sobald vorhanden.

**Kontaktdaten Melder**
 - IC-Name: Mary Lou
 - Discord: mi_mi_kyu

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by SR-Morli** [comment]
https://medal.tv/games/red-dead-2/clips/i52s4Stm7fqEziWNT/d1337VvMaYWa?invite=cr-MSxabk8sMjMwNDI5MTUyLA

Einmal der erste Fall am Ende sieht man kurz die F8 logs. Grüße Morli

**Comment by MrBurns010** [comment]
Dieses Problem kann bei mehreren Spielern nicht reproduziert werden. Es tritt anscheinend nur bei diesem Spieler auf. Hier gerne einmal mit der Spielerin folgende Möglichkeiten durchgehen:

https://discord.com/channels/1123352191751704606/1212545059837186068
https://discord.com/channels/1123352191751704606/1183132057543639111
https://discord.com/channels/1123352191751704606/1134952931574173818

Die Tatsache, dass der Fehler nicht auftritt, wenn der Spieler an einer bestimmten Stelle steht, zeigt eindeutig, dass es sich nicht um einen Fehler beim Telegramm handelt.

@SR-Morli

**Comment by SR-Morli** [comment]
Habe das alles dementsprechend weitergegeben und bedanke mich vielmals fürs durchchecken :)
