### ISSUE TITLE
[BUG] Pferd erkennt Besitzer nicht mehr

### ISSUE THREAD

**Issue by SR-Morli** [Sundown-Rising/sundown-rising-issues#119]
**Beschreibe den Fehler**
Beim Betreten der Umkleiden oder der Friseure (ob andere Orte auch verursachen ist leider nicht bekannt) verlieren die Pferde das Wissen über Ihre Besitzer und erkennen diese nicht wieder, sobald sie zurück kommen. Ruft man sein Pferd erneut taucht ein Doppelgänger vom eigenen Pferd auf und das "verbuggte" Pferd despawnt auch nicht mehr von selbst wenn man sich vom Ort des Geschehens weit entfernt.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Rufe dein Pferd
2. Geh Klamotten shoppen
3. Gehe danach zurück zu deinem Pferd
4. (FEHLER) Das Pferd wird dich nicht mehr erkennen und du kannst es nur noch führen oder Fliehen lassen. (fliehen funktioniert nicht)

**Erwartetes Verhalten**
Das Pferd sollte dich nach dem Shoppen oder dem Friseurbesuch immer noch als Besitzer anerkennen und auf deinen Pfiff hören können.

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.
(Werden in den Kommentaren nachgereicht)

**Kontaktdaten Melder**
 - IC-Name: Jeremy Anders
 - Discord:  grownnx

**Sonstiges**
Übergangslösung auf das verbuggte Pferd setzen und über die F8 Konsole den dh Befehl ausführen (despawn Horse)

**Comment by MrBurns010** [comment]
@SR-Morli 
Das liegt daran, dass, wenn man das Buch vom Kleiderladen öffnet, man in eine andere Dimension portiert wird. Somit verliert das Pferd den Bezug zum Spieler und wird von Script nicht mehr erkannt. Bitte den Spieler dahin gehend informieren, dass er sein Pferd wegschicken soll, bevor er in den Kleidungsladen geht.

@fraupan 
Ist es möglich hierfür eine Funktion einzubauen, dass, sobald der Spieler in eine andere Dimension portiert wird, dass sein Pferd über das Script automatisch gelöscht werden kann?

**Comment by fraupan** [comment]
> @fraupan Ist es möglich hierfür eine Funktion einzubauen, dass, sobald der Spieler in eine andere Dimension portiert wird, dass sein Pferd über das Script automatisch gelöscht werden kann?

Ist bestimmt machbar. Ich probier es aus. Alternativ kann ich bei dem Kleidungsscript nen Export reinschmeißen, damit die Pferde despawnt werden.

**Comment by MrBurns010** [comment]
Auch ne super Idee. Ist ja alles offen beim Clothing. Danke dir! @fraupan
