### ISSUE TITLE
[BUG]Handtasche/Ledertasche keine Funktion

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#120]
**Beschreibe den Fehler**
Ich hatte bereits gestern das Ticket aufgemacht bezüglich der Rucksäcke. 
Ebenfalls gibt es im General Store die Handtasche und die Ledertasche. Beide haben keine Funktion und sind nicht verwendbar.

**Nachstellbar**
JA
1. Nehme eine Handtasche oder Ledertasche aus einer Kutsche/Satteltasche.
2. Nicht die selbe Funktion wie die Rucksäcke

**Erwartetes Verhalten**
Erweitert dass Inventar wie die Rucksäcke

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i4I68LvFPuRxiq-X2/fc19H6e61z6M?invite=cr-MSxMMGIsMjA1NDY3ODgxLA?mobilebypass=true

**Kontaktdaten Melder**
 - IC-Name: Abraham Addams
 - Discord: evil_kali

**Comment by MrBurns010** [comment]
Kommen die Tage über ein Update. Das müssen wir noch angepasst werden, damit es optisch passt und die Tasche nicht in der Luft fliegt. 

Gerne den Spieler informieren @SRIcely

**Comment by SRIcely** [comment]
Ich denke dieses Thema kann geschlossen werden?
