### ISSUE TITLE
[BUG] Boote Laden out of order

### ISSUE THREAD

**Issue by SR-Morli** [Sundown-Rising/sundown-rising-issues#121]
**Beschreibe den Fehler**
Es kam die Meldung rein, dass bei dem Bootsausleger in Thieve´s Landing nicht auf den Bootsladen zugegriffen werden kann (keine Boote gekauft werden können). Alle anderen Optionen wie die Reise nach Guarma sind aktiv und können auch benutzt werden. (siehe clip).

Spielerin wurde gebeten das ganze noch an einem anderen Bootsausleger zu testen, ob Boote gekauft werden können. Nachtrag kommt als Kommentar :)

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Gehe zum Bootsausleger
2. Wähle die Option Boot kaufen mit [Leertaste]
3. (FEHLER) Keine Reaktion, kein shop öffnet sich.

**Erwartetes Verhalten**
Shop öffnet sich und man kann zwischen den verschiedenen Booten/Kanu´s auswählen

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.
https://medal.tv/de/games/red-dead-2/clips/i52ivUQspC-HzOzlK/d1337SouPYC5?invite=cr-MSxvbkMsMTkxMDA0MTUyLA

**Kontaktdaten Melder**
 - IC-Name: Flinke Eule
 - Discord: sandranasty

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.
Ergänzung (Screenshot der F8 Konsole wird nachgereicht in Kommentar)

**Comment by SR-Morli** [comment]
![grafik](https://github.com/Sundown-Rising/sundown-rising-issues/assets/172885539/4a4ef803-20e9-4c63-b3d2-65466fe9c3c0)

Einmal der Screenshot der F8 Konsole

Fehler tritt wie vermutet bei allen Bootsanlegern auf. Laden aktuell nicht verfügbar.

**Comment by MrBurns010** [comment]
Script wird in Kürze ersetzt. Daher keine Bugfixes mehr.
