### ISSUE TITLE
[BUG] Rucksack synct nicht richtig

### ISSUE THREAD

**Issue by SR-Morli** [Sundown-Rising/sundown-rising-issues#122]
**Beschreibe den Fehler**
Sobald der Rucksack auf dem Rücken ist bleibt er dort. Legt man den Rucksack zurück in die Kutsche ist er dennoch auf dem Rücken sichtbar, allerdings nur für den Spieler der ihn ausgerüstet hat.

**Nachstellbar**
JA/NEIN
Falls Ja, folgende Schritte:
1. Rucksack ausrüsten (ins Inventar legen)
2. Rucksack ist auf dem Rücken? Ja/Nein?
3. Wenn Ja Rucksack zurück in die Kutsche/Satteltasche packen
4. (FEHLER) Rucksack wird immer noch auf dem Rücken angezeigt.

**Erwartetes Verhalten**
Rucksack sollte wieder verschwinden und die Kapazität der Tasche kleiner werden.

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.
Werden nachgereicht, da Clip eine länge von 4 Stunden hat.

**Kontaktdaten Melder**
 - IC-Name: Jody Holiday
 - Discord: hundnala

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
Fehler im Live Test nicht nachstellbar. Problem wird auf Clientside vermutet. Empfehlung Cache Löschen

**Comment by Twackerino** [comment]
Zu 2 zusätzlicher Command eingebaut /reloadbackpack womit diese manuell reloaded werden können
