### ISSUE TITLE
[BUG] Poncho + Bandana rasiert Bärte

### ISSUE THREAD

**Issue by Lenemortis** [Sundown-Rising/sundown-rising-issues#123]
**Beschreibe den Fehler**
Spieler berichtet von der Problematik, dass er bei Outfits die in Verbindung mit Poncho 10 stehen, der Bart nach abziehen des Bandanas verschwindet. Hinzukommt das er 2x das Bandana auswählen muss, bevor er es hochziehen kann.

**Nachstellbar**
JA
1. Bandana zweimal aktivieren
2. Bandana hochziehen
3. Bereich innerhalb des Bandanas verdeckt
4. Bandana abziehen
5. Bart ist weg

**Erwartetes Verhalten**
Bandana mit dem Poncho verwenden können, ohne das der Bart verschwindet

**Screenshots/Videos**
<a href='https://postimg.cc/k2x4xSNJ' target='_blank'><img src='https://i.postimg.cc/k2x4xSNJ/Bandana-Bart-Bug.png' border='0' alt='Bandana-Bart-Bug'/></a>
(in der F8 Konsole war nichts sichtbar - war bei einer Liveübertragung dabei)

**Kontaktdaten Melder**
 - IC-Name: William McGiggle
 - Discord: 713344732331376720

**Comment by MrBurns010** [comment]
Bitte einen Clip inkl. F8 einreichen. Ansonsten können wir diesen Fehler nicht an den Entwickler weiterleiten.
@Lenemortis

**Comment by Lenemortis** [comment]
@MrBurns010 
Hier das Video im Nachgang. Ich hoffe es ist Aussagekräftig genug.
https://youtu.be/TxgRCLCeatc

**Comment by MrBurns010** [comment]
befindet sich in Prüfung durch entwickler
