### ISSUE TITLE
[BUG] Umkleide Camping geht nicht.

### ISSUE THREAD

**Issue by SR-Morli** [Sundown-Rising/sundown-rising-issues#125]
**Beschreibe den Fehler**
Camping Umkleiden funktionieren aktuell nicht.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Geh zum Camp und baue eine Umkleide
2. Versuche die Umkleide zu benutzen
3. (FEHLER) Menü der Umkleide ist leer

**Erwartetes Verhalten**
Auswahl der einzelnen Optionen der Umkleide

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.
![grafik](https://github.com/Sundown-Rising/sundown-rising-issues/assets/172885539/98c2df9b-547b-46f2-9798-61cdd1bd42a8)
![grafik](https://github.com/Sundown-Rising/sundown-rising-issues/assets/172885539/22ff25ff-9640-4562-af31-f5708b02fe4f)

**Kontaktdaten Melder**
 - IC-Name: Wesley Moon
 - Discord: gamerworld92

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by MrBurns010** [comment]
Camping wird in Kürze ersetzt durch ein besseres Script. Hier erfolgt kein Bugfix mehr.
