### ISSUE TITLE
[BUG] Schminke beim Friseur funktioniert nicht

### ISSUE THREAD

**Issue by SR-Morli** [Sundown-Rising/sundown-rising-issues#126]
**Beschreibe den Fehler**
Die Farben beim Friseur funktionieren nicht bei der Schminke. Anstatt schwarz wird es rot-braun, obwohl schwarz ausgewählt ist. Dabei spielt die Farbe an sich keine Rolle, ändert sich nichts. Egal ob Lidschatten, Smoky Eyes, Rouge, oder Lippen.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1.Gehe zum Friseur
2. Versuche Schminkfarben einzustellen.
3. (FEHLER) Farbe bleibt gleich.

**Erwartetes Verhalten**
Farbe der Schminke sollte sich ändern und dann speichern beim kauf.

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.
wird in den Kommentaren nachgereicht.

**Kontaktdaten Melder**
 - IC-Name: Saya Davis
 - Discord: saya_chizu

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by SR-Morli** [comment]
https://medal.tv/games/red-dead-2/clips/i56LLV0CgXY3Car9J/d1337oABJDNc?invite=cr-MSxRdGosMjA1NDUwMzA2LA

**Comment by MrBurns010** [comment]
21 Uhr kommt ein Update. Danach bitte nochmal testen und gerne feedback

**Comment by MrBurns010** [comment]
zu 2 Uhr gefixt
