### ISSUE TITLE
[BUG]Telegrammnummer-Bestatter-Rhodes-buggy

### ISSUE THREAD

**Issue by SRHannah-Sundown** [Sundown-Rising/sundown-rising-issues#127]
**Beschreibe den Fehler**
Spieler meldet das die Telegrammnummer des Bestatters in Rhodes immer noch nicht funktioniert

**Nachstellbar**
JA/NEIN - Da die Telegrammnummer nicht funktioniert. gibt es keine nachvollziehbaren Schritte.
Falls Ja, folgende Schritte:
1. Geh zum Wasser
2. Nimm eine Angel raus
3. Lass einen Fisch anbeißen und hole ich ihn ein.
4. (FEHLER) Hab keinen Fisch im Inventar

**Erwartetes Verhalten**
Funktionstüchtige Telegramm Nummer

**Screenshots/Videos**

Kein Clip vorhanden

**Kontaktdaten Melder**
 - IC-Name:
 - Discord: xxliiisaaaxx

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
zu 21 behoben
