### ISSUE TITLE
[BUG]Ballon-parken-führt-zu-spammeldung

### ISSUE THREAD

**Issue by SRHannah-Sundown** [Sundown-Rising/sundown-rising-issues#128]
**Beschreibe den Fehler**
Sobald der Ballon geparkt ist und man sich etwas weiter entfernt, fängt rechts im Bildschirm die Meldung "Ballon geparkt" zu spammen.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Parke den Ballon beim Ballonguy
2. Entfernen vom Parkplatz
3. Meldung "Ballon geparkt" erscheint
4. (FEHLER) Die Meldung wird dauerhaft immer wieder eingeblendet

**Erwartetes Verhalten**
Einmalige Meldung das der Ballon geparkt wurde.

**Screenshots/Videos**

https://medal.tv/de/games/red-dead-2/clips/i552XoAUfjKP7ysS3/d13376WfXLXY?invite=cr-MSw3a2csMjA1NDY3ODgxLA
https://medal.tv/de/games/red-dead-2/clips/i553LlZvfkDWWeTIQ/d1337IcA464Y?invite=cr-MSxQM2csMjA1NDY3ODgxLA

**Kontaktdaten Melder**
 - IC-Name: Abraham Addams
 - Discord: evil_kali

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by MrBurns010** [comment]
Update für 21 Uhr. Bitte danach nochmal testen und Feedback geben. Danke :-) @SRHannah-Sundown

**Comment by SRHannah-Sundown** [comment]
Leider hat sich laut Spieler nichts geändert, er kann den Ballon nicht einparken und der Server spammt die Nachricht trotzdem immer weiter.

**Comment by MrBurns010** [comment]
@SRHannah-Sundown 
Gibt es einen Fehler in der F8 Console?

**Comment by MrBurns010** [comment]
https://medal.tv/games/red-dead-2/clips/i5BbeZ79gMPzIigD7/d1337weqGHwZ?invite=cr-MSxkengsMzc0MjYxNjAs

@SRHannah-Sundown 

Fehler kann nicht reproduziert werden. Bitte einmal zusammen mit dem Spieler Folgendes durchführen:
https://discord.com/channels/1123352191751704606/1134952931574173818

Wenn der Fehler danach noch immer besteht, bitte einen Clip von Anfang des Ausparkens bis ende. Inkl. F8 Log

**Comment by SRHannah-Sundown** [comment]
https://medal.tv/games/red-dead-2/clips/i5BhPwaIyjuVPwCPD/d13373mZeP7L?invite=cr-MSxwS08sMjA1NDY3ODgxLA

Spieler schrieb folgendes:
Vorhin hat es dauerhaft einen rein gehauen, also irgendwas muss sich gebessert haben. Aber jetzt spamt es da keinen mehr rein
Das war vor 21 Uhr und ist auch jedes mal gewesen wenn ich geschaut hatte. Nun ist es still um die Console ^^.

Vielleicht hilft es auch zu sagen, das ich in den Stadium keinen neuen Baloon ausparken kann aber den Existierenden der "Eingeparkt" wurde auch nicht mehr "mir" gehoert und daher nicht geflogen werden kann. Zudem hoert die Spam benachrichtigung in der Kino ansicht auf haha.

**Comment by MrBurns010** [comment]
fakt ist, seit 21 Uhr keine Probleme mehr ja? :-D
 @SRHannah-Sundown

**Comment by SRHannah-Sundown** [comment]
Leider nein.
Zitat: "Also eigentlich sind keine Probleme behoben. ^^ Wenn ich zu weit vom Ballon weg gehe sagt es Ballon geparkt. Was er auch macht.... irgendwie, den dort wo der Ballon ist bleibt ein Ballon den ich nicht fliegen kann. Aber ich kann weiterhin den Ballon nur an den Ausparkpunkten einparken. (Was ja fein ist) aber ohne neu joinen kann ich das nicht da er sagt das der Baloon noch draußen ist.
[00:09]
Und dann kommt das spammen xd" - Zitat Ende....
Da scheint es doch noch einiges an Problemen zu geben. Der Fehler Spam ist wohl weg, aber der Rest bleibt bestehen.
(Ich versuche noch raus zu bekommen, ob er die Schritte aus dem "User-Spezifische Fehler" gemacht hat, bisher wurde da im Ticket nicht drauf reagiert!)

**Comment by MrBurns010** [comment]
@SRHannah-Sundown 

1. https://discord.com/channels/1123352191751704606/1134952931574173818

2. Clip von Anfang bis Ende und per Bildschirmübertragung zuschauen.

3. Selbst ausprobieren, ob du diesen Fehler reproduzieren kannst.

Diesen Clip bitte hier einsenden. Ansonsten ist eine weitere Bearbeitung **nicht** möglich, da niemand von uns diesen Fehler nachstellen kann.

**Comment by SR-Morli** [comment]
Der Ballon führt immer noch zu Problemen ich füge das mal hier noch mit ein, sollte ich dazu ein neues Ticket eröffnen müssen, bitte einmal Bescheid geben :)

"Beim Ballon passiert nichts wenn ich den Button "R" drücke. Auch können sich Leute nicht in der Gondel aufhalten, da sie ansonsten zu Boden fallen und Schaden nehmen."

https://medal.tv/de/games/red-dead-2/clips/i6eJa5d7MXtqinu0Y/d1337TzhIrNk?invite=cr-MSxpWDIsMTc1NjQxNzMxLA
