### ISSUE TITLE
Namechange Blutdiamant Ring

### ISSUE THREAD

**Issue by Helmard** [Sundown-Rising/sundown-rising-issues#129]
Bitte das Item "Blutdiamant Ring" mit dem Namen "Rubinring" ersetzen.

https://discord.com/channels/1123352191751704606/1251133555094978560

Wir haben uns zu diesem Namenswechsel entschieden, da der Name Blutdiamant einen gewissen Beigeschmack hat.

Danke

**Comment by Xuess22** [comment]
zu 2 Uhr erledigt @Helmard
