### ISSUE TITLE
[BUG] Native-Schilder werden nicht angezeigt

### ISSUE THREAD

**Issue by Twackerino** [Sundown-Rising/sundown-rising-issues#13]
**Beschreibe den Fehler**
Angelegte Native Schilder werden nicht bei anderen Spieler geladen

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Seid 2
2. Einer nimmt ein Schild raus
3. Person A sieht den.
4. (FEHLER) Person B nicht.

**Erwartetes Verhalten**
Person B sieht das Schild

**Screenshots/Videos**
https://www.youtube.com/watch?v=osK2w02gKOA
https://medal.tv/de/games/red-dead-2/clips/28HJq9WXlCaR4K/d13375h32vJp?invite=cr-MSxCb1gsMTk4NDcyNzc5LA
https://medal.tv/games/red-dead-2/clips/28ITiC3vtvSBqM/d1337Tm891hH?invite=cr-MSwydGwsMTk4NDcyNzc5LA

**Kontaktdaten Melder**
 - IC-Name: Nokomis Maska
 - Discord: diragon - 563055222935781380
 - IC-Name: Kleiner Fels
 - Discord: aytoon - 714573318602358786

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by MrBurns010** [comment]
typisches Sync Problem. Von uns leider nicht lösbar
