### ISSUE TITLE
[BUG]Telegramm-Taube-kommt-nicht-mehr

### ISSUE THREAD

**Issue by SRHannah-Sundown** [Sundown-Rising/sundown-rising-issues#130]
**Beschreibe den Fehler**
Mehrere Spieler haben angegeben, das die Taube, welche ein Telegramm ankündigt, nicht mehr auftaucht.

**Nachstellbar**
Unbekannt
Da man dieses Problem als normaler Spieler nicht rekonstruieren kann.

**Erwartetes Verhalten**
Sobald ein Telegramm ankommt, taucht eine Taube bzw Einblendung einer Taube auf.

**Screenshots/Videos**
Bisher keinen Clip oder Screenshot erhalten, Spieler aus Ticket gibt an, er kann davon keinen Clip erstellen, er kann sich schlecht selbst ein Telegramm schicken.

**Kontaktdaten Melder**
 - IC-Name: Elijah Clark
 - Discord: doggy1509

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
Notification funktioniert auf dem Main.
![grafik](https://github.com/Sundown-Rising/sundown-rising-issues/assets/58168452/c578b7e3-c05c-488a-bd56-30a4a7e10923)
