### ISSUE TITLE
[BUG] Joint ohne Wirkung

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#131]
**Beschreibe den Fehler**
Lemon Haze Joint sowie Orange Haze Joint haben keine Wirkung bei Benutzung.

**Nachstellbar**
JA
1.  Doppelclick auf Lemon oder Orange Haze Joint
2. Item verschwindet aus Inventar ohne Animation oder Wirkung

**Erwartetes Verhalten**
Man benutzt einen Joint. Dann beginnt eine Animation wie man den Joint raucht mit anschließenden Farbenspiel siehe Clip.
https://medal.tv/de/games/red-dead-2/clips/i5sSqX3eSTbDQSqTN/d1337VmbIy9I?invite=cr-MSxrTXksMTkxMjM3Mzc4LA

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i5sR4VMhrYdK7V7yg/d1337bU0q18b?invite=cr-MSw1WmosMTkxMjM3Mzc4LA
https://medal.tv/de/games/red-dead-2/clips/i57U9vDQMpGkSJIpE/d1337Gs8Dwyn?invite=cr-MSxJd1gsMjAyMjc2NjQ5LA

**Kontaktdaten Melder**
 - IC-Name: Elijah Clark
 - Discord: doggy1509

**Comment by MrBurns010** [comment]
um 2 Uhr gefixt
