### ISSUE TITLE
[BUG]Rezepte im Veredlungstisch nicht eingefügt ?

### ISSUE THREAD

**Issue by SR-Medusa** [Sundown-Rising/sundown-rising-issues#132]
**Beschreibe den Fehler**
Der Veredlungstisch in Rhodes (Nr. 3 ) funktioniert nicht so, wie es soll. Sobald man den Benutzen möchte, kommt die Meldung: " Oh, es gibt keine Rezepte."
Könnte da mal jemand drüberschauen ?
Zudem kann man einen veredelten Joint in Van Horn herstellen. Ist das so gewollt ? Ich dachte die sollen nur am 3ten Tisch gecrafted werden ?

**Erwartetes Verhalten**
Es wäre super, wenn da geprüft werden könnte, ob die Rezepte eingepflegt sind oder ob da was vertauscht wurde.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i5xpfThekS3kzE4Re/d1337fZsujUH?invite=cr-MSxYQXcsMTkzODY4OTc3LA

**Kontaktdaten Melder**
 - IC-Name: Wiyaka Mitchell
 - Discord:  230424600947851274

**Comment by MrBurns010** [comment]
https://medal.tv/games/red-dead-2/clips/i5CR1mlCAe0BVrOIE/d1337jv9LLLv?invite=cr-MSxrREIsMzc0MjYxNjAs

Ich denke, hier muss mal der Cache gecleart werden:
https://discord.com/channels/1123352191751704606/1134952931574173818

Arbeitsplatz 2 hat definitiv keinen veredelten Joint :-) siehe Config:
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/12be9b59-6d7a-403e-92ae-26f55c3f0966)

Am Veredelungsplatz war kein Item mit Erfahrung 0. Wenn man also nicht mindestens für ein Rezept die Erfahrungspunkte hat, wird angezeigt, dass man nicht das nötige Wissen (also die Erfahrungspunkte) hat. Siehst du in deinem Video mein 01:00 Min. Ich habe ihr mal die „Blättchen“ eingefügt. Somit öffnen sich das Buch nun, auch wenn man nicht genügend Erfahrung hat. Somit sollte es zu keinen Verwirrungen mehr kommen.

@SR-Medusa 

Bitte einmal Cache clearen und nochmal kurzes Feedback geben ob wir hier schließen können.

**Comment by SR-Medusa** [comment]
Mit cache Löschen funktioniert es jetzt. Prima. Ich danke dir @MrBurns010
