### ISSUE TITLE
Hut nicht aufsetzbar wenn Maske auf [BUG]

### ISSUE THREAD

**Issue by xxLiiisaaaxx** [Sundown-Rising/sundown-rising-issues#134]
**Beschreibe den Fehler**
Wenn man eine Maske auf hat ist es nicht möglich seinen Hut aufzusetzen.

**Nachstellbar**
JA

**Erwartetes Verhalten**
Das man seinen Hut aufsetzen kann.

**Screenshots/Videos**
https://youtu.be/LFOu5DHThjI

**Kontaktdaten Melder**
 - IC-Name: Cassidy Blackbeard
 - Discord: 802470240705052682

**Sonstiges**
Mit einem kleinen Trick lässt es sich lösen.
Allerdings wissen das viele Spieler nicht und verzweifeln.
Man muss die Reihenfolge beachten:
Char Reload ( dann hat man ja automatisch die Maske an )
Maske aus
Hut aufsetzen
Maske anlegen

Dann funktioniert es.

**Comment by MrBurns010** [comment]
weitergeleitet an Entwickler

**Comment by MrBurns010** [comment]
Rückmeldung:
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/e9b143ed-bc81-4d67-9a9b-0b6d9c062b5f)

Es wird in Zukunft über ein Update möglich sein. Dies erfordert jedoch einiges an Arbeit und wird nicht kurzfristig kommen. Ist aber notiert und wird eingefügt.

Spieler bitte Informieren. Wir werden es über die Changelogs bekannt geben, wenn es da ist. @xxLiiisaaaxx
