### ISSUE TITLE
[BUG]Polizeibuch-öffnet-nicht-Strawberry-Office

### ISSUE THREAD

**Issue by SRHannah-Sundown** [Sundown-Rising/sundown-rising-issues#136]
**Beschreibe den Fehler**
Der Spieler hat IC keine Möglichkeit das Poizeibuch im Strawberry Office zu öffnen

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Geh in Strawberry ins Office
2. Gehe zum Tisch, E kann gedrückt werden, G für Lager kann gedrückt werden
3. Nach einigem hin und her laufen taucht ganz kurz das Enter Zeichen zum drücken auf, wird aber sofort wieder von E überlagert
4. (FEHLER) Enter Menü kann nicht geöffnet werden, da Enter zu schnell verschwindet

**Erwartetes Verhalten**
Man würde erwarten das die Enter Taste rechts unten im Bildschirm genau so lange da ist, das man Zeit hat den Punkt zu finden oder die Taste zu drücken.

**Screenshots/Videos**

https://medal.tv/de/games/red-dead-2/clips/i5Wy1TrsfoNn6JnZ8/d1337qgKG2ZB?invite=cr-MSxKb28sMTUyOTU4NDE4LA

**Kontaktdaten Melder**
 - IC-Name: James Anders
 - Discord: benny94

**Sonstiges**
In dem Video bei Zeitstempel 1:39 sieht man SEHR kurz die Entertaste aufblinken, ich musste das Video zweimal schauen, bis es mir dann aufgefallen ist.

**Comment by Twackerino** [comment]
Das Skript verhält sich wie zu erwarten. Der Punkt wird mit anderen Punkten lediglich überschnitten, darum die Änderung von Bug auf QoL

**Comment by MrBurns010** [comment]
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/495a1564-293c-4529-920a-137894b578a4)

Koordinaten wurden versetzt. Kleines Mapping hinzugefügt. Bitte Spieler informieren @SRHannah-Sundown
