### ISSUE TITLE
[BUG]Fehler-beim-Metalldetektor

### ISSUE THREAD

**Issue by SRHannah-Sundown** [Sundown-Rising/sundown-rising-issues#137]
**Beschreibe den Fehler**
Spieler berichtet von 2 Grabungen mit dem Metalldetektor bzw der Schaufel, aber beide male hat es keinen Schatz gegeben.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Grabe an der vorgesehenen Stelle bis der Kreis gefüllt ist
2. Meldung kommt; Wir haben genug gegraben
3. Meldung kommt: Wir schauen mal was es gibt
4. (FEHLER) Es passiert nichts, Spieler erhält kein Item, es erscheint keine weitere Meldung

**Erwartetes Verhalten**
Spieler bekommt seinen "Schatz"

**Screenshots/Videos**

F8 Konsole ist im Video sehr gut zu sehen, inklusive der Fehlermeldung.
https://medal.tv/games/red-dead-2/clips/i5RW588KJK834dBPV/d1337WW8dAMf?invite=cr-MSxaQnEsMzcwNDQwNzcs

**Kontaktdaten Melder**
 - IC-Name: SR|Amnesia
 - Discord: amnesia69

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Xuess22** [comment]
@SRHannah-Sundown ich find da grad keinen Fehler, weder in F8 noch im Skript.
Kannst du mal fragen was die Spielerin alles bisher gefunden hat?
Vielleicht kann man dann nach dem Ausschlussverfahren gehen.

**Comment by Xuess22** [comment]
@SRHannah-Sundown die Spielerin hat wohl kurz darauf ein Timeout gehabt, deshalb hat sich alles aufgehangen. Das ist definitiv kein Fehler vom Skript. :)
