### ISSUE TITLE
[BUG]kameraeinstellung-umkleide-brauerei-lavendelwiese

### ISSUE THREAD

**Issue by SRHannah-Sundown** [Sundown-Rising/sundown-rising-issues#139]
**Beschreibe den Fehler**
Spieler gibt an, die Kamera bzw der Kamerawinkel in der Umkleide einer Brauerei bei der Lavendelwiese, hat eine komische Sichtweise, siehe Video.

**Nachstellbar**
JA/NEIN
Falls Ja, folgende Schritte:
1. Stellen in die Umkleide
2. Öffne Keiderrad
4. (FEHLER) Kamera schwenkt so, das der Char fast aus dem Sichtfeld ist

**Erwartetes Verhalten**
Kamera zeigt Char und Kleidung an

**Screenshots/Videos**

https://www.youtube.com/watch?v=xLK-LxTBesc

**Kontaktdaten Melder**
 - IC-Name: Elena Welingten
 - Discord: demonenjager

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by MrBurns010** [comment]
@SRHannah-Sundown 

Garderobe ist **_nicht_** dafür gedacht, dass man zusätzlich das Kleidungsrad öffnet. Entweder man geht in die Garderobe oder man wählt etwas über das Kleidungsrad. Beides ist absolut quatscht!

Kleiderschrank können wir versetzen, damit es besser mi der Kamera passt.

**Comment by SRHannah-Sundown** [comment]
Ich gebe das an die Spielerin so weiter, das mit dem Kleiderschrank versetzen klingt gut, das behebt vielleicht schon ein wenig Unmut.

**Comment by MrBurns010** [comment]
Kleiderschrank wurde etwas nach vorn versetzt. Bitte die Spielerin informieren, dass sie sich nicht direkt in die Ecke stellen soll. Dann gibt es auch keine Probleme. Ist ab 21 Uhr auf dem Mainserver. @SRHannah-Sundown
