### ISSUE TITLE
[BUG] Kleider buggen. Haut durch Stoff

### ISSUE THREAD

**Issue by Twackerino** [Sundown-Rising/sundown-rising-issues#14]
**Beschreibe den Fehler**
Haut scheint durch die Klamotten.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Weibliches PED
2. Hosen suchen im Schneider
3. Buggen teils.

**Erwartetes Verhalten**
Hosen bedecken die Haut

**Screenshots/Videos**
![grafik](https://github.com/Sundown-Rising/sundown-rising-issues/assets/58168452/fde71da2-94c9-4eff-9877-aa24a3ad1210)

**Kontaktdaten Melder**
 - IC-Name: Anaki Watanka
 - Discord: blue_nudel1408 - 406027750508462090

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by MrBurns010** [comment]
Kommt durch "FemPedTextures" im Mapping-Ordner. Das Problem ist, dass hier für die weiblichen Peds Beine und Brüste generiert werden, die bei einigen Kleidungsstücken zu Fehlern führen. Es gibt hierbei nur zwei Möglichkeiten:

1. Kein FemPedTextures mehr und somit wieder Löcher in den Körpern
2. Andere Kleidung suchen

**Comment by MrBurns010** [comment]
Erneute Abstimmung wenn die neuen Kleidungsstücke da sind.
