### ISSUE TITLE
[BUG]Fehlende-Blips-Ballonverleiher-und-Bootsanleger

### ISSUE THREAD

**Issue by SRHannah-Sundown** [Sundown-Rising/sundown-rising-issues#141]
**Beschreibe den Fehler**
Mehrere Spieler beschreiben Probleme mit fehlenden Blips und/oder Funktionen für den Ballonverleiher und die Bootsanleger.
Schiffsanleger in Annesburg und der dortige Ballonverleiher funktionieren nicht.
An manchen "alten" Standorten funktioniert es auch ohne einen Blip auf der Map Ballons/Schiffe zu holen.

**Nachstellbar**
JA

**Erwartetes Verhalten**
Blips für Boote und Ballon auf der Karte und funktionierende Funktionen am richtigen Spot.

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.

**Kontaktdaten Melder**
Ticket vom 19.06. 15:37
 - IC-Name: Robert Blue
 - Discord: bluecher1967

 Ticket vom 16.06. 16:40
- IC-Name: Abraham Addams
- Discord: evil_kali
 
Ticket vom 19.06. 10:32
- IC-Name: Jack Hunter
- Discord: mario_1980

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by MrBurns010** [comment]
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/c03dd24e-221e-48c7-9193-9a648f92b029)

Ich bin zwar alt ... aber ich seh sowohl Blips für Boote als auch Ballon  @SRHannah-Sundown

**Comment by MrBurns010** [comment]
Kein Clip ....
Kein Fehler reporduzierbar ....

@SRHannah-Sundown Bitte die Themen überprüfen, bevor hier gemeldet wird. Kostet nur unnötig Zeit, wenn doch alles klappt oder der Spieler den Cache nicht gecleart hat.

![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/770dfd3d-9aa5-41ad-b637-31fd5d122e3b)

![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/937ff3c0-d969-4942-b7b0-210e88dcdb03)

**Comment by SRHannah-Sundown** [comment]
Hab ich so weiter gegeben, vielen Dank^^
