### ISSUE TITLE
[BUG]Bankschalter BW funktioniert nicht

### ISSUE THREAD

**Issue by SR-Medusa** [Sundown-Rising/sundown-rising-issues#144]
**Beschreibe den Fehler**
Der Bankschalter in BlackWater spinnt aktuell. Auf mein Konto in Armadillo kann ich jedoch ohne Probleme drauf zugreifen.

**Erwartetes Verhalten**
Prüfung vom Skript. Ist da vielleicht etwas kaputt gegangen ?

**Screenshots/Videos**
[Bitte Screenshots oder Videos, mit der F8 Konsole.
](https://medal.tv/de/games/red-dead-2/clips/i6nS3SK0g-Cp_XoFU/d1337EM6pSuk?invite=cr-MSxiN1IsMTkzODY4OTc3LA)

**Kontaktdaten Melder**
 - IC-Name: Annabelle McCown
 - Discord: SR|Medusa

**Comment by Twackerino** [comment]
Spieler im Bankmenü gecrashed. Problem nach Restart verschwunden.
