### ISSUE TITLE
[BUG] Ballon Spawn Strawberry versetzen

### ISSUE THREAD

**Issue by SR-Morli** [Sundown-Rising/sundown-rising-issues#145]
**Beschreibe den Fehler**
Ballon spawnt mitten im NPC und führt zu Handlingproblemen mit Ballon
**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Ballon rufen in Strawberry
2. Versuchen zu starten.

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Fisch als Item im Inventar

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.
https://medal.tv/de/games/red-dead-2/clips/i6eJa5d7MXtqinu0Y/d1337TzhIrNk?invite=cr-MSxpWDIsMTc1NjQxNzMxLA

**Kontaktdaten Melder**
 - IC-Name: Roderick Rogers
 - Discord: schokiii

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by MrBurns010** [comment]
Closed weil Ticket völlig falsch!

- Ballon in Strawberry
- Video zeigt nicht Strawberry und nichts aus der Fehlerbeschreibung
- Erwartetes Verhalten -> Fisch als Item im Inventar

So wird das nichts ....
