### ISSUE TITLE
Anzeigebug HUD

### ISSUE THREAD

**Issue by XPeTerchenX** [Sundown-Rising/sundown-rising-issues#146]
**Beschreibe den Fehler**
Sprachreichweitenanzeige bei Serverconnect auf **8m**
Sprachweite ist jedoch nur auf **3,5m** bei Connect.

**Belege*
Test mit Ticketersteller

**Kontaktdaten Melder**
 - IC-Name: Rose Turner
 - Discord: 366371349108621312

**Sonstiges**

**Comment by MrBurns010** [comment]
Sprachanzeige wird durch neue HUD ersetzt. Fehler wird damit behoben
