### ISSUE TITLE
Bank Warteschlange

### ISSUE THREAD

**Issue by XPeTerchenX** [Sundown-Rising/sundown-rising-issues#147]
**Beschreibe den Fehler**
In der Nacht bekommt man Meldung in der Warteschlange.
Bankmann steht auch nicht da.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Geh zum Bankschalter
2. Öffne Schließfach
3. FEHLER: Warteschlange

**Erwartetes Verhalten**
Schließfach wird geöffnet oder Meldung Bank hat geschlossen.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i6rDaBSY64JICBXd3/d1337iIRblDw?invite=cr-MSxvclMsMTUyOTU4NDE4LA

**Kontaktdaten Melder**
 - IC-Name: James Anders
 - Discord: 805742437544886322

**Sonstiges**

**Comment by Twackerino** [comment]
Passiert wenn spieler im Bank schalter crashed behebon nach Restart. Kann durch uns nicht verhindert werden
