### ISSUE TITLE
[QoL] Thema Kohle bei Booten.

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#148]
**Beschreibe die Verbesserung**
Der Verbrauch von Kohle bei den Dampfbooten ist recht hoch. Bei dem alten Script habe ich bei der Strecke von Blackwater zur Braithwaite 100 Kohle verbraucht was 5 Kohlenuggets entspricht. Bei dem neuen Script bin ich aktuell bei 7 Kohlenuggets für die selbe Strecke. 

Ebenfalls ist mir aufgefallen dass man Kohle nur nachfüllen kann wenn mindestens 10 Kohle im Kohlelager Platz haben.
Könnte man dies ändern so dass man immer nachfüllen kann? Verlorene Kohle wäre halt dann "Pech"

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i6L50NzDsA6eyVQi4/d1337PTyqNDY?invite=cr-MSxVaXAsNzcyMDI1Njks
https://medal.tv/de/games/red-dead-2/clips/i79EK94IZJv_XmHDp/d1337PR1eqWa?invite=cr-MSxLOUUsMTkxMjM3Mzc4LA

**Kontaktdaten Melder**
 - IC-Name: Jack Winchester
 - Discord: stormi_gaming

**Comment by Twackerino** [comment]
Bitte erst an CM -Wirtschaft. User haben kein "Ich heul mal also setzen devs es um recht".

**Comment by SRIcely** [comment]
Habe mit Helmard gesprochen. Es wird nichts geändert.
