### ISSUE TITLE
[Gewerbe] Hunters Rest Crafting

### ISSUE THREAD

**Issue by Twackerino** [Sundown-Rising/sundown-rising-issues#15]
**Welches Gewerbe?**
Hunters Rest

**Problem / Anfrage**
Crafting Rezepte
[HuntersRest.xlsx](https://github.com/Sundown-Rising/sundown-rising-issues/files/15376094/HuntersRest.xlsx)

**Kontakt - Gewerbeamt**
Nick

**Kontakt - Gewerbe**
IC-Name: Jackie Moon
Discord: fuxine - 809917695772065792

**Sonstiges**
Sonstige Informationen

**Comment by nickbrick03** [comment]
Alle offenen Aufgaben abgearbeitet, alles wurde getestet und funktioniert.
