### ISSUE TITLE
[BUG] Ballons extrem schnell

### ISSUE THREAD

**Issue by DevGonzi** [Sundown-Rising/sundown-rising-issues#151]
**Beschreibe den Fehler**
Ballons fliegen unrealistisch schnell

**Nachstellbar**
JA - getestet auf LIVE Server 
1. 50$ dabei haben
2. Ballon mieten
3. Einsteigen
4. Hochfliegen
5. W/A/S/D zum sehr schnellen fliegen nutzen

**Erwartetes Verhalten**
Ballon sollte in einer Realistischen Geschwindigkeit fliegen.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i7BYhspPOSSD5AI2N/XYufTWCoMCW8?mobilebypass=true
von gonzi: https://www.youtube.com/watch?v=3sB-o5D3T8I

**Kontaktdaten Melder**
 - IC-Name: Roderick Rogers
 - Discord: schokiiii

**Comment by Xuess22** [comment]
Ist so eingestellt worden weils vorher so langsam war.
@DevGonzi 
Also eine gewünschte Änderung.
