### ISSUE TITLE
Ändern der Animation der Wundsalbe wenn möglich

### ISSUE THREAD

**Issue by Relegatos** [Sundown-Rising/sundown-rising-issues#153]
Hallo liebes Dev-Team ich als CM-Medic habe eine Abstimmung eingebraucht welche sich auf die noch IC befindliche "Wundsalbe" bezieht . 
Mei vorschlag ist , das man die Animation ändert, welche zu Zeit noch die ist von Face-DMG script (was ja abgeschaltet ist) , in eine Animation wo der Char eine " Eincremebewegung" macht .
Somit könnte man die Wundsalbe weiter IC nutzen als Medic-Item und als RP-Item wo sich die "Verletzten" selbst mit der Salbe Eincremen können zur Wundbehandlung . Dabei soll das Item KEINE Heilung oder sonst was geben .

Sollte dies nicht möglich sein oder das Item soll vom Server genommen werden ( wegen Platzmangel etc. ) dann bitte ich um entsprechende Mitteilung .

Danke und Gruß Rele

anbei der link zu Abstimmung : https://discord.com/channels/1123352191751704606/1252672172430721134

**Comment by MrBurns010** [comment]
@Relegatos hast du eine Animation dafür? Ich habe keine gefunden ....

**Comment by Relegatos** [comment]
jaa ich eben auch nicht deswegen ja meine frage ob das möglich ist oder ob in dem Emote Skript evt noch emotes drin sind die Spieler nicht sehen/kennen

**Comment by Xuess22** [comment]
Also @Relegatos wir können die Salbe gerne als "nice to have" einbauen, eine gewünschte Animation musst du uns aber vorgeben. Ich geh da jetzt nicht alle durch die es in RedM gibt, da sitz ich hier 4 Stunden.
Bitte die Animation verlinken, dann bau ich dir das ein. Gruß Sabrina

**Comment by Twackerino** [comment]
https://www.rdr2mods.com/wiki/pages/list-of-animations-dictionaries-and-animations-r21/
Bitte dann ggf um neues issue
