### ISSUE TITLE
[BUG] Bootsverschönerung nicht erwerbbar

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#154]
**Beschreibe den Fehler**
In den Changelog´s für das Bootscript wurde angekündigt dass man die benötigten Items für die optischen Veränderungen der Boote
in den General Stores kaufen kann. Diese gibt es dort nicht zu kaufen.

Benötigte Items:
-Boot Farben
-Boot Lackierungen
-Boot Requisiten
Auch nochmal hier zu sehen:
https://medal.tv/de/games/red-dead-2/clips/i7UMS1dnrdwzQ1SCV/d1337Fg8pko7?invite=cr-MSw1THAsMTkxMjM3Mzc4LA

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i7UH5eeHVGWS1ALkf/d1337kEygNT7?invite=cr-MSx5STUsMTkxMjM3Mzc4LA
https://medal.tv/games/red-dead-2/clips/i79S68yErBp5jtAF3/d1337mxFrbBK?invite=cr-MSxVdFgsMjA1NDY3ODgxLA

**Kontaktdaten Melder**
 - IC-Name: Abraham Addams
 - Discord: evil_kali

**Comment by Xuess22** [comment]
@SRIcely https://discord.com/channels/1123352191751704606/1123558498127585321/1252698128377839711
Hier steht folgendes:
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170861947/7f07d842-1079-480b-833f-734a635ee025)

Kurzfristige Updates ( bedeutet, die kommen zeitnah rein )

**Comment by Xuess22** [comment]
Ich schließe hier, da es kein Bug ist
