### ISSUE TITLE
[BUG] Logbuch Item kann nicht weggeworfen werden wenn Sammelhändler Schlüssel Quest Aktiv

### ISSUE THREAD

**Issue by DevGonzi** [Sundown-Rising/sundown-rising-issues#155]
**Beschreibe den Fehler**
Logbuch Item kann nicht weggeworfen werden wenn Sammelhändler Schlüssel Quest Aktiv
Wenn man das Buch wegwirft kommt es nach kurzer zeit immer wieder.

**Nachstellbar**
JA
1. Nimm die Sammelhändler Schlüssel Quest an
2. Man bekommt das buch?
3. Wirf das buch weg
4. rejoin
5. buch wieder da

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Fisch als Item im Inventar

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i7MheHSh9XEuPEcjy/d13379K72yaT?invite=cr-MSxSR0wsMjAyMjc2NjQ5LA
https://medal.tv/de/games/red-dead-2/clips/i7Ms78N91us4pa9NC/d1337Kr7JVLH?invite=cr-MSxXa2UsMjAyMjc2NjQ5LA

**Kontaktdaten Melder**
 - IC-Name: Elijah Clark
 - Discord: doggy1509

**Sonstiges**
Amnesia hat das Problem auch.

**Comment by MrBurns010** [comment]
Ist korrekt. Solange es eine offene Quest gibt die dem Spieler in der DB zugeordnet ist bekommt er das Buch
