### ISSUE TITLE
Ändern Aloevera-Verband 

### ISSUE THREAD

**Issue by Relegatos** [Sundown-Rising/sundown-rising-issues#156]
ich bitte euch beim Aloeveraverband den effekt das dieser Hunger und Durst löscht auszuschalten weil das RP-lich schwachsinn ist , den Heileffekt 100 inner Heal soll bleiben .

Danke , Gruß Rele

**Comment by nickbrick03** [comment]
zu 21 Uhr am 26.06. geändert
