### ISSUE TITLE
Federpost 

### ISSUE THREAD

**Issue by Relegatos** [Sundown-Rising/sundown-rising-issues#157]
ist es möglich die Federpost so einzustellen/anzupassen das die Native auch Ärzte mit Dr.-Titel anschreiben können ?
weil das würde den Handel mit den Native einiges Vereinfachen , weil Native wohl kaum zum Telegramm Office gehen um zu schreiben.

Danke gruß Rele

**Comment by Twackerino** [comment]
Tun sie, das kann ich nach Telegrammprüfungen die ich unregelmäßig durchführe so sagen.
Native skript ist komplett verschlüsselt, keine änderung außerhalb der Config möglich.

**Comment by Relegatos** [comment]
ok danke für die schnelle antwort , dann kann ich das so weiter geben das es keine Möglichkeit gibt .
