### ISSUE TITLE
Kräuterbonbons 

### ISSUE THREAD

**Issue by Relegatos** [Sundown-Rising/sundown-rising-issues#158]
Welche Wirkung ( Heilung ) ist bei den Kräuterbonbons hinterlegt ? Weil in der Itemliste der Medic´s die Kräuterbonbons nicht aufgeführt .

Danke , Gruß Rele

**Comment by Twackerino** [comment]
Wenn die nicht in der von mir verfassten liste sind keine.

**Comment by Relegatos** [comment]
ok danke
