### ISSUE TITLE
[BUG] Kiste

### ISSUE THREAD

**Issue by Lenemortis** [Sundown-Rising/sundown-rising-issues#159]
**Beschreibe den Fehler**
Spielerin kommt nicht an die Spielertruhe.
Dreistelliger Code funktioniert nicht und Augenscheinlich wohl nicht sichtbar.
Koordinaten sind: {-1917.3818, -1073.2833, 76.0323, 113.7280}
Code: 638

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Geht an die Truhe Truhe
2. Versucht den Code einzugeben (andere aus Ihrem Volk kommt auch nicht dran)
3. Kiste lässt sich nicht öffnen

**Erwartetes Verhalten**
Man kann ohne Probleme auf den Inhalt der Kiste zugreifen

**Screenshots/Videos**
https://discord.com/channels/1123352191751704606/1254495782183243989/1254496056482336891
https://discord.com/channels/1123352191751704606/1254495782183243989/1254497284310302780

**Kontaktdaten Melder**
 - IC-Name: Mitena Altaha
 - Discord: 420325823405359104

**Comment by Twackerino** [comment]
Datenbank kann die Truhe sowie den Code auslesen. Bitte auslesen lassen und testen/schauen das kein nutzerfehler vorliegt

**Comment by nickbrick03** [comment]
Der Code der Kiste ist **123**

**Comment by nickbrick03** [comment]
Der Code der Kiste ist **123**
