### ISSUE TITLE
[BUG]Buggy Stuhl Strawberry

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#160]
**Beschreibe den Fehler**
Es gibt einen Stuhl im Welcome Center von Strawberry.
Wenn man sich dort hinsetzt und wieder aufsteht spawnt man in der Wand.

**Nachstellbar**
Ja
1. Setze dich auf den Stuhl
2. Beende die Interaktion

**Erwartetes Verhalten**
Man sollte wieder vor dem Stuhl spawnen nicht dahinter.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i8h5Ls8WxZ07DOJKd/d1337C18kInV?invite=cr-MSxPREIsMTkxMjM3Mzc4LA

Das stand im F8 Log: [    624031] [b1491_GTAProce]     RageNetTcpWorker/ ugc body: ticket=YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh&contentType=rdr2mission&queryName=GetMyBookmarkedContent&queryParams=%7blang%3a%5b%27de%27%2c%27en%27%2c%27fr%27%2c%27it%27%2c%27es%27%2c%27pt%27%2c%27pl%27%2c%27ru%27%2c%27es-mx%27%5d%7d&offset=0&count=500

**Kontaktdaten Melder**
 - IC-Name: Eugene Briggs
 - Discord: ikaali

**Comment by SRIcely** [comment]
Das selbe Problem haben wir bei einer Bank in Rhodes. Gegenüber von der Arztpraxis.

Screenshots/Videos
https://medal.tv/de/games/red-dead-2/clips/iaJLT89H9dafaCpmx/d1337zD9ICHp?invite=cr-MSw4ZEUsMTkxMjM3Mzc4LA
https://medal.tv/de/games/red-dead-2/clips/ia5VQyb0v38ZKKGXK/d1337ExzgUUO?invite=cr-MSxEbVosNzcyMDI1Njks

Kontaktdaten Melder
IC-Name: Jack Winchester
Discord: stormi_gaming

**Comment by MrBurns010** [comment]
RDR2 Mapping. Haben wir keinen Einfluss drauf.
