### ISSUE TITLE
[BUG] headshot man ziel direkt auf die Brust

### ISSUE THREAD

**Issue by SRKoch** [Sundown-Rising/sundown-rising-issues#161]
**Beschreibe den Fehler**
Eine klare Fehler beschreibung.
haben festgestellt, dass wenn man per "Fokusieren" zielst NICHT direkt auf den Kopf gezielt wird.
heißt tatsächlich, es waren ein paar mehr leute am cheaten als wir vielleicht erst gedacht haben, wenn leute so instant gekillt wurden.

**Nachstellbar**
JA durch kamui und lovie
Falls Ja, folgende Schritte:
1. Zielt auf die Brust.
2.   genau in die mitte

**Screenshots/Videos**
https://youtu.be/EDd4DWmiXto

**Kontaktdaten Melder**
 - IC-Name: Tosaka
 - Discord: SR Kamui

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
Soll ich mal kurz alle bannen? Was is die Aufgabe an die devs? Die feststellung hilft vl peterchen und support.

**Comment by SRKoch** [comment]
hab es falsch verstanden. dachte es geht um ein anzeige fehler beim fokus.^^ mein fehler

**Comment by joybtw** [comment]
Dann kann hier zu?

**Comment by XPeTerchenX** [comment]
MACH ZU

**Comment by Twackerino** [comment]
> MACH ZU

MACH DEN KOPF ZU
