### ISSUE TITLE
[BUG]Vogelscheuchen verschwinden

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#162]
**Beschreibe den Fehler**
Aber wie im Clip zu sehen, senkt sich die Scheuche beim Versuch sie zu platzieren nach unten in den Boden. Man muss also schnell "G" drücken damit man sie rechtzeitig richtig aufbaut. Des weiteren, kann aber niemand die aufgebaute Scheuche sehen, nur ich bzw. der, der sie auch aufgebaut hat.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Platziere eine Vogelscheuche

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Das jeder sie sieht und nicht im Boden verschwindet.

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1254712938745430127/1254719804577808474/uncapped_MedalTVRedM20240624095345.mp4?ex=667a8460&is=667932e0&hm=bcca9643d3f0b616f960621ebc341ab50b587d28f2b1932ff0f3854743ade451&

**Kontaktdaten Melder**
 - IC-Name: Jack Hunter
 - Discord: mario_1980 (741558445165248634)

**Comment by MrBurns010** [comment]
Keine Rückmeldung!!!!!! @SRCaesar
