### ISSUE TITLE
[BUG]Wapiti Tauschhändler Native

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#163]
**Beschreibe den Fehler**
Eine klare Fehler beschreibung.
In Wapiti steht eine Dame, die sonst immer die Ankäuferin war, damit man Federn verdienen kann. Neuerding Verkauft sie aber nur und Kauft nichts an.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Spreche mit der Tauschhändlerin in Wapiti

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Sie sollte die Sachen ankaufen und dem Spieler Federn dafür geben.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i8fP4jQSCQez0aYsX/d1337CtcyJHT?invite=cr-MSxsdzksMjMxNzk0OTg4LA

**Kontaktdaten Melder**
 - IC-Name: Manteo Yuma
 - Discord: tim_ratchet (281472221589798913)

**Comment by Twackerino** [comment]
https://discord.com/channels/1123352191751704606/1123558498127585321/1254150245521162240

**Comment by Twackerino** [comment]
Zu 2 Behoben
