### ISSUE TITLE
[BUG]Wassereimer/Wasserpumpe

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#164]
**Beschreibe den Fehler**
nachdem ich Wasserflaschen hergestellt habe, sind meine Eimer kaputt gegangen.
Ist das jetzt auch normal. dass man die Eimer nicht mehr an der Wasserpumpe füllen kann? Bei der sogenannten Gewerbepumpe kann ich nur Eimer füllen fürs Pflanzen gießen, ich kann weder meine Feldfalsche aufüllen noch daraus trinken.

**Nachstellbar**
JA/NEIN
Falls Ja, folgende Schritte:
1. Gehe zur Wasserpumpe und teste es aus.
**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Das man die füllen kann und trinken kann.

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1254335806563422219/1254384428873027644/10_kleine_Eimer.mp4?ex=667a9d89&is=66794c09&hm=8794f8ab2e8d3be62d0735efbf1f569c69a9ff45d15fd93260a2b123551fd39a&

**Kontaktdaten Melder**
 - IC-Name: Mitchell Lewis
 - Discord: tholang (810133059503915049)

**Comment by Xuess22** [comment]
@SRCaesar sollte zu 21 Uhr behoben sein, bitte nachfragen beim spieler
