### ISSUE TITLE
[BUG] Rucksack 

### ISSUE THREAD

**Issue by xPantherx2** [Sundown-Rising/sundown-rising-issues#165]
**Beschreibe den Fehler**
Betrifft Miningrucksack, wenn ich diesen aus den Satteltaschen meines Pferdes herausnehme und in meine Tasche lege, erhöt sich das Inventar von 250 auf 400. Schließe ich die Tasche dann hab ich einen Rucksack an der, wenn ich mich bewege, auf die Erde fällt. Lege ich den Miningrucksack wieder in die Sattel tasche zurück und schließe meine Taschen, dann bleibt der Inventar Inhalt auf 400. Entnehme ich wieder den Miningrucksack aus de Satteltasche und lege diesen in meine Tasche, dann erhöt sich der Inventar inhalt wieder um 200 auf mitlerweile 600. Habe dann aber wieder den Rucksack an, der dann beim Bewegen wieder runter fällt. Die erhöhung des Invetares bleibt aber auch wenn ich den wieder in die Satteltasche ablege. So das ich weiter einen Inventar von 600 habe der erst nach einem relogg wieder "normal ist.

**Erwartetes Verhalten**
Dass, wenn man den Rucksack wieder ins Pferd packt, die Inventar-Größe wieder auf die normalen 250 zurückgeht

**Screenshots/Videos**
Clip ist leider zu groß 

**Kontaktdaten Melder**
 - IC-Name: Charles Anderson
 - Discord: 313312937659990019

**Comment by xPantherx2** [comment]
https://medal.tv/de/games/red-dead-2/clips/i8lv8KjckDW3AdBXV/d1337yTpxK4H?invite=cr-MSxpWXksMTA1OTQ1OTIzLA

**Comment by MrBurns010** [comment]
Gab bereits ein Issue dazu:
https://github.com/Sundown-Rising/sundown-rising-issues/issues/149
