### ISSUE TITLE
[BUG] Ölfelder Verkaufen immer 0.15$ auch ohne arbeit

### ISSUE THREAD

**Issue by DevGonzi** [Sundown-Rising/sundown-rising-issues#166]
**Beschreibe den Fehler**
Geht man zum Office bei den Ölfeldern wird einem sofort das Verkaufen für 0.15$ angezeigt. Eine Andere Interaktion ist nicht möglich.
Dies war mir möglich ohne vorher zu arbeiten.

**Nachstellbar**
JA
1. Geh ins Office bei den Ölfeldern
2. (FEHLER) Ohne Arbeit wird das Verkaufen für 0.15$ angeboten, dies ist jedoch nicht möglich da man die Benötigten Items nicht hat.

**Erwartetes Verhalten**
Man sollte erst Arbeiten müssen, ebenso sollte man keine Gegenstände brauchen denke ich

**Screenshots/Videos**
Von Spieler:
https://medal.tv/games/red-dead-2/clips/i7BWiKo1K4VquPWfB/d133772LN1RO?invite=cr-MSxxT0osMjQ0ODMxMDUzLA

Von Gonzi:
![RedM_b1491_GTAProcess_axH039SbOs](https://github.com/Sundown-Rising/sundown-rising-issues/assets/35921566/48dd77bb-8ca6-4edb-b79c-61f97a84471c)

**Kontaktdaten Melder**
 - IC-Name: Kowal Henry
 - Discord: crisdaii

**Comment by Xuess22** [comment]
@DevGonzi Clip ist nicht mehr da, kann ihn mir nicht anschauen :/

**Comment by DevGonzi** [comment]
Siehe screenshot, zeigt das selbe

**Comment by MrBurns010** [comment]
Script wird in kürze ausgetauscht ... daher keine Fehlerbehebung mehr :-)
