### ISSUE TITLE
[BUG]Kräuterwasser Natives

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#167]
**Beschreibe den Fehler**
ich teste gerade alle Schamanen Items und musste feststellen, dass das Kräuterwasser nicht funktioniert. Das Item lässt sich gar nicht benutzen.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Doppelklick auf das Item

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Das man es benutzen kann

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1254818928094347358/1254823785861873705/image.png?ex=667ae538&is=667993b8&hm=e84a08b54b581cc572ce2d2f82ff7408660ac7bf4d4a57118d7bba740403f766&

**Kontaktdaten Melder**
 - IC-Name: Yakari Inola
 - Discord: flashback_81 (342387885351370752)

**Comment by Xuess22** [comment]
@SRCaesar 
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170861947/e8e95170-7f33-4edd-8e16-fe03867b6038)

Ich kann auf den Clip leider nicht zugreifen

**Comment by nickbrick03** [comment]
Ist zu 21 Uhr am 26.06. gefixt
