### ISSUE TITLE
[BUG] Verbrauch an Camp Reperaturkits höher als geplant

### ISSUE THREAD

**Issue by DevGonzi** [Sundown-Rising/sundown-rising-issues#168]
**Beschreibe den Fehler**
Laut Pan soll man bei über 50% Campstatus eins brauchen und bei unter 50% zwei Reperaturkits. User melden jedoch weiterhin, dass man selbst bei 93% zwei Rep-Kits braucht

**Nachstellbar**
NEIN - hab kein Camp

1. Geh zu deinem Camp (Es darf keine 100% haben logischerweise)
2. Öffne das Camp menü
3. Prüfe den Status deines Camps
4. Drücke auf "Status" um das Camp zu Reparieren
5. (FEHLER) Notify: "Lager - Du benötigst 2x Camp-Reparatur-Kit"

**Erwartetes Verhalten**
Gemäß der Info von Pan sollte man nur ein Rep-Kit brauchen, da das Lager 93% hat.

**Screenshots/Videos**
Userclip: https://medal.tv/de/games/red-dead-2/clips/i8t09ViQW6Bc9MJcp/UCJg8gGBDCkl?invite=cr-MSxpRDYsMjI5OTMwNzAwLA&mobilebypass=true

**Kontaktdaten Melder**
 - IC-Name: Viona Mertens
 - Discord: roccatc

**Comment by MrBurns010** [comment]
Es kommt ein neues Script
