### ISSUE TITLE
[BUG] Camp Baukreis reichweite Fehlerhaft

### ISSUE THREAD

**Issue by DevGonzi** [Sundown-Rising/sundown-rising-issues#169]
**Beschreibe den Fehler**
Der Angezeigte Baukreis entspricht nicht dem Tatsächlichen Baukreis 

**Nachstellbar**
NEIN - hab kein Camp

1. Geh zu deinem Camp
2. /camp
3. "Baukreis anzeigen"
4. (FEHLER) Der Baukreis wird weitaus größer angezeigt als er eigentlich ist

**Erwartetes Verhalten**
Der Baukreis sollte korrekt angezeigt werden.

**Screenshots/Videos**
Userclip: https://cdn.discordapp.com/attachments/1253658436944658534/1254742472161235094/uncapped_MedalTVRedM20240624121207.mp4?ex=667a997d&is=667947fd&hm=787be4334d11a545afe0680372fe4cee4009d86458865b2e8b34539670907a8a&

**Kontaktdaten Melder**
 - IC-Name: Jackie Moon
 - Discord: fuxine

**Comment by Xuess22** [comment]
@DevGonzi lt. Ticket müsste der Fehler behoben worden sein, richtig?
