### ISSUE TITLE
native -Agairta Pilze Pet kick

### ISSUE THREAD

**Issue by XPeTerchenX** [Sundown-Rising/sundown-rising-issues#17]
**Beschreibe den Fehler**
Natives werden beim Essen des Agarita Pilzes in ein Pet verwandelt und dann gekickt.

**Nachstellbar**
JA -> pet bypass fehlt bei Natives

**Erwartetes Verhalten**
Natives können für 5min ein Pet bespielen.

**Screenshots/Videos**

![Bild_2024-05-21_180553677](https://github.com/Sundown-Rising/sundown-rising-issues/assets/143320133/1b49570c-6fa8-46b6-a525-477d4c1691b2)

**Kontaktdaten Melder**
 - IC-Name: Wesa Cheveyo
 - Discord: 318471752135081985

**Comment by Twackerino** [comment]
Sollte zu 2 behoben sein.
