### ISSUE TITLE
[BUG] Sheriff Buch Strawberry versetzen

### ISSUE THREAD

**Issue by DevGonzi** [Sundown-Rising/sundown-rising-issues#170]
**Beschreibe den Fehler**
Das Sheriff buch in Strawberry ist aufgrund seiner Platzierung nicht nutzbar

**Nachstellbar**
JA (auf devserver)

1. Teleportier dich nach Strawberry vor das Office {x=-1811.38, y=-348.24, z=163.35}
2. Setz dir den Job "sheriffsb 4"
3. Geh in das Innere und versuche mit dem Buch an der Treppe zu Interagieren
4. (FEHLER) Die Interaktionsmöglichkeit kommt für weniger als eine Sekunde, versucht man durch hin und herlaufen das Buch zu erreichen ist dies nicht möglich

**Erwartetes Verhalten**
Die Interaktion mit dem Buch sollte problemlos möglich sein

**Screenshots/Videos**
Userclip: https://medal.tv/de/games/red-dead-2/clips/i7U91ZplSd0mwbnqK/d1337ZAdtLZA?invite=cr-MSxFcFYsMTUyOTU4NDE4LA

**Kontaktdaten Melder**
 - IC-Name: James Anders
 - Discord: benny94

**Sonstiges**
Vorschlag, das Buch sollte wie z.B. in Valentine an einen Stützbalken / an die Wand platziert werden

**Comment by Xuess22** [comment]
@DevGonzi hat Spieler seinen Cache geleert?

**Comment by DevGonzi** [comment]
Ja, mehrfach.
Ich hatte ja das selbe problem auch als ich es auf dem Devserver getestet habe @Xuess22

**Comment by MrBurns010** [comment]
Buch versetzt.
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/6f556991-d6f5-4203-b7e6-e25d9cd89aab)
