### ISSUE TITLE
[BUG] Kutschenräder gehen seit update zu jedes mal beim Shiften sofort Kaputt

### ISSUE THREAD

**Issue by DevGonzi** [Sundown-Rising/sundown-rising-issues#171]
**Beschreibe den Fehler**
Räder von Kutschen gehen bereits wenn man die Kutsche das erste mal ausparkt und nur kurz Shiftet kaputt.

**Nachstellbar**
JA

1. Kutsche aus Stall holen
2. Auf die Kutsche setzen
3. Losfahren
4. Shiften
6. (FEHLER) Rad/Räder gehen sofort kaputt

**Erwartetes Verhalten**
Die Räder sollten nicht bei jedem mal losfahren direkt kaputtgehen sondern wie im Changelog angeben mit einer Wahrscheinlichkeit vom Shiften.

**Screenshots/Videos**
Clip von Peterchen: https://youtu.be/Y9kg6AZE_X8

**Kontaktdaten Melder**
 - IC-Name Melder 1: Crowley King
 - Discord Melder 1: king_crowley
 - IC-Name Melder 2: Carlos Rodriguez
 - Discord Melder 2: nony20

**Comment by Twackerino** [comment]
https://discord.com/channels/1123352191751704606/1123558498127585321/1255462951331303464
