### ISSUE TITLE
[BUG]Kein Waffenverkauf in Auslage möglich

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#172]
**Beschreibe den Fehler**
Man kann keine "Waffen" in die Auslagen packen. Wenn man versucht die Waffe der Auslage hinzuzufügen passiert nichts.

**Nachstellbar**
Ja
1. Nehme ein Item in dein Inventar welches einen Waffenslot belegt.
2. Gehe zur Auslage und öffne Angebot verwalten
3. Versuche die "Waffe" hinzuzufügen
4. Gebe den Preis ein

**Erwartetes Verhalten**
Dass man wie normale Items diese der Auslage hinzufügen kann um sie dort zu verkaufen

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i8r80W28S9VlHL_89/mdhoM91dqv3O?invite=cr-MSxCRmUsMjA5OTY2MDM1LA
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170888142/6199fb0b-0def-4cae-adb0-d44694939ac9)

**Kontaktdaten Melder**
 - IC-Name: Eleanor Knoxville
 - Discord: cateyes8087

**Comment by Xuess22** [comment]
@joybtw reminder
