### ISSUE TITLE
Jagdkutschen [Wunsch] 

### ISSUE THREAD

**Issue by xxLiiisaaaxx** [Sundown-Rising/sundown-rising-issues#173]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Aktuell kann nur der Inhaber der Kutschen Kadaver hineinlegen. 

**Beschreibe die gewünschte Lösung**
Wenn auch Leute mit Zugriffsberechtigung Kadaver hineinlegen können.

Bitte um Rückmeldung ob dies Möglich ist :)
Dankeeee :)

**Comment by Twackerino** [comment]
@fraupan Du hast da am meisten ahnung
