### ISSUE TITLE
Instrumente als stummes Item oder stummes Emote 

### ISSUE THREAD

**Issue by XPeTerchenX** [Sundown-Rising/sundown-rising-issues#175]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Den Spielern die Möglichkeit geben, Instrumente als Item oder Emotes zu nutzen ohne, das Musik dabei abgespielt wird.

**Beschreibe die gewünschte Lösung**
über ein Skriptanpassung oder neues Skript möglich

**Comment by Twackerino** [comment]
Nicht möglich.
