### ISSUE TITLE
[BUG]Wasserpumpe Eimer füllen

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#178]
**Beschreibe den Fehler**
an der Wasserpumpe die wir verkaufen und auch schon viele an die Farmer, kann man seit neuestem keine Eimer mehr befüllen. Nur noch trinken und seine Feldflasche auffüllen

**Nachstellbar | Auschließen Client Problemen**
JA
Falls Ja, folgende Schritte:
1. Geh zur Wasserpumpe und probiere es den Eimer zu füllen

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Der Eimer wird gefüllt. Bzw. es wird angezeigt, dass man ihn Füllen kann.

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1255616787421331610/1255629613284065320/20240626221120_1.jpg?ex=667dd3b4&is=667c8234&hm=9dc3bee9fc267214712d9a6936561f2578d71840219462e5715d1840ddd20346&

**Kontaktdaten Melder**
 - IC-Name: Wesley Moon
 - Discord: gamerworld92 (701472126959353968)

**Comment by MrBurns010** [comment]
ist kein bug sondern korrekt. Eimer füllen geht nur noch über Pumpen vom Farming Script
