### ISSUE TITLE
[BUG] Markt in ST.

### ISSUE THREAD

**Issue by xPantherx2** [Sundown-Rising/sundown-rising-issues#179]
**Beschreibe den Fehler**
Der NPC Händler am Markt in St. Denis kauft z.B. kein Baumharz an.
**Erwartetes Verhalten**
Das der NPc im markt Baumharz ankauft

**Screenshots/Videos**
noch nicht 

**Kontaktdaten Melder**
 - IC-Name: Jackie Moon
 - Discord: 809917695772065792

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
Dopplung #163
