### ISSUE TITLE
[BUG] Van Horn Crimequest NPC

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#18]
**Beschreibe den Fehler**
Der Crimequest NPC in Van Horn hinter dem Saloon hat die beiden legendären Felle entgegen genommen und anstatt Ihnen das Item für die Quest zu geben, gab er Ihnen 4 Questlog Bücher. Nun kann man den NPC auch nicht mehr ansprechen.

**Nachstellbar**
Der NPC spricht mit niemandem mehr. Nicht mit der Person die die 4 Questbücher bekommen hat noch andere Personen. Unabhängig von Crimejob oder nicht.

**Erwartetes Verhalten**
Der NPC sollte einem einen Gegenstand als Belohnung für die Quest geben. (Schere oder 2ter Schlüssel)

**Screenshots/Videos**
https://youtu.be/wf4kVNldO-I?si=bZVRTW92fEDSQWOU
https://youtu.be/jAD21zbFu28?si=sn9YtUeZbCJGqLIy

**Kontaktdaten Melder**
 - IC-Name: Ronald Goldstein
 - Discord: front776

**Sonstiges**

**Comment by Blutswente** [comment]
Selbes Problem auch im Ticket : 1244651731535663246

Gemeldet von der Person : 424613791779782667

**Comment by MrBurns010** [comment]
Bug gemeldet an NSS

**Comment by MrBurns010** [comment]
Questbücher dürfen nicht in die Pferdetaschen gesteckt werden. Ansonsten gehen die Meta-Informationen verloren. Alle anderen Bugs wurden gefixt.
