### ISSUE TITLE
[BUG] Stacks

### ISSUE THREAD

**Issue by xPantherx2** [Sundown-Rising/sundown-rising-issues#180]
**Beschreibe den Fehler**
ich kann nur 50 orangen saft tragen obwohl 100 angezeigt wird möglicherweise ist das bei den ganzen anderen sachen auch so konnte 

**Erwartetes Verhalten**
Das man 100 Orangensaft tracken kann 

**Screenshots/Videos**
noch nicht 
**Kontaktdaten Melder**
 - IC-Name: Felix Westfield
 - Discord: 198527086963458051

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by xPantherx2** [comment]
https://cdn.discordapp.com/attachments/1255530646122532885/1255884717480476783/image.png?ex=667ec149&is=667d6fc9&hm=af7a3fd8c23ebba85f27b27a51910b0b47fcd4a558a660bdf846df5c753ab908&

**Comment by xPantherx2** [comment]
https://cdn.discordapp.com/attachments/1255530646122532885/1255884717891256410/image.png?ex=667ec149&is=667d6fc9&hm=b848dc8f1102e32c3fdd4d7626b4e19208469f422ec38cf0cdcdb0dd4036ab28&

**Comment by xPantherx2** [comment]
https://cdn.discordapp.com/attachments/1255530646122532885/1255884718516211894/image.png?ex=667ec14a&is=667d6fca&hm=745ebbf7ffda275d112952a29ea67b1d988a7b89c65bbe80add41dff10269e56&       Einmal die bilder dazu

**Comment by Xuess22** [comment]
@xPantherx2 da das Ticket zu ist kann ich keine Clips sichten

**Comment by MrBurns010** [comment]
Unbeantwortet daher close

**Comment by MrBurns010** [comment]
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/acb612df-9d43-49f4-8a01-7476b2d38558)
