### ISSUE TITLE
[BUG]Kutschen Tiere laden

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#181]
**Beschreibe den Fehler**
wenn man Zugriff auf eine Kutsche bekommt, kann man Tiere entladen von Kutschen, die gar keine Tier laden können.

**Nachstellbar | Auschließen Client Problemen**
JA
Wurden Client-Fehler welche durch bspw. den Cache ausgelöst wurden ausgeschlossen (https://discord.com/channels/1123352191751704606/1131142465806675979 )
Falls Ja, folgende Schritte:
1. Erteile Zugriff auf eine Kutsche und schaue ob es funktioniert mit den Tieren

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Es sollten keine Tiere auf die Kutsche geladen werden können, die nicht dafrü vorhergesehen sind. 

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1255553085426630748/1255629264389406770/image.png?ex=667dd361&is=667c81e1&hm=974d78f6209620201be5a57416d972cf18981d7ff3c081a43c0b281b07a702b9&

**Kontaktdaten Melder**
 - IC-Name: Jackie Moon
 - Discord: fuxine (809917695772065792)

**Comment by MrBurns010** [comment]
Schon wieder nicht verfügbar !!!!

https://cdn.discordapp.com/attachments/1255553085426630748/1255629264389406770/image.png?ex=667dd361&is=667c81e1&hm=974d78f6209620201be5a57416d972cf18981d7ff3c081a43c0b281b07a702b9&

**Comment by SRCaesar** [comment]
Ohman okay ich kümmere mich drum. Woran liegt das weißt du das? @MrBurns010

**Comment by joybtw** [comment]
Einfach das Bild runter laden und hier mit beihängen.
Bei Clips das selbe

**Comment by fraupan** [comment]
Erkenntnis:
der "Tiere" Prompt ist in der selben Promptgruppe, wie "Lager". 
Muss getrennt werden. (mach ich noch)0

**Comment by fraupan** [comment]
Da die Funktion nur optisch stört und nicht in der Funktion, schließe ich das Ticket als "vorerst nicht geplant".
Mit dem neuen Pferde-Script wird das dann behoben.
