### ISSUE TITLE
[BUG]Wapititauschhändler

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#182]
**Beschreibe den Fehler**
Es werden wohl immer noch nicht Items getauscht. Zudem sind items im store dort die garnicht mehr gibt wie Native Salbe. Vielleicht sollte man das den neuen Items entsprechend anpassen. 

**Nachstellbar | Auschließen Client Problemen**
JA
Falls Ja, folgende Schritte:
1. Geh zum Händler
2. Spreche ihn an und versuche Honigverbände zu tauschen gegen Federn.

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Das der Händler dir die federn dafür gibt. 

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1255782558701191178/1255783628957286420/image.png?ex=667e6324&is=667d11a4&hm=1f6f2e47dc10dcb786ffac954baacae42b73cccdb0cde3d45a8b55073019254b&

https://cdn.discordapp.com/attachments/1255782558701191178/1255783628336795722/image.png?ex=667e6324&is=667d11a4&hm=24aa5dacd753172b51ea6c675fda0d723f4b41cd6c411a2670778dc5446ce855&

**Kontaktdaten Melder**
 - IC-Name: Yakari Inola
 - Discord: flashback_81 (342387885351370752)

**Comment by SRCaesar** [comment]
Zusatz vom User:
Beinschienen konnte ich verkaufen, aber wenn ich Honigverbände verkaufen will, kommt das.

https://cdn.discordapp.com/attachments/1255782558701191178/1255853664094916618/image.png?ex=667ea45e&is=667d52de&hm=7d0096fa9408b133dbe3e6265ec0688543fab77dc9d5c4d20688fd69d6ad866f&

https://cdn.discordapp.com/attachments/1255782558701191178/1255853665512587344/image.png?ex=667ea45e&is=667d52de&hm=449091e2043c0bbb8c305531d806673cdf9ed33005e7a2db8231f58fa8efd3c6&

**Comment by SRIcely** [comment]
Ebenfalls kam eine Meldung von einem Native dass man beim Tauschhändler nur die Option kaufen hat anstatt zu verkaufen.

Ebenso waren dort Gesichtsmasken beim Händler welche nicht herstellbar sind.

Screenshots:
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170888142/9bb4f43a-5c9b-4355-9f1d-c342b8ac4828)
![image2](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170888142/599e4017-f862-4c49-aae9-da50105e86f4)

Melder:
IC-Name: Adahy Black
Discord: sentinelprimerbmarc

**Comment by Twackerino** [comment]
sollte behoben sein
