### ISSUE TITLE
[Wunsch] Nakota Wasserpumpe

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#183]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Durch das neue Anpflanzsystem ist man wenn man nicht unmittelbar am Fluss ist an eine Wasserpumpe gebunden. 

**Beschreibe die gewünschte Lösung**
Nakota will in ihren Lager eine Wasserpumpe das es mit dem Anpflanzen leichter ist.

**Gibt es Alternativen die bereits überlegt wurden und warum reichen die nicht?**
Keine

**Sonstiges**
https://cdn.discordapp.com/attachments/1254945849616765031/1255089412652404827/image.png?ex=667dd6da&is=667c855a&hm=341b187c6728abf00f540b74c5e6c19d810ab06268c5c3b20ddae6379dc51426&

Wenn es geht die Pumpe neben dem Metzter stellen.

**Comment by Twackerino** [comment]
![Native_Nummerierung](https://github.com/Sundown-Rising/sundown-rising-issues/assets/58168452/89f3fba1-9dd0-4f93-ac2e-8d99c5c5a32a)
Ich such nicht auf der Karte nach dem Ort. Mindestens die Camp nummer noch besser die Coords

**Comment by SRCaesar** [comment]
Es ist die 9. Aber schaue auch noch nach den Koordinaten.

**Comment by Xuess22** [comment]
zu 21 Uhr gesetzt @SRCaesar
