### ISSUE TITLE
[Wunsch] Volkskisten von 10.000 auf 60.000 erhöhen

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#184]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Wir haben soeben in der Supporterrunde besprochen, dass die Volkskisten auf 60.000 erhöht werden können, wie bei den Ärzten. Sodass die ganzen vielen Kisten in den Lager wegkommen können und die Performance besser wird.

**Beschreibe die gewünschte Lösung**
Volkskisten der Völker von 10.000 auf 60.000 erhöhen.

**Gibt es Alternativen die bereits überlegt wurden und warum reichen die nicht?**
Es wurde überlegt wegen Kisten, gibt aber Performance Probleme und ist nervig.

**Comment by Xuess22** [comment]
@SRCaesar zu 21 Uhr angepasst
