### ISSUE TITLE
[Wunsch] Genehmigter schwarzer Puma einstellen

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#185]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Ein schwarzen Puma bei meinem 2. Char einstellen der erstellt wurde. Er wurde genemigt und jetzt müsste man den 2. Char noch einstellen als Puma. 

**Beschreibe die gewünschte Lösung**
Ein schwarzen Puma bei meinem 2. Char einstellen der erstellt wurde. 

**Gibt es Alternativen die bereits überlegt wurden und warum reichen die nicht?**
Nein

**Comment by MrBurns010** [comment]
Ohne Infos zum Zweitchar wird hier nix passieren ....

streamid? Name? irgendwas brauchen wir

**Comment by SRCaesar** [comment]
Tohon Puma heißt der Zweitchar.

https://gyazo.com/e0aca9663291586c1f8fcb70f34c4d47

**Comment by MrBurns010** [comment]
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/0f157bd7-26cc-4b2b-96a9-d9420059d2af)

**Comment by SRCaesar** [comment]
https://gyazo.com/422dbe55f1558bbbd1b24e4d23ddfd33

@MrBurns010 Ist noch ein Mensch. ^^
