### ISSUE TITLE
[BUG]Indianerbetten

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#186]
**Beschreibe den Fehler**
Das Bett kann man im Inventar nicht auswählen und somit nicht aufbauen

**Nachstellbar | Auschließen Client Problemen**
JA
Falls Ja, folgende Schritte:
1. Öffne dein Inventar 
2. Versuche Indianerbett aufzustellen

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Indianer bett lässt sich aufstellen 

**Screenshots/Videos**
https://medal.tv/games/red-dead-2/clips/i9G8orgKNnhNSSix2/d1337Uk3AxF1?invite=cr-MSxTS0csNDg1MDAzMDcs

**Kontaktdaten Melder**
 - IC-Name: Wesley Moon
 - Discord: gamerworld92 (701472126959353968)

**Comment by MrBurns010** [comment]
That clip does not exist.

Somit keine Fehlerbehebung möglich
