### ISSUE TITLE
[BUG]Mine An/-Verkauf

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#187]
**Beschreibe den Fehler**
Dort steht kaufen statt verkaufen siehe Bild und die Anzeige wieviel man bei sich trägt funktioniert nicht.

**Nachstellbar | Auschließen Client Problemen**
JA

Falls Ja, folgende Schritte:
1. Gehe zum Minenankauf
2. Schaue ob es angezeigt wird 

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Es wird angezeigt wieviel man im Inventar hat und es steht dort Verkaufen statt kaufen.

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1255500045298700403/1255905601070825682/image.png?ex=667f7d7c&is=667e2bfc&hm=ba984679cf5defabfa7104948ffaf986a66f9947c1e80a13fc81c6ff0237aae6&

https://cdn.discordapp.com/attachments/1255500045298700403/1255905945121198141/20240627172057_1.jpg?ex=667f7dce&is=667e2c4e&hm=ee6fdd84676e58ebf982a2d3e706cddadb038fd807fa034414c86689cafffdca&

**Kontaktdaten Melder**
 - IC-Name: Jesse Eastwick
 - Discord: spitfire9833

**Comment by Twackerino** [comment]
Bilder nicht vorhanden.

**Comment by MrBurns010** [comment]
@SRCaesar 

Wenn hier keine Rückmeldung mehr erfolgt schließen wir ....

**Comment by SRCaesar** [comment]
Hab da wohl allgemein Probleme mit den Bildern... wisst ihr woran das liegen könnte? Das ich das bessern kann :)

**Comment by MrBurns010** [comment]
Keine Links zu Discord. Rechte Maustaste auf das Bild, kopieren, und dann hier ins Textfeld STRG+V. Dann lädst du das Bild direkt hier hoch. @SRCaesar

**Comment by SRCaesar** [comment]
Danke dir

**Comment by nickbrick03** [comment]
Hier wäre Pan wahrscheinlich sinnvoller als ich, da sie bereits an tp_stores gewerkelt hatte

**Comment by MrBurns010** [comment]
ich dachte du warst dran :) sry

**Comment by nickbrick03** [comment]
> ich dachte du warst dran :) sry

`tp_player_stores` bin ich dran.
`tp_stores` sind Twacker und Pan

**Comment by Twackerino** [comment]
Auch bereits behoben
