### ISSUE TITLE
[Wunsch] Kräutersammler Rezept angleichen (Natives)

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#189]
Es geht darum, dass die Natives 2 Knochenmehl und 1 Scheißhaufen brauchen um 5 Dünger herzustellen. Meines Wissens nach brauchen die Siedler 1 Knochenmehl und 1 Scheißhaufen für 5 Dünger. 

**Beschreibe die gewünschte Lösung**
Bitte Rezept von den Natives auch auf 1 Scheißhaufen und 1 Knochenmehl setzen, denke die Zusammensetzung sollte sich ja nicht ändern für 5 Dünger.

**Comment by Xuess22** [comment]
@SRCaesar zu 21 Uhr angepasst
