### ISSUE TITLE
[BUG] Bockfell statt Bisonfell

### ISSUE THREAD

**Issue by Elite969** [Sundown-Rising/sundown-rising-issues#190]
**Beschreibe den Fehler**
"Hallo!

Bei dem Native Jagtauftrag für den Bison bekommt man ein Bockfell raus.
Denke mal das ist nicht gewollt.

Wäre es möglich dieses umzutauschen in ein Bisonfell, solange es nicht gefixt ist?

LG, Kenai."

**Nachstellbar | Auschließen Client Problemen**
JA/NEIN

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis? 
Drop Bisonfell 

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.

**Kontaktdaten Melder**
 - IC-Name: Kenai Comanche
 - Discord: 282905517318471681

**Sonstiges**

**Comment by Xuess22** [comment]
@Elite969 es gibt Legendäre Bisonhaut und und Legendäre Payata-Bisonhaut. Allerdings ist im Skript ein Reward System drin. Heißt, er muss den Auftrag öfters machen, dann bekommt er auch irgendwann Bisonfell.

Gruß!
