### ISSUE TITLE
Wetter einstellbar ?

### ISSUE THREAD

**Issue by Relegatos** [Sundown-Rising/sundown-rising-issues#192]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Eine klare Beschreibung des Problems. Bspw. Die Spieler sind frustiert wenn die Waffen aus dem Inventar verschwinden.

**Beschreibe die gewünschte Lösung**
Eine klare und verständliche Beschreibung der gewünschten Lösung.

**Gibt es Alternativen die bereits überlegt wurden und warum reichen die nicht?**
Welche Alternativen wurden bereits überlegt.

**Sonstiges**
Alles andere Hilfreiche

**Comment by Xuess22** [comment]
Da die Anfrage 2x da ist, schließe ich ein Ticket @Relegatos
