### ISSUE TITLE
Wetter einstellbar ?

### ISSUE THREAD

**Issue by Relegatos** [Sundown-Rising/sundown-rising-issues#193]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Eine klare Beschreibung des Problems. Bspw. Die Spieler sind frustiert wenn die Waffen aus dem Inventar verschwinden.
Ist es möglich das bestehende Wetterskript so einzustellen das es etwas weniger Regnet und das die Lautstärke bei Gewitter etwas runter gedreht werden könnte ?

Diese Anfrage ist Com Anfrage 
https://discord.com/channels/1123352191751704606/1253750154771697735

Gruß Rele

**Comment by Twackerino** [comment]
Können die Spieler selbst. Ist nichts von uns

**Comment by Relegatos** [comment]
wie kann ich den IC einstellen das es weniger Regnet ??

**Comment by Twackerino** [comment]
Die Lautstärke ist clientside
