### ISSUE TITLE
[BUG] Telegramm Funktioniert nicht 

### ISSUE THREAD

**Issue by SR-General** [Sundown-Rising/sundown-rising-issues#194]
Die Telegramm NR von dem Gewerbe  Jack Winchester / Black Diamond Saint Denis funktioniert nicht. Trotz der versuche ihn welche zu schicken hat es nicht geklappt er erhält nix er war deswegen im support und bambam hat auch versucht ihn ein Telegramm zu senden wo auch nix ankommt.

Daher meine bitte könntet ihr euch mal angucken warum bei dem jungen Mann nix ankommt

 - IC-Name: Jack Winchester
 - Discord: 262597836384894976

**Comment by Twackerino** [comment]
Was gibt der denn ein?

**Comment by SR-General** [comment]
Black Diamond Saint Denis

**Comment by Twackerino** [comment]
Ja.... das ist nicht die richtige TNR. Die richtige kann er notfalls noch beim Gewerbeamt nachfragen
