### ISSUE TITLE
[Frage]Pumpe versetzen Rhodes Ranch

### ISSUE THREAD

**Issue by Elite969** [Sundown-Rising/sundown-rising-issues#195]
"Hallöchen, wir haben auf der Rhodes Ranch das Problem, dass da eine Wasserpumpe steht mit Beschriftung. Direkt neben der Veranda."
Spieler: Kate Blackwood 530897294443151390
![Bild_2024-06-28_212406719](https://github.com/Sundown-Rising/sundown-rising-issues/assets/173967457/671bc6d7-1e76-41a6-8023-fabccfe9be42)

**Comment by MrBurns010** [comment]
Ja und nun?

**Comment by Twackerino** [comment]
> Ja und nun? Brauchen da schon ein paar Infos. Ganz weg oder wo soll die hin?

Soweit ich im Ticket gelesen habe wollen die die beschriftung weg. @MrBurns010

**Comment by Elite969** [comment]
Ich kläre das noch mal ab.

**Comment by MrBurns010** [comment]
> Soweit ich im Ticket gelesen habe wollen die die beschriftung weg. @MrBurns010

Beschriftung muss bestehen bleiben damit die Pumpen unterschieden werden können. Welche kommt vom Script, welche von BCC @Twackerino

**Comment by Elite969** [comment]
Nach Rücksprache mit der Dame, kann die Pumpe versetzt werden. Neuer Standort: Hinter dem Haus. Es geht nur darum, dass die Schrift nicht mehr stört sobald jemand dort sitzt...

**Comment by Xuess22** [comment]
@Elite969 bitte der Dame sagen sie soll einmal /coords 3 am gewünschten Standort via T-Befehl ausführen, sobald die Coords da sind kann ich die Pumpe versetzen.

**Comment by Elite969** [comment]
<img width="691" alt="Screenshot_8" src="https://github.com/Sundown-Rising/sundown-rising-issues/assets/173967457/79bbb05a-8605-4e9e-995e-e9e45edb6840">
@Xuess22 
x=1378.54 y=-881.26 z=68.32 h=75.92

**Comment by Elite969** [comment]
@Xuess22 wie ist der Stand?

**Comment by Xuess22** [comment]
@Elite969 ist mit den Pflanzen zu 16 Uhr versetzt
