### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lenemortis** [Sundown-Rising/sundown-rising-issues#196]
**Beschreibe den Fehler**
Der Underground-Ärzte können keine betroffene Spieler mit Retrovium (Adrenalin Spritze) wieder hochholen.
Der/die betroffenen sind leider zu Spielrestart gezwungen.

**Nachstellbar | Ausschließen Client Problemen**
JA
Falls Ja, folgende Schritte:
1. Spieler liegt am Boden
2. Nimmt als Medic die Spritze
3. Spieler wird wiederbelebt
4. Funktioniert nicht und es muss ein relog gemacht werden

**Erwartetes Verhalten**
Spritzen wieder so funktionsfähig machen, dass der Spieler nach der Spritze wieder steht

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/iaycUNR4plsm7GAMI/d1337fTVKlPD?invite=cr-MSxqRWIsMjAyMjc2NjQ5LA

**Kontaktdaten Melder**
 - IC-Name: Elijah Clark
 - Discord: 424919721301901312

**Comment by Lenemortis** [comment]
Hat sich erledigt, bitte um Nachsicht....
Es konnte gelöst werden.

Liebe Grüße

**Comment by Twackerino** [comment]
Hätte mich tbh auch gewundert wenn nur die nicht gehen. Alle Reviveitems haben die gleiche Kernlogik
