### ISSUE TITLE
[BUG] Kleidung verliert farben, wenn man als Frau eine Schleife anzieht.

### ISSUE THREAD

**Issue by DevGonzi** [Sundown-Rising/sundown-rising-issues#197]
**Beschreibe den Fehler**
Wenn man sich eine schleife holt ist alles an kleidung ungefärbt was man gekauft hat und man muss alles noch mal färben und kaufen

**Nachstellbar | Auschließen Client Problemen**
JA
Wurden Client-Fehler welche durch bspw. den Cache ausgelöst wurden ausgeschlossen 
JA

Falls Ja, folgende Schritte:
1. Hab einen Frauenchar
2. Geh in den Laden wo man Schleifen kaufen kann
3. Kauf ne schleife
4. Char Reload 
5. FEHLER -> Alle Kleidung ungefärbt

**Erwartetes Verhalten**
Kleidung sollte so bleiben wie sie ist

**Screenshots/Videos**
Clip von Pony: https://www.youtube.com/watch?v=J2sESESX-GY

**Kontaktdaten Melder**
 - IC-Name: Jolyne Jenkins
 - Discord: jelly.nachtfalter

**Comment by MrBurns010** [comment]
an Entwickler weitergeleitet. Fehler konnte reproduziert werden
