### ISSUE TITLE
[BUG] Ärzte-Shops fehlende Mediziner Bücher / St.Denis ist nun eine Apotheke statt Ärzte-Shops

### ISSUE THREAD

**Issue by Relegatos** [Sundown-Rising/sundown-rising-issues#199]
**Beschreibe den Fehler**
Eine klare Fehler beschreibung.
In den Ärzte-Shops in Valentine und Armadillo kann man keine "Mediziner Buch" mehr kaufen und in St.Denis ist nun eine Apotheke an statt eines Ärzte-Shops .

Musste "Mediziner Buch" über Admintool vergeben.

Ich möchte euch bitten das wieder so einzustellen das wir in Valentine und Armadillo wieder dieses Buch kaufen können und das in St.Denis aus der Apotheke wieder ein Ärzte-Shop wird.

Danke , gruß Rele

**Comment by MrBurns010** [comment]
Überschrift korrigiert

**Comment by Twackerino** [comment]
Habe durch schellsuche entdeckt, die dinger sind in der Uni und in einem für medics gelockten shop.

Absicht oder nicht muss am besten mal @Xuess22 sagen, die sollte da vermutlich mehr wissen

**Comment by Xuess22** [comment]
Also ich weiß davon nix, aber @Relegatos , seit wann besteht denn dieses Problem? Und was bedeutet, in SD ist auf einmal eine Apotheke?
Eine genauere Ausführung wäre wichtig.

**Comment by Relegatos** [comment]
in SD war immer auch ein Medic-Shop bei dem NPC der da steht , dort ist nun eine Apotheke siehe Bild via Discord .
Das mit den Büchern wurde mir gestern im Voice-Support mitgeteilt und ich habe es IC geprüft und dabei ist mit aufgefallen das in SD nun eine NPC Apotheke ist .

**Comment by Relegatos** [comment]
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/171220210/e6051af7-4d86-417d-ab2d-7e5005c8a2cd)
----------------------------------------------------
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/171220210/d81f0d82-055f-4f2a-b74b-103e49d896de)

**Comment by Relegatos** [comment]
Bild 1 : St.Denis 
Bild 2 : Valentine
