### ISSUE TITLE
[BUG] Tierfelle Despawnen

### ISSUE THREAD

**Issue by Twackerino** [Sundown-Rising/sundown-rising-issues#2]
**Beschreibe den Fehler**
Tierfelle despawnen nach dem Häuten aus der Hand.

**Nachstellbar**
Manchmal, vorallem main
Falls Ja, folgende Schritte:
1. Töte ein Tier
2. Häute es
3. Warte 3 Sekunden mit dem Fell in der Hand.
4. (FEHLER) Es verschwindet

**Erwartetes Verhalten**
Fell bleibt in der Hand

**Screenshots/Videos**
https://youtu.be/9CKaZIlzMSM

**Kontaktdaten Melder**
 - IC-Name: Robert Blue
 - Discord: Bluecher1967 - 434113531307229184

**Comment by Twackerino** [comment]
Folgende Problematik.

Despawn tritt nicht immer auf. Zeitgleich despawnt es bei einigen bei anderen nicht. Fehler vorallem im Live betrieb testbar. Da bereits Skript restarts eine veränderung der Problematik hervorrufen

**Comment by MrBurns010** [comment]
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/e6116574-89b1-474f-b61d-540386516604)

**Comment by Twackerino** [comment]
Sundown-Rising/sundown-rising-issues#63
Erneute Meldung

**Comment by MrBurns010** [comment]
Hunting Update hat keinen Erfolg gebracht.

**Comment by Twackerino** [comment]
Neuer Lösungsversuch in RICX.
@MrBurns010 wer übernimmt einstellen?

**Comment by MrBurns010** [comment]
> Neuer Lösungsversuch in RICX. @MrBurns010 wer übernimmt einstellen?

@Xuess22 ist mit den Jungs von der Wirtschaft bereits dran :-) Sobald Preise und Items fertig sind, wird es auf den Main gebracht und direkt im Livebetrieb getestet. Mein Test auf dem Dev war auch erfolgreich. Jedoch fehlen hier natürlich die Spieler. Aber die neue Funktion hat perfekt funktioniert. @Twackerino

**Comment by Twackerino** [comment]
Nach Änderungen und Anpassungen am Jagdscript nicht mehr relevant
