### ISSUE TITLE
[BUG] Kisten Verschwunden

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#201]
**Beschreibe den Fehler**
Kisten sind verschwunden. Von vielen Spielern erfasst worden

**Kontaktdaten Melder**
 - IC-Name: Suki Blackwood
 - Discord: 668504186001948712

**Comment by joybtw** [comment]
Sollte nach 12:00 Uhr wieder gehen, das Issue schließe ich, wenn ich es getestet habe 👍
