### ISSUE TITLE
[BUG] Gold Schürffen Script

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#202]
**Beschreibe den Fehler**
"Hallo. Ich schürfe Gold an verschiedenen Stellen und habe über den Tag verteilt noch keinen Nugget gefunden. Ich bekomme zwischendurch die Meldung das ich nichts gefunden habe und mehr Meldungen bekomme ich nicht."

Nach dem 2ten Versuch unterbicht das Minigame und der Spieler bekommt keine weiteren Meldungen.
Clip vor Restart: https://medal.tv/de/games/red-dead-2/clips/ibJEerBmuRnOpnRn6/d13377YpPQ7a?invite=cr-MSxza1gsNDI5NzY1Njgs

Hab ihn gebitten nach dem Restart noch ein Versuch zu starten.
Clip nach 21:00 Uhr Restart: https://medal.tv/de/games/red-dead-2/clips/ibKdIS47UhmrdgILw/d1337C8JRdan?invite=cr-MSxkNVMsNDI5NzY1Njgs

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Evt. wo kene Meldung erscheint, müsste er im normal fall ein Gold Nugget bekommen

**Screenshots/Videos**
1. Clip: https://medal.tv/de/games/red-dead-2/clips/ibJEerBmuRnOpnRn6/d13377YpPQ7a?invite=cr-MSxza1gsNDI5NzY1Njgs
2. Clip: https://medal.tv/de/games/red-dead-2/clips/ibKdIS47UhmrdgILw/d1337C8JRdan?invite=cr-MSxkNVMsNDI5NzY1Njgs

Der Spieler hat noch eine Map Zeichnung zugesendet, wo er alles versucht hatte Gold zuschürfen
![Screenshot_74](https://github.com/Sundown-Rising/sundown-rising-issues/assets/68290420/7fbf0514-4d2c-4b7b-9466-12d16bf969a9)

**Kontaktdaten Melder**
 - IC-Name: Walt Murfree
 - Discord: 199958553727860736

**Comment by Xuess22** [comment]
@aytoon Fehler kann NICHT nachgestellt werden. Peterchen & ich haben in 5 Minuten an zwei Flüssen jeweils 5 Nuggets gefunden. Bitte Spieler informieren. Ansonsten dem Spieler anweisen, einmal den Cache zu leeren.
