### ISSUE TITLE
Ballon [BUG]

### ISSUE THREAD

**Issue by xxLiiisaaaxx** [Sundown-Rising/sundown-rising-issues#203]
**Beschreibe den Fehler**
Ballon war gekauft und wurde eingeparkt, dennoch musste strafe bezahlt werden.

**Nachstellbar | Ausschließen Client Problemen**
JA
Falls Ja, folgende Schritte:
1. Kaufe einen Ballon
2. parke den Ballon aus 
3. Park ihn wieder ein 
4. (FEHLER) 50$ Strafe wegen "falsch einparken"

**Erwartetes Verhalten**
keine  Strafzahlung fällig

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/iauoCIzjCA6HIx8mM/d1337W8r31mw?invite=cr-MSw1TmgsMjA1NDY3ODgxLA

**Kontaktdaten Melder**
 - IC-Name: Abraham Addams 
 - Discord: 238320077374619649

**Comment by SpaceboyNr2** [comment]
Habe es vor 1-2 Tagen auf dem Dev Server probiert und da läuft alles.

**Comment by xxLiiisaaaxx** [comment]
Ich kann es heute Abend gerne einmal auf dem Main testen und hier eine Meldung geben mit Clip sollte es nicht klappen.

**Comment by xxLiiisaaaxx** [comment]
Ich habs eben auf dem Main getestet.
Es funktioniert einwandfrei.
Leider ist warum auch immer mein Clip weg.
Waren aber mehrere Leute anwesend unteranderem Elite & Marcel und noch paar andere.

**Comment by SpaceboyNr2** [comment]
Perfekt, ich schließe dann hier das anliegen.
