### ISSUE TITLE
[BUG] Native Heiler/Schamanen können keine Heiler sachen benutzen/keine Wirkung

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#206]
**Beschreibe den Fehler**
Die Spielerin hatte In-game versucht Kräuterverbände, Kräuterwasser an anderen Spielern anzuwenden und haben keine Wirkung bzw. sie kann es nicht mal anlegen.

**Auflistung von nicht funktionierenden sachen:**
- Honig Verband
- Kräuterverband
- Kräuterwasser
- Aktiv Native Salbe
- Aloe Vera Verband

**Spieler Ticket:**
```
Ich bin Heilerin und habe derzeit das Problem das einige sachen nicht zu benutzen sind oder nciht wirklich helfen.
Kräuter wasser: kann weder schamane noch wer anders benutzen
Honig oder Kräuterverband: haben keine wirkung, weder herz noch blitz
Salben lassen sich nicht benutzen, weder von Schamane noch von anderen.
Es wäre schön wenn wir die Sachen wieder benutzen könnten und sie auch wieder heilung oder Ausdauer bringen.
```

**Nachstellbar | Auschließen Client Problemen**
JA

**Erwartetes Verhalten**
Es wäre schön wenn man die Sachen wieder benutzen kann und sie auch wieder heilen oder Ausdauer bringen.

**Screenshots/Videos**
F8-Screen: 
![20240704223541_1](https://github.com/Sundown-Rising/sundown-rising-issues/assets/68290420/61347c6f-73e3-4c0d-b510-ab37c4ab45f7)

**Kontaktdaten Melder**
 - IC-Name: Namid Maska
 - Discord: 713814894537080894
 - Steam: steam:11000013c31ad55
 - Char ID: 2401
 - Rang: 1 native_schaman

**Sonstiges**
Toyatuku tue hat allerdings auch das Problem. Beide Rang 1 Schamane/Heiler

**Comment by aytoon** [comment]
**Update der Sachen, die nicht Funktionieren:**
+ Kräuterwasser im glas

**Comment by Twackerino** [comment]
Funktionierend:
Honig Verband
Aloe Vera Verband
Kräuterverband
Kräuterwasser

Nicht funktionierend:
Aktiv Native Salbe

Das eine fehlenede wurde behoben.
