### ISSUE TITLE
[BUG] Direkter Buff nach Drogenkonsum

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#208]
**Beschreibe den Fehler**
Wenn man beispielsweise einen Joint konsumiert bekommt man direkt den Buff auf Leben/Ausdauer.
Es gibt keinerlei Effekt oder Animation zur Konsumierung.

**Nachstellbar
Ja.
1. Konsumiere die Droge
2. Bekomme direkt den Buff

**Erwartetes Verhalten**
https://medal.tv/de/games/red-dead-2/clips/i5sSqX3eSTbDQSqTN/d13371XvwjqT?invite=cr-MSxFbXksMTkxMjM3Mzc4LA

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/ibh9Kg7w8aKo80Ka6/AhYoniNikfb3?invite=cr-MSxGSUIsMjAyMjc2NjQ5LA

**Kontaktdaten Melder**
 - IC-Name: Elijah Clark
 - Discord: doggy1509

**Comment by Xuess22** [comment]
@SRIcely um welche Drogen handelt es sich da? Ich kann aus den beiden Clips nicht alles erschließen. Koka Tabak hab ich gesehen, aber Marihuana funktionierte doch?

**Comment by SRIcely** [comment]
Ich würde danach auf den Dev gehen und die ganzen Joints durchprobieren. 
Gibt es noch andere Dinge ausser dem Koka Tabak die keine Joints sind?

**Comment by Xuess22** [comment]
@SRIcely es gibt mehrere Drogen, aus dem Text kann ich nicht erschließen um welche Drogen es sich handelt.

**Comment by SRIcely** [comment]
@Xuess22 In seinem Clip hat er nur Koka Tabak, Kalka Kush und Purple Kush getestet. Die anderen kann ich gerne testen.

**Comment by SRIcely** [comment]
Ich habe mal alles an Drogen getestet was ich auf dem Dev-Server gefunden habe.
Einige Sachen gab es doppelt deswegen habe ich die Itembeschreibung mit hinzugefügt @Xuess22
Buffs wie Leben oder Ausdauer habe ich auf dem Dev nicht gesehen.
Da in dem Ticket zu sehen ist dass Items zwar einen Buff haben aber keine Animation/Effekt müsste man das mal anschauen.

Item                                 Itembeschreibung           Effekt?
Purple Kush 		        Uiiii ich kann fliegen 	Animation+Effekt vorhanden
Purple Kush 		        Nice Item		                Animation+Effekt vorhanden
Veredelter Purple Kush 	Nice Item		                Animation+Effekt vorhanden
Kalka Kush 		        Ein Joint	                 	Animation+Effekt vorhanden
Kalka Kush 		        Nice Item		                Animation+Effekt vorhanden
Veredelter Kalka Kush 	Nice Item	                 	Animation+Effekt vorhanden
Opium 			        Nice Item	                	Animation+Effekt vorhanden
Opium 			        Nice Item	                   	Animation+Effekt vorhanden
Veredelter Opium 	        Nice Item		                Animation+Effekt vorhanden
Orange Haze 		        Nice Item		                Keine Animation, Kein Effekt
Lemon Haze 		        Nice Item		                Keine Animation, Kein Effekt
Marihuana 		        Zur Entspannung		Animation+Effekt vorhanden	
Opium Zig		        Nice Item		                Animation+Effekt vorhanden
Kokain		        	Weißes Pulver		        Animation+Effekt vorhanden

**Comment by fraupan** [comment]
Absprache mit Walrus: 
Er ist übers Wochenende nicht da, wird verschoben bis danach
