### ISSUE TITLE
[BUG] Shopraub nicht möglich

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#209]
**Beschreibe den Fehler**
Wenn man versucht einen Generalstore auszurauben bekommt man die Fehlermeldung: 
Du solltest vielleicht ein Halstuch tragen. 
Egal ob der Spieler eines trägt oder nicht.

**Erwartetes Verhalten**
Der Spieler zieht sich sein Halstuch auf und kann dann den Generalstore ausrauben.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/id0waWQnTzoKgUyIQ/e0UmzsAw5TyP?invite=cr-MSxrM0ssMjAwOTkyNjU0LA

**Kontaktdaten Melder**
 - IC-Name: John Watson
 - Discord: impileebjorn

**Comment by SRIcely** [comment]
Hier ein neuer Clip @SpaceboyNr2 

https://medal.tv/de?contentId=if1jpRYhJsMSmC8Hy&invite=cr-MSxkZ2csMjAwOTkyNjU0LA&spok=d13371qpTvxC

**Comment by Xuess22** [comment]
@SRIcely zu 16 Uhr behoben. Crime kann nun selbst entscheiden ob sie Bandana tragen möchten oder nicht.
