### ISSUE TITLE
[BUG]Muskat/Valeriensamen nicht kaufbar

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#210]
**Beschreibe den Fehler**
Wenn ein Farmer Valerien oder Muskatsamen beim Samenmarkt kaufen möchte bekommt er die Fehlermeldung:
Du kannst nichts mehr tragen.

**Nachstellbar 
Ja.
1. Gehe zum Farmermarkt und öffne das Menü
2. Kaufe Valeria/Muskatsamen

**Erwartetes Verhalten**
Ich bekomme die jeweiligen Samen ins Inventar

**Screenshots/Videos**
https://www.youtube.com/watch?v=ZWGnUJF5wL4
https://medal.tv/de/games/red-dead-2/clips/idBNRpKu4BluUrzEO/d1337r4kb8qo?invite=cr-MSxzVlEsMTkxMjM3Mzc4LA

**Kontaktdaten Melder**
 - IC-Name: John Stone
 - Discord: gothicteufel

**Comment by fraupan** [comment]
Die Items für Muskat Samen (mace_seed) und Valerien Samen (valerian_seed) waren nicht in der Datenbank eingepflegt.
Ab dem 12 Uhr Restart ist das Problem gefixt.
