### ISSUE TITLE
Zu hoher Ping

### ISSUE THREAD

**Issue by SRRanaka** [Sundown-Rising/sundown-rising-issues#212]
Und zwar hat ein Spieler das Problem das er bei einem zu hohen Ping gekickt wird. Er fragt an ob man ihm davon befreien kann. 
Er spielt wohl über einen Simkartenrouter.

Bei Rückfragen hier das Ticket:  https://discord.com/channels/1123352191751704606/1259541098444099624

Ticket bleibt offen bis zur Rückmeldung

**Comment by Twackerino** [comment]
Schieb das Ticket mal zum Highteam ^^
