### ISSUE TITLE
[BUG] Lägendärer Jagd Auftrag - geht nicht weiter

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#214]
**Beschreibe den Fehler**
Wenn man in Wapiti den NPC anspricht für Lägendären Jagd Aufträgen und dann zum Punkt hinreitet wo man die WIlderer töten muss, despawnen/spawnen die Wilderer NPCs nicht und wird somit der Auftrag nicht weitergeführt. Mit Glück spawnt da nur 1-2 NPCs aber dennoch kann man den Auftrag nicht weiter machen.

**Nachstellbar | Auschließen Client Problemen**
JA

**Verlauf der Ausführung:**
1. Geh zum NPC in Wapiti (Jagd Aufträge)
2. Nimm Auftrag an (Bison)
3. Reite zum Punkt wo man den Bären suchen muss
4. Reite zum Wald gegenüber
5. (FEHLER) Töte Wilderer, die spawnen

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
- Das die NPCs spawnen und man nach dem Töten der NPCs den Auftrag weiter machen kann.

**Screenshots/Videos**
Clip 1: https://medal.tv/de/games/red-dead-2/clips/idQWWAttNaOj0aSJz/d1337krJrGXO?invite=cr-MSxwMEosMjI3ODIwMjk0LA
Clip 2: https://medal.tv/de/games/red-dead-2/clips/ie8NJqCoGd7K1ff6R/d13370Z9Djjm?invite=cr-MSxEZTUsMjI3ODIwMjk0LA

**Kontaktdaten Melder**
 - IC-Name: Noya Ahyoka
 - Discord: 404681425913249792
 - Char ID: 6215
 - Steam: steam:110000134d32bc9
 - In-Game Job: native_collector / 1
 - TX Name: Cayris

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.
/

**Comment by Twackerino** [comment]
@MrBurns010 muss bitte an Xakra ggf. Da Verschlüsselt.
