### ISSUE TITLE
Hufeisen Rezeptänderung

### ISSUE THREAD

**Issue by Helmard** [Sundown-Rising/sundown-rising-issues#216]
Im Sinne der Logik und der Attraktivität des Berufes bitte das Rezept für die Hufeisenherstellung wie folgt abändern : 

Neues Rezept Pro Hufeisen:

Eisenbarren 3
Kupferbarren 2
Nägel 16

https://discord.com/channels/1123352191751704606/1252183765854457936

**Comment by Xuess22** [comment]
zu 16 Uhr geändert @Helmard
