### ISSUE TITLE
Nutztierpreisanpassung

### ISSUE THREAD

**Issue by Helmard** [Sundown-Rising/sundown-rising-issues#217]
Bitte den VK Preis der Ziegen an den der Schweine angleichen.

VK Preis ist jeweils bei Zufriedenheit 200.

Schweine EK 150$ VK 275$
Ziegen EK 150$ **_VK 75$_**

https://discord.com/channels/1123352191751704606/1258347412305743892

**Comment by Twackerino** [comment]
![grafik](https://github.com/Sundown-Rising/sundown-rising-issues/assets/58168452/b3868a75-7717-40c4-a625-98d8519a6091)
![grafik](https://github.com/Sundown-Rising/sundown-rising-issues/assets/58168452/b044bc90-cf38-4525-bc0e-1dc456a7667d)
Öhm... ja also die sind mit max 300 hinterlegt

**Comment by Twackerino** [comment]
Würde mal vermuten ihr ist da ne ziege gestorben auf dem weg

**Comment by Xuess22** [comment]
Hat sich geklärt, wird geschlossen.
