### ISSUE TITLE
[BUG] Sendet man ein Notizbuch via Telegramm ist der Inhalt des Buches weg

### ISSUE THREAD

**Issue by DevGonzi** [Sundown-Rising/sundown-rising-issues#218]
**Beschreibe den Fehler**
Sendet man ein Notizbuch via Telegramm ist der Inhalt des Buches weg

**Nachstellbar | Auschließen Client Problemen**
JA auf LIVE

Falls Ja, folgende Schritte:
1. Schick ein Telegram mit einem Notizbuch mit Text
2. Der Empfänger nimmt es an
3. (FEHLER) Das Buch ist leer

**Erwartetes Verhalten**
Das buch sollte mit inhalt gesendet werden

**Kontaktdaten Melder**
Gonzi

**Comment by DevGonzi** [comment]
Beispiel:
https://discord.com/channels/1124057670157078668/1190261581913800754/1260057014021787698

3 Seiten text weg

**Comment by Twackerino** [comment]
Metadata werden nicht mit gesendet und es ist bisher nicht geplant diese mitzusenden.

**Comment by DevGonzi** [comment]
Kann man Bücher blacklisten zu senden?
