### ISSUE TITLE
Bug Werkzeugmacher Blackwater

### ISSUE THREAD

**Issue by SRRanaka** [Sundown-Rising/sundown-rising-issues#219]
**Beschreibe den Fehler**
Fernglas und verbessertes Fernglas nach Herstellung nicht in der Tasche.

**Nachstellbar | Auschließen Client Problemen**
JA
Cache wurde nach Aussage des Erstellers geleert
Falls Ja, folgende Schritte:
1. Nimmt erforderliche Ressourcen
2. Geht zur Werkbank
3. Bestätigt die Herstellung
4. (FEHLER) Hat hergestellte Items nicht im Inventar

**Erwartetes Verhalten**
Fernglas oder erweitertes Fernglas im Inventar.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/ierqgffQVa3Z6nZ4T/d1337W0Usqqv?invite=cr-MSxmWlosMTE5MzgyNjQyLA

Timestemp:

ab 0:39 min Start Herstellung Fernglas
ab 1:00 min F8 Konsole
ab 1:00 min Fertigstellung Fernglas
ab 2:46 min Start Herstellung verbessertes Fernglas
ab 3:07 min Fertigstellung verbessertes Fernglas
ab 3:07 min F8 Konsole

**Kontaktdaten Melder**
 - IC-Name: Fernando Tuga
 - Discord: zorgar.

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
Sollte mit dem 16 Update behoben sein.
