### ISSUE TITLE
Underground-Medic[Wunsch] 

### ISSUE THREAD

**Issue by Puma-TV** [Sundown-Rising/sundown-rising-issues#222]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Underground Medic System

**Beschreibe die gewünschte Lösung**
Die Möglichkeit die Krähe des Underground Medics auch bei Verletzung los zu schicken, 
damit der Underground Medic geheim bleibt.

**Gibt es Alternativen die bereits überlegt wurden und warum reichen die nicht?**
-

**Sonstiges**
Rückfragen dazu an SR | Puma

**Comment by Twackerino** [comment]
Wünsche an Skripts die über CM´s laufen sind hoffentlich mit denen abgesprochen.

Ansonsten, es wird keine Sonderlösungen im Medicscript geben, gerade da der Code bereits mit den vorhanden Codeblöcken nur schwer zur lesen und warten ist.
