### ISSUE TITLE
Schlösser Dakota-River-Farm Farmhaus[Frage]

### ISSUE THREAD

**Issue by Puma-TV** [Sundown-Rising/sundown-rising-issues#223]
![Bild_2024-07-10_015606236](https://github.com/Sundown-Rising/sundown-rising-issues/assets/175158813/468731b4-ca4f-4fc4-8b7f-508ea75ecee0)
**Schreib das Anliegen**
Die Schlösser des Farmhaus der Dakota-River-Farm müssen ins Script hinterlegt werden

**Comment by Twackerino** [comment]
Erstens. Keine Frage, sondern eine feststellung.
Zweitens: Vordertür hintertür badezimmer schweinestall?

**Comment by fraupan** [comment]
@Puma-TV Es wäre noch schön zu wissen, WELCHE Türen gesetzt werden sollen.

**Comment by fraupan** [comment]
Leider kam keine Reaktion mehr. Ticket wird geschlossen.
