### ISSUE TITLE
[BUG] Bandenshop werden keine Möbel angezeigt

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#225]
**Beschreibe den Fehler**
Im Bandenshop, in dem Fleischertisch und Kisten zum Verkauf stehen, gibt's keine Möbel mehr, die dritte Kategorie ist leider komplett leer. 

**Nachstellbar | Auschließen Client Problemen**
JA

1. Geh zum Bandenshop (Fleischertisch und Kisten zum Verkauf stehen)
2. Klicke Oben durch, bis zur 3ten Seite
3. (FEHLER) Crime Möbel werden nicht angezeigt (leer)

**Erwartetes Verhalten**
Das Crime Möbel bei den Bandenshop angezeigt werden.

**Screenshots/Videos**
![2024-07-09_16_52_36-Window](https://github.com/Sundown-Rising/sundown-rising-issues/assets/68290420/83af0075-2153-4dc3-bc38-6669024894e6)

**Kontaktdaten Melder**
 - IC-Name: Roderick Rogers
 - Discord: 245978752322895873
 - Char ID: 4792
 - Steam: steam:11000010266d4c4
 - Fraktion: Kupferbanditen

**Comment by MrBurns010** [comment]
Ist korrekt. Es wird keine Möbel mehr über das Bandenscript geben sondern nur noch vom Ausstatter. Das hängt mit dem Update für die Zelte zusammen welches in kürze released wird.
