### ISSUE TITLE
Gemeinschaftsstall Hufschmied Ad [Gewerbe]

### ISSUE THREAD

**Issue by Puma-TV** [Sundown-Rising/sundown-rising-issues#226]
**Welches Gewerbe?**
Hufschmiede Ad

**Problem / Anfrage**
Erstellung eines Gemeinschaftsstall für die Hufschmiede

**Kontakt - Gewerbeamt**
Puma

**Kontakt - Gewerbe**
IC-Name: Ivy Oreally
Discord: 847911065282412614

**Sonstiges**
Mit Sabrina abgesprochen

**Comment by MrBurns010** [comment]
"Mit Sabrina abgesprochen" ist keine Info mit der wir etwas anfangen können

**Comment by Puma-TV** [comment]
Sie hat gesagt da kümmert sich Pan drum!!!

**Comment by fraupan** [comment]
ToDo: Gemeinschaftsstall für Hufschmiede Ad, Hufschmiede Dev

**Comment by fraupan** [comment]
fixed: https://github.com/Sundown-Rising/sundown-rising-private/commit/c72ba3658354756001df7f9bb29160377d3851c5
