### ISSUE TITLE
[BUG] Bild hoch - Keine Funktion

### ISSUE THREAD

**Issue by MrBurns010** [Sundown-Rising/sundown-rising-issues#227]
**Beschreibe den Fehler**
Bild hoch funktioniert nicht korrekt

**Nachstellbar | Auschließen Client Problemen**
JA

**Erwartetes Verhalten**
Bild hoch soll die korrekten Logs posten

**Sonstiges**
@Twackerino im Thema

**Comment by Twackerino** [comment]
![grafik](https://github.com/Sundown-Rising/sundown-rising-issues/assets/58168452/1e327ea1-6be4-4493-8297-5e14b38a75e7)
funktioniert
