### ISSUE TITLE
[BUG] Ranch NPC - Sichtungen funktionieren nicht

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#228]
**Beschreibe den Fehler**
Wenn man zum Sichtung NPC geht, ihn anspricht und versucht eine Pferde Sichtung zu machen. Will er die Sichtung nicht Starten. Die SPielerin hat gemeldet, dass es wohl bei allen Ranchen so ist.

**Nachstellbar | Auschließen Client Problemen**
JA

1. Geh zur Ranch
2. Sprich den Sichtungs NPC an
3. Klicke egal welchen Pferd, den du Sichtigen willst
4. Klicke eine Farb Rasse an
5. (FEHLER) Sichtung beginnt

**Erwartetes Verhalten**
Das wenn man auf den Pferd Klickt und der dazugehörigten Rasse, dass die Sichtung startet

**Screenshots/Videos**
Clip: https://medal.tv/games/red-dead-2/clips/ieQjH5rlRLsATRAql/d1337t1aymmO?invite=cr-MSxVa3QsNTMwMDgzODIs

**Kontaktdaten Melder**
 - IC-Name: Jody Morgan
 - Discord: 747070922938253313
 - Steam: steam:11000010570cf29
 - Char ID: 724
 - TX Name: katib1979
 - IC Job: dakotariverranch / 4

**Comment by Twackerino** [comment]
![grafik](https://github.com/Sundown-Rising/sundown-rising-issues/assets/58168452/fb4a6fdc-6875-4892-a261-032d7b852f43)

**Comment by aytoon** [comment]
F8 Log:
![Screenshot_2024-07-10_212121](https://github.com/Sundown-Rising/sundown-rising-issues/assets/68290420/1bf8f56e-8fda-4afb-bc0d-779d6dfd6aa3)
