### ISSUE TITLE
[Wunsch] Haltbarkeit von Hufeisen

### ISSUE THREAD

**Issue by DevGonzi** [Sundown-Rising/sundown-rising-issues#229]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Bei den CMs einstimmig Beschlossen:
Hufeisen eine Haltbarkeit von 1 Monat geben, wenn die Hufe NICHT regelmäßig ausgekratzt werden. (gehen sie dann Kaputt)
Kratzt man die Hufe regelmäßig aus, muss man sie auch nicht wechseln.

**Beschreibe die gewünschte Lösung**
Hufeisen bekommen wie ein Healthcounter

**Comment by fraupan** [comment]
Wird erst was mit dem neuen Pferde-Script. Daher erstmal als nicht geplant geschlossen.
