### ISSUE TITLE
[Wunsch] Abänderung Drogenpreise

### ISSUE THREAD

**Issue by Twackerino** [Sundown-Rising/sundown-rising-issues#23]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Nein, CM Abstimmung

**Beschreibe die gewünschte Lösung**
https://docs.google.com/document/d/1OJCn8ha0qFY20P9EL1m7EL3gJ-7ZyRpN_YStE_1XaIA/edit?usp=sharing

**Sonstiges**
Eingereicht von Meda

**Comment by MrBurns010** [comment]
Drogenpreise sind an die Städte geknüpft. Man startet in nicht so hochwertigen Städten, wo der Verkaufspreis gering ist und arbeitet sich immer weiter hoch. Dabei steigt auch der Verkaufspreis immer mit.
