### ISSUE TITLE
Frage aus der Community : Ist es möglich "Slap" Emotes einzufügen ?

### ISSUE THREAD

**Issue by Relegatos** [Sundown-Rising/sundown-rising-issues#234]
in den "Vorschlägen" gibt es eine Anfrage ob man "Slap-Emotes" mit einer Extra Kategorie im Emote-Menü einfügen kann ? 

Da wir CM´s darauf keine Antwort geben können , nun diese Frage weiter an euch Devs .

Hier noch der Link zu der Anfrage : 
https://discord.com/channels/1123352191751704606/1257365684480905217

Gruß Rele

**Comment by joybtw** [comment]
Wenn die sich boxen wollen, sollen sie boxen. Braucht man keine Emotes für
