### ISSUE TITLE
Frage aus der Community zwecke Verbände

### ISSUE THREAD

**Issue by Relegatos** [Sundown-Rising/sundown-rising-issues#235]
gefragt wird , ob es möglich ist das man IC angelegte Verbände/Bandagen etc , dann auch als solche Sichtbar sind , so das "mein" Gegenüber sieht das "Ich" verbunden bin ? 

Da wir CM´s darauf keine Antwort haben , ob das Möglich ist , nun diese Frage an euch Devs dazu .

Hier noch der Link zu dieser Anfrage : 
https://discord.com/channels/1123352191751704606/1259985072522793090

Gruß Rele

**Comment by joybtw** [comment]
Soweit ich weiß nicht wirklich

**Comment by joybtw** [comment]
Man könnte aber einen Verletzten Gehstil einbauen, wenn die Person sich verbindet

**Comment by Relegatos** [comment]
soll der dann kommen dieser gehstil ?
