### ISSUE TITLE
(evtl. für Pan)Streichung ein Farbpallette Pferdefell [Frage]

### ISSUE THREAD

**Issue by Puma-TV** [Sundown-Rising/sundown-rising-issues#236]
**Schreib das Anliegen**
Es wurde sich über eine Farbpalette der Pferde besonders beschwert und wir kamen zu dem Entschluss das dieses Fell schon Fail im RP ist und man diese entfernen oder um modellieren sollte. Fell zusehen in Anhang. Vielen Dank für die Bearbeitung
![Pferd1](https://github.com/user-attachments/assets/d5bd8995-96eb-47cb-99f6-8ec0846002ce)
![Pferd2](https://github.com/user-attachments/assets/f5ebbcbf-95fb-4a3b-9a52-65c8b3679d8c)

**Comment by joybtw** [comment]
Einfach den Spieler bitten, es Live im Support um zu konfigurieren.

**Comment by fraupan** [comment]
Ist nicht rausnehmbar, soll wie Joy schon geschrieben hat bitte umgefärbt werden.
