### ISSUE TITLE
[BUG] "Waffen" kann man nun kaufen, allerdings liegen sie nicht im Inventar

### ISSUE THREAD

**Issue by Xuess22** [Sundown-Rising/sundown-rising-issues#237]
**Beschreibe den Fehler**
Eine klare Fehler beschreibung.
 "Waffen" kann man nun kaufen, allerdings liegen sie nicht im Inventar

**Nachstellbar | Ausschließen Client Problemen**
JA
Wurden Client-Fehler welche durch bspw. den Cache ausgelöst wurden ausgeschlossen 

Falls Ja, folgende Schritte:
1. Geh zur Auslage
2. Versuche Fernglas / Fackel zu kaufen
3. Klicke auf Kaufen
4. (FEHLER) Nichts davon im Inventar

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Gekaufte Ware im Inventar

**Screenshots/Videos**
https://discord.com/channels/1123352191751704606/1247288119963947009/1261064909555367987
![image](https://github.com/user-attachments/assets/3f69e214-60c0-447d-ae65-0c19a6f1a4fb)

**Kontaktdaten Melder**
 - IC-Name: Fernando Tuga
 - Discord: 174260677500862464

**Comment by Twackerino** [comment]
behoben
