### ISSUE TITLE
[Wunsch] Marker Überfall ungenauer

### ISSUE THREAD

**Issue by Twackerino** [Sundown-Rising/sundown-rising-issues#24]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Die Marker bei Überfällen sind zu genau.

**Beschreibe die gewünschte Lösung**
Marker ungenauer / Radius wie bspw Pferdesichtungen

**Sonstiges**
Eingereicht von Meda

**Comment by MrBurns010** [comment]
Was bringt es, wenn ein General Store überfallen wird und der Marker die ganze Stadt bedeckt und keiner weiß, wo man hin muss? Es wird ausgespielt, dass ein Passant etwas gesehen hat. Es kommt ja kein Passant mit den Worten "In Valentine passiert was", sondern eher mit "In Valentine wird der GS ausgeraubt".

**Comment by Twackerino** [comment]
Mit den Überfällen waren Drogenvk gemeint

**Comment by Itsjadymady** [comment]
Also mit dem Marker sin d Drogenüberfäle und Illegale Handlungen gemeint, dort wird HAAR GENAU angezeigt wo der Crimler sich befinden, was ich bisschen unfair finde.Viele Lawler gehen dann direkt zu der Position und nehmen die Leute fest. Ein Radius wo sich ca die Leute befinden wäre besser

**Comment by Twackerino** [comment]
Durch Verschlüsselung nicht möglich von Dev einzufügen. Müsste beim Entwickler angefragt werden. @MrBurns010
