### ISSUE TITLE
[BUG] Rucksäcke verschwinden nicht nach abnahme

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#240]
**Beschreibe den Fehler**
Wenn man jetzt die Rucksäcke anzieht und wieder ablegt, sieht man sie immer noch auf dem Rücken obwohl sie weg sein müssten.
Je mehr man Rucksäcke man anzieht und abnimmt, stacken die sich und nach einem relog verschwinden die erst vom Rücken.

**Nachstellbar | Auschließen Client Problemen**
JA

1. Öffne den Inventar ("i")
2. Doppelklick auf einen Rucksack (anziehen)
3. Wieder doppelklick auf Rucksack (abnehmen)
4. (FEHLER) Rucksack verschwindet nicht. Je mehr Rucksäcke man anzieht und abnimmt, desto mehr stacken die sich.

**Erwartetes Verhalten**
Das bei abnahme von einem Rucksack, dass er vom Rücken verschwindet.

**Screenshots/Videos**
![PDhIialmQNGUqKs6sKLkew](https://github.com/user-attachments/assets/8cbbf407-4e0b-49f6-8280-c371cc7314df)

**Kontaktdaten Melder**
 - IC-Name: Kleine Katze
 - Discord: 288368895293652992
 - Char ID: 4933
 - Steam: steam:11000013631d26c
 - TX Name: Kleine Katze

**Comment by SRIcely** [comment]
Ich habe hier noch einen weiteren Melder.
Clip:
https://medal.tv/de?contentId=ig6th7SUmRaRDVKWG&invite=cr-MSxzdk8sMjQ0ODMxMDUzLA&spok=d1337yBYJcX5

Melder:
  IC-Name: Kowal Henry
  Discord: crisdaii
