### ISSUE TITLE
[bug]Tiersehne

### ISSUE THREAD

**Issue by SDBuechse** [Sundown-Rising/sundown-rising-issues#241]
**Beschreibe den Fehler**

Zum Herstellen eines Verbesserten Bogen wir eine Tiersehne verlangt, diese ist aber nicht zu bekommen.
Der Melder hat schon auf mehreren Wegen ( Jagen, Jagdbund, Nativ ) nach diesem Item nachgefragt. Keiner konnte ihm helfen.
Bei dem normalen Bogen wird eine Bogensehne benötigt. 

**Screenshots/Videos**

![image](https://github.com/user-attachments/assets/ebeaf4d8-c827-42e5-9d33-b004b35c769a)

**Kontaktdaten Melder**

 - IC-Name: Manteo Yuma
 - Discord: 281472221589798913

**Comment by Twackerino** [comment]
Mit Jagdupdate zu 16 behoben/geklärt
