### ISSUE TITLE
[BUG] Indianderbett

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#242]
**Beschreibe den Fehler**
Dass Campingitem Indianerbett lässt sich nicht aufstellen.

**Nachstellbar 
Ja
1, Nehme ein Indianerbett in dein Inventar
2. Doppelclick im Inventar auf dass Item
3. Fehler (lässt sich nicht aufstellen)

**Erwartetes Verhalten**
Wenn ich dass Item durch Doppelclick anwähle sollte es sich platzieren lassen.

**Screenshots/Videos**
https://medal.tv/de?contentId=i9G80AXHb6OD0jXLa&invite=cr-MSxodWIsNDg1MDAzMDcs&spok=d1337I0JiZcz
https://medal.tv/de/games/red-dead-2/clips/igbGIjjG32QGJBHrG/d1337EZSoonP?invite=cr-MSwxNmosMTkxMjM3Mzc4LA

**Kontaktdaten Melder**
 - IC-Name: Wesley Moon
 - Discord: gamerworld92

**Comment by Xuess22** [comment]
@SRIcely ich hab den Fehler gefunden. Das Bett ist im Native Crafting & im normalen Hunters Rest Crafting.
Ist jetzt nur die Frage wer das bekommen soll?

**Comment by Xuess22** [comment]
Quatsch mit Soße, ich benenne das einfach um. Dann haben das beide

**Comment by Xuess22** [comment]
zu 16 Uhr gefixt @SRIcely
