### ISSUE TITLE
NPC Entfernen

### ISSUE THREAD

**Issue by XPeTerchenX** [Sundown-Rising/sundown-rising-issues#244]
**Beschreibe die Verbesserung**
NPC Entfernen auf der Rhodes Ranch
NPC stört und steht im Weg, wird nicht gebraucht

**Screenshots/Videos**
![Bild_2024-07-14_134215094](https://github.com/user-attachments/assets/ed422f5c-86b6-4735-a60e-1a2d3383372a)

**Kontaktdaten Melder**
 - IC-Name: Louis Jenkins
 - Discord:  232414925753024512

**Sonstiges**

**Comment by Twackerino** [comment]
Coordinaten?

**Comment by Twackerino** [comment]
bzw hat der NPC ne funktion?

**Comment by Xuess22** [comment]
@XPeTerchenX zu 16 Uhr entfernt
