### ISSUE TITLE
[BUG] Ballon Strafe

### ISSUE THREAD

**Issue by SRKing-Sup** [Sundown-Rising/sundown-rising-issues#245]
**Beschreibe den Fehler**
Wenn man einen Ballon nicht beim Händler einparkt bekommt man eine $50 Strafe.

**Nachstellbar | Auschließen Client Problemen**
JA
Wurden Client-Fehler welche durch bspw. den Cache ausgelöst wurden ausgeschlossen 
JA
Falls Ja, folgende Schritte:
1. Park einen Ballon aus
2. Flieg ein Stück vom Händler weg
3. Landen
4. Einparken
5. Erhalt einer $50 Strafe (FEHLER)

**Erwartetes Verhalten**
Der Ballon verschwindet ohne Geldabzug

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/iczAJbFb5UhCLpD96/d1337tfJzaZJ?invite=cr-MSxLYzIsNzc5NjczMTMs

**Kontaktdaten Melder**
 - IC-Name: Kate Walker
 - Discord: 483624040859435028

**Comment by Twackerino** [comment]
Die parkt den Ballon irgendwo in ner Pampa und die müssen den Ballon von da abholen und fordern ne Strafzahlung. Kein Fehler.
