### ISSUE TITLE
Schlachter Wapiti

### ISSUE THREAD

**Issue by Benny9407** [Sundown-Rising/sundown-rising-issues#246]
**Beschreibe den Fehler**
Schlachttisch und Fellhändler in Wapiti sind nicht auffindbar, da der eig. Punkt nicht funktioniert.

**Nachstellbar | Auschließen Client Problemen**
JA
Es wurde bereits von einem Teamler gegengeprüft und funktioniert ebenfalls nicht.
Falls Ja, folgende Schritte:
1. kadaver auf der Schulter
2. Gehe zum Schlachttisch
3. Möchte kadaver abgeben/weiterverarbeiten
4. (FEHLER) Punkt nicht auffindbar

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Einen funktionierenden Schlachttisch

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/igCuPmfT880sDYDDp/d13372Qe39ZR?invite=cr-MSxWSHcsMTkxMjM3Mzc4LA

**Kontaktdaten Melder**
 - IC-Name: Adahy Black
 - Discord: 263369829187190785

**Comment by Twackerino** [comment]
fixed
