### ISSUE TITLE
[BUG] Metzger NPC's fehlen

### ISSUE THREAD

**Issue by SRKing-Sup** [Sundown-Rising/sundown-rising-issues#247]
**Beschreibe den Fehler**
Metzger NPC's fehlen

Wurden Client-Fehler welche durch bspw. den Cache ausgelöst wurden ausgeschlossen 
Ja

1. Geh zum Metzger
2. Metzger NPC weg (fehler)

**Erwartetes Verhalten**
Metzger NPC ist da

**Kontaktdaten Melder**
 - IC-Name: Dominik Lupus
 - Discord: 211277840950362112

**Sonstiges**
Ausserdem fehlen laut Melder die Bilder bei den Fellen.
Kann ich bestätigen

**Comment by Twackerino** [comment]
Änderung auf QOL da Fehler nur Optisch
