### ISSUE TITLE
[Wunsch] Drogenfarmen

### ISSUE THREAD

**Issue by Twackerino** [Sundown-Rising/sundown-rising-issues#25]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Zurzeit braucht man den Crime Job und die Drogenschere um die Drogen-Pflanzen zu sammeln

**Beschreibe die gewünschte Lösung**
Das Drogen ernten nur noch mit der Schere welche von der Bande an ihre Verkäufer heraus gegeben wird.

**Sonstiges**
Eingereicht von Meda

**Comment by MrBurns010** [comment]
Nur mit Crimejob ist der Drogenabbau möglich, um zu verhindern, dass den Banden wieder langweilig wird und die Zivis arbeiten lassen und die Zeit nutzen, um in den Städten scheiße zu bauen.

**Comment by Xuess22** [comment]
Lösungsvorschlag:
Man erstellt einen Job, Bspl. crime_praktikant.
Dieser Job wir auch auf die Schere geloggt.
Sollte die Crime also jemanden anstellen wollen, der denen beim Pflanzen ernten hilft oder Informationen beschafft, müssen sie das via Support Ticket einreichen und CM Crime kann diesen Job vergeben.
Haut der Spieler jetzt mit der Schere ab, kann die Crime ihm den Job wegnehmen lassen und Schere ist useless.
@MrBurns010 

Lösungsvorschlag aufgrund von Gespräch mit Medusa & Meddy.

**Comment by MrBurns010** [comment]
Aber wir haben lange und ausführlich darüber gesprochen, dass gerade diese Farming-Sachen nur für die Crime zugänglich sein sollen, damit **genau das** nicht passiert. Damit die Leute selbst abbauen. Damit sie nicht wieder Langeweile haben und die Leute unnötig ausrauben oder einen Ladenraub nach dem anderen machen.

Ich verstehe nicht, warum das jetzt alles umgeworfen werden soll. Ich habe einen Haufen Geld ausgegeben, damit die Jobblocks speziell für uns in die Scripts programmiert werden, weil es so gewünscht war. Und jetzt ist es plötzlich wieder genau andersherum.

Da frage ich mich dann ernsthaft, wofür ich mir die Mühe gemacht habe ... Da hätte ich das Geld genauso gut aus dem Fenster werfen können, wenn die Funktion nun plötzlich nicht mehr gewünscht ist, obwohl es anders besprochen war. @Xuess22

**Comment by Xuess22** [comment]
Verstehe dich da vollkommen & der Joblock ist auch super. Problem ist dass die Drogen, gerade am Anfang, wenig Gewinn bringen + Risiko sehr hoch ist beim Verkauf erwischt zu werden + hohe Strafe pro Joint. 
Das ernten der Drogen dauert ziemlich lange + ist auf der ganzen Map verteilt. 
So könnte man sagen, die Crime darf höchstens 2 "Praktikanten" einstellen ( mit Chance auf Blood-In ) und diese könnten beim ernten helfen. Gerade Guarma usw. Hier gehts lediglich darum, der Crime etwas unter die Hand zu greifen. @MrBurns010 

![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170861947/ee8bb7b8-49a1-42b3-821e-5b29cd2dfd56)

**Comment by Xuess22** [comment]
Ist schon behoben durch den Crime Anwärter. Ich close.
