### ISSUE TITLE
[QoL]  Wunsch nach einer Haltbarkeit für Blumensträuße

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#250]
**Beschreibe die Verbesserung**
- Das die blumen sträuße eine haltbarkeit erhalten da diese rein theoretisch ja verwelken nach 2-4 tagen.
- Blumen Buch vlt eine möglichkeit einführen womit man die etwas länger haltbar machen kann
also ohne zbs die blumenvase sind die nur 1-2 tag haltbar und mit blumenvase in der tasche sind die zbs 2-4 tage haltbar
um den sinn der blumen verkäufe noch aktraktiver zu machen.

**Details:**
- Normale Blumen Sträuße in Tasche: 1-2 Tage verwelk zeit.
- Sträuße mit Vase: 2-4 Tage verwelk zeit.

**Screenshots/Videos**
Keine

**Kontaktdaten Melder**
 - IC-Name: Jody McAllister
 - Discord: Jody McAllister (323405522739134465)
 - Steam: steam:1100001148dd215
 - Char ID: 4139

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
Unser Kernsystem unterstüzt keine Verwesung.
