### ISSUE TITLE
[BUG] Kleintiere können nicht zum Schlachter

### ISSUE THREAD

**Issue by SRKing-Sup** [Sundown-Rising/sundown-rising-issues#251]
**Beschreibe den Fehler**
Die kleintiere (Ratten u. Frösche) hat mab ja vorher direkt nur das fleisch/das tier ins inventar bekommen die kann man nun nicht mehr bekommen aber das tier wird nicht in der hand gehalten um es zum schlachter zu bringen

Wurden Client-Fehler welche durch bspw. den Cache ausgelöst wurden ausgeschlossen 
JA

**Erwartetes Verhalten**
Man hält das tier in der Hand und kann es zum Schlachter bringen

**Kontaktdaten Melder**
 - IC-Name: Dominik Lupus
 - Discord: 211277840950362112

**Comment by Twackerino** [comment]
Script für Zerlegbare/häutbare Kleintiere bereits den CM-Wirtschaft zu Einstellung gegeben.

**Comment by DevGonzi** [comment]
aktueller status @Twackerino ?

**Comment by Helmard** [comment]
Ich benötige die Liste sämtlicher Tiere die auf unserem Server rumlaufen, damit ich sie in dem Jägerscript hinzufügen kann.
Ich habe geschaut, es fehlen- nur als Beispiel- viele Schlangen und einiges was Dominic Lupus auch herausgefunden hat.

(https://discord.com/channels/1123352191751704606/1262118618108530688)

Die Tiere welche ich in dem Script bearbeitet hatte, standen ja schon drin. Ich weiß nicht ob die bei uns überhaupt auf dem Server sind (Bsp Water Snake - hab ich nie gesehen)

**Comment by Twackerino** [comment]
zu 21 mit Einführung von Ricx_skinner behoben
