### ISSUE TITLE
[BUG] Fleischer - Fell - Kein Eintrag für Fell gefunden" bei Schildkröte

### ISSUE THREAD

**Issue by MrBurns010** [Sundown-Rising/sundown-rising-issues#256]
**Beschreibe den Fehler**
Wenn man eine Schildkröte häutet kommt die Meldung: "Fell - Kein Eintrag für Fell gefunden!"

**Nachstellbar | Auschließen Client Problemen**
JA

**Screenshots/Videos**
![image](https://github.com/user-attachments/assets/ee70bfb1-f441-4b9b-9211-f72ee020c9b1)

**Comment by Twackerino** [comment]
Selbiges bei schlange siehe verlinkung oben

**Comment by DevGonzi** [comment]
Pelt trader oder butcher

**Comment by Twackerino** [comment]
Logik angepasst
