### ISSUE TITLE
[BUG] Notify beim Fleischer falsch

### ISSUE THREAD

**Issue by MrBurns010** [Sundown-Rising/sundown-rising-issues#257]
**Beschreibe den Fehler**
Beim Schlacht und Zerlegeauftrag wird der Itemname anstatt der Itemlabel in der Notify angezeigt.

**Nachstellbar | Auschließen Client Problemen**
JA

**Screenshots/Videos**
![image](https://github.com/user-attachments/assets/a07ef66e-4d45-4c53-9c70-f46b6a463991)

**Comment by Twackerino** [comment]
fixed
