### ISSUE TITLE
[BUG] Fleischer NPC - Alle Völker [NATIVES]

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#260]
**Beschreibe den Fehler**
Alle Völker haben ihren Fleischer verloren und können keine Kadaver abgeben. Sowie auch in dem Freien Feder Lager im Westen fehlt auch der Fleischer NPC.

**Nachstellbar | Auschließen Client Problemen**
JA

1. Geh zum Fleischer Tisch (Völker Fleischer)
2. Versuch den Kadaver zu verkaufen
3. (FEHLER) Interactions Punkt fehlt zum verkauf der Kadaver

**Erwartetes Verhalten**
Das bei allen Völker, sowie Freien Feder Lager die Fleischer NPCs interactions Punkte gesetzt werden und die Fleischer funktionieren.

**Screenshots/Videos**
Clip: https://medal.tv/de/games/red-dead-2/clips/ihpEMI1YezQd_7q2t/d1337TRASfyu?invite=cr-MSxJT3YsMTkxMDA0MTUyLA

**Kontaktdaten Melder**
 - IC-Name: Flinke Eule (2805)
 - Discord: 452902891489984522
 - Steam: steam:11000010bab3dbc

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
Fleischer punkte sind existent. https://discord.com/channels/1123352191751704606/1217920099386654810/1262045513381974077
zu beachten wenn nicht FFW oder Wapiti
