### ISSUE TITLE
[BUG] Angel lässt sich nd ausschwingen

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#263]
**Beschreibe den Fehler**
Wenn man die Angel raus nimmt und versucht zu Fischen, kann ma nd die Angel auswerfen.

**Nachstellbar | Auschließen Client Problemen**
JA

1. Geh zum Wasser
2. Nimm eine Angel raus
3. (FEHLER) Versuch die Angel auszuwerfen

**Erwartetes Verhalten**
Das man die Angel auswerfen kann.

**Screenshots/Videos**
Clip 1: https://medal.tv/de/games/red-dead-2/clips/ihVt0imZh6c-wJvfc/d1337UqeNuSZ?invite=cr-MSx1ZmIsNjg2MzAyMDYs
Clip 2 (mit F8 Log): https://medal.tv/de/games/red-dead-2/clips/ihWKD3Xh7h2Hknc6W/d13372hy26Iy?invite=cr-MSxPejEsNjg2MzAyMDYs

F8 Log Screenshot:
![Screenshot_2024-07-17_225318](https://github.com/user-attachments/assets/822bbca8-5753-4802-9a15-3265d60f3da0)

**Kontaktdaten Melder**
 - IC-Name: Jane Kurt (6451)
 - Discord: 447417484023169045 (Jane Kurt)
 - Steam: steam:11000013dd163e0

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
Ich würde empfehlen noch einen Köder an die Angel zu hängen. Das sollte die Verwirrung beheben

**Comment by aytoon** [comment]
Proble ist, sie hatte schon den Köder dran gehängt und man kann ihn nd raus werfen. Darum hat sie es auch gemerldet. ^^

**Comment by Twackerino** [comment]
Aus dem Clip nicht ersichtlich. Andere Empfehlung. Da unten rechts ist ein rotes Symbol, das mal weg.
