### ISSUE TITLE
[BUG] Fleischer - Fell - Kein Eintrag für Fell gefunden" bei Schlange

### ISSUE THREAD

**Issue by SRBjoern** [Sundown-Rising/sundown-rising-issues#264]
Wenn man eine Schlange Häutet bekommt man den Fehler Kein ertrag gefunden

**Nachstellbar | Auschließen Client Problemen**
JA

Fell sowie Fleisch und Schlangengift im Inventar

![image](https://github.com/user-attachments/assets/c58d200d-1b28-4e99-bd48-d4cdc1d81eaa)
![image](https://github.com/user-attachments/assets/54222c26-a27a-4b08-b82e-ef748e85f0e4)
![image](https://github.com/user-attachments/assets/e77b5c8d-773f-4896-9c94-4512f2f014cc)

 - IC-Name: Yakari Inola
 - Discord: 342387885351370752

**Comment by Twackerino** [comment]
doppelt #256
