### ISSUE TITLE
[BUG] Fischfallen fangen keine Fische

### ISSUE THREAD

**Issue by MrBurns010** [Sundown-Rising/sundown-rising-issues#265]
**Beschreibe den Fehler**
Fischfallen fangen keine Fische. Auch nach mehreren Stunden ist die Falle leer trotz das sich darin ein Köder befindet.

**Nachstellbar | Auschließen Client Problemen**
JA

**Erwartetes Verhalten**
Es soll nach ca. 15 Min. die Möglichkeit bestehen, einen Fisch zu fangen

**Screenshots/Videos**
![image](https://github.com/user-attachments/assets/d600a045-be9e-479b-ba18-94785416b409)

**Comment by Twackerino** [comment]
wenn die Falle anvisiert wird steht unten rechts die region. die brauch ich.

**Comment by Twackerino** [comment]
https://cdn.discordapp.com/attachments/1160971212382544022/1263988936506871858/image.png?ex=669f88ae&is=669e372e&hm=b14902ae15c5f5a0778642e4dc423ad9b9d087a10714740e1a18452a762bae02&
https://cdn.discordapp.com/attachments/1160971212382544022/1263988936749879438/image.png?ex=669f88ae&is=669e372e&hm=36cd0fdb3a0a62c07ca4d882488c97ccf5e6955ff7521503813430d65b44ca70&

**Comment by Twackerino** [comment]
![grafik](https://github.com/user-attachments/assets/ac257cbf-f967-4a65-977a-c0d2fd4f2157)
![grafik](https://github.com/user-attachments/assets/aeaacc07-ef32-446b-b486-57a0c2d75fcd)
