### ISSUE TITLE
Butcher Metzgeraufgabe sollen alle arten von Tiere dort abgegeben werden?

### ISSUE THREAD

**Issue by SRBjoern** [Sundown-Rising/sundown-rising-issues#266]
zur zeit ist das neue Butcher script so das auch Fische und andere Tiere wie z.B. Legendäre Tiere abgegeben werden müssen um die Aufträge zu erfüllen ist dieses so beabsichtigt?

**Comment by Twackerino** [comment]
Der Fleischer wählt zufällig aus allen abgebaren Tieren.
