### ISSUE TITLE
[BUG] Waffen werden komplett zerstört

### ISSUE THREAD

**Issue by SRBjoern** [Sundown-Rising/sundown-rising-issues#267]
**Beschreibe den Fehler**
Wenn Waffen kaputt gehen werden sie noch komplett zerstört und sind nicht mehr Reparable.

**Nachstellbar | Auschließen Client Problemen**
JA

**Erwartetes Verhalten**
Das die Waffe komplett zerstört im Inventar ist und man sie Reparieren kann
**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/iigJB91cdyVaIShFp/d1337waqWP6I?invite=cr-MSxMc08sNzcyMDI1Njks
![image](https://github.com/user-attachments/assets/641b1494-3743-415f-a520-edbaaddeda98)

**Kontaktdaten Melder**
 - IC-Name: Jack Winchester
 - Discord: 262597836384894976

**Comment by fraupan** [comment]
Wurde auf dem Main getestet: item "Kaputte Waffe" ist im Inventar, allerdings ohne Icon.
