### ISSUE TITLE
[BUG] Haustier stirbt beim Fliegen gegen char

### ISSUE THREAD

**Issue by DieBuu** [Sundown-Rising/sundown-rising-issues#271]
**Beschreibe den Fehler**
Haustier Vogel Fliegt beim Laufen gegen den Char und ist tot.

**Nachstellbar | Auschließen Client Problemen**
JA

Falls Ja, folgende Schritte:
1. Haustier rufen
2. Haustier fliegen lassen.
3. Vogel fliegt gegen den Char und liegt tot am Boden

**Erwartetes Verhalten**
Vogel kreist um den Char herum beim laufen.

**Videos**

https://github.com/user-attachments/assets/e2127b9c-9216-4082-9be7-b18bca9e389d

**Kontaktdaten Melder**
 - Ic Name: Toyatuku tue
 - Discord: Allisonblack

**Comment by joybtw** [comment]
Zum aktuellen Zeitpunkt nicht möglich. Script wird aber bald ersetzt 🤗 
Ich schließe dann hier erstmal
