### ISSUE TITLE
[BUG] Schlafmohn - Blüten nicht einsammelbar

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#272]
**Beschreibe den Fehler**
Der Spieler kann einige Schlafmohn Blüten nicht einsammeln, obwohl die da angezeigt werden.

**Nachstellbar | Auschließen Client Problemen**
JA

1. Geh zum Westen zu der Schlafmohn Plantage
2. Versuch die Blüten zu sammeln
3. (FEHLER) einige Blüten kann man nicht einsammeln.

**Erwartetes Verhalten**
Das man die Blüten einsammelbar werden.

**Screenshots/Videos**
Clip: https://medal.tv/de/games/red-dead-2/clips/ijDjrhK7zti167XP9/d1337R7KWVNO?invite=cr-MSw3OGUsMTk4NDcyNzc5LA

**Kontaktdaten Melder**
 - IC-Name: Rainer Thurner (4013)
 - Discord: 648108608080445440 (Rainer Thurner)
 - Steam: steam:11000010c146617

**Sonstiges**
Der Spieler, hatte alles schon probiert (Cache gelöscht usw.) Hat nix gebracht.

**Comment by fraupan** [comment]
Hallöchen @aytoon,

das Script ist leider verschlüsselt, wodurch wir da nichts machen können. Spieler soll ausspielen, dass manche Pflanzen eben noch nicht ernte-bereit sind.

Grüße!
