### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DieBuu** [Sundown-Rising/sundown-rising-issues#273]
**Beschreibe den Fehler**
Auslagen werden nicht angezeigt

**Nachstellbar | 
JA

Falls Ja, folgende Schritte:
1. Gehe an den Ort an dem die Auslage war
2. Verwalte/Kaufe/verkaufe der Auslage wird nicht angezeigt.

**Erwartetes Verhalten**
Die Verwaltung/Kaufe/verkaufe der Auslage werden angezeigt

**Screenshots/Videos**
![image](https://github.com/user-attachments/assets/3450f296-4cd9-450e-8482-f627d79b8727)

https://github.com/user-attachments/assets/59060b3b-eaba-4cd2-b0e4-7f50e281acbf

**Kontaktdaten Melder**
 - IC-Name: John Stone 
 - Discord: gothicteufel
 
 - IC-Name: Kate Blackwood
 - Discord: Misskreativa
 
- IC-Name: Will Black
 - Discord: likepandabaer
 

**Sonstiges**
Betroffene Gewerbe bisher

1Saloon in Annesburg
2Die Minen Anesburg.
3 Der Saloon in Valentine.
4Die BLW Ranch.
5 Der Fleischer in Tumbelweed
6 Minen auslage in Tumbelweed.
7 Rhodes Farm
8 Bäckerrei RH
9 Tabakladen SD
10 Mc Farlens Ranch

**Comment by aytoon** [comment]
Auslage BW fehlt

**Comment by Twackerino** [comment]
Vermutlich mit nächsten Restart behoben
