### ISSUE TITLE
[BUG] Shopraub - Start fehlgeschlagen

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#274]
**Beschreibe den Fehler**
Der Spieler versucht einen Shop Raub zu Starten, doch es kommt immer eine fehler meldung, dass "Es ist nicht der Richtige Zeitpunkt" währe.

**Nachstellbar | Auschließen Client Problemen**
JA

1. Geh in irgendein Shop rein
2. (FEHLER) Starte einen Shop Raub

**Erwartetes Verhalten**
Das beim Start eines Shop Raubs, es Startet und keine Fehlermeldung spuckt.

**Screenshots/Videos**
Person 1 Clip: https://medal.tv/de/games/red-dead-2/clips/ijcPCTpny1yDDEha_/d1337AWNwGxQ?invite=cr-MSxsWlAsMjAwNDM2OTk4LA
Person 2 Clip: https://medal.tv/de/games/red-dead-2/clips/ijSsANVEi_f7GKpES/d1337nXqVODo?invite=cr-MSxqM2IsMjAwOTkyNjU0LA

**Kontaktdaten Melder**
Person 1 -
 - IC-Name: John Watson (3909)
 - Discord: 191262121898672135 (SR | Björn)

Person 2 -
 - IC-Name: Michael Brown (6245)
 - Discord: 1232439797348569089 (Michael Brown)

**Sonstiges**
Fehler schon bei 2 Personen gesichtet. F8 Log zeigt auch kein Script error an. Cache bei beiden gelöscht und funktionirt immernoch nd.

**Comment by fraupan** [comment]
Ich liebe es, wenn sich Spieler darüber beschweren, obwohl da eine eindeutige Fehlermeldung dabei steht.
Nach Absprache mit Sabrina werden das Zeitfenster **nicht** verändert.
Stattdessen habe ich die Fehlermeldung angepasst.
