### ISSUE TITLE
[BUG] Falsche Federn im Crafting

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#277]
**Beschreibe den Fehler**
Im Craftingbuch der Waffenbauer bei den Natives sind noch die Federn vom alten Jagdscript hinterlegt.
Im neuen bekommen sie nur noch Federn und keine Hühnerfedern mehr.

Im Clip zu sehen sind die braunen Hühnerfedern (altes Script) und die weißen Federn (neues Script)

**Screenshots/Videos**
https://youtu.be/fzrvLhQtGHA

**Kontaktdaten Melder**
 - IC-Name: Unkas Nashoba
 - Discord: littlestigi

**Comment by Twackerino** [comment]
zu 21
