### ISSUE TITLE
Pferdesichtungen doppelter Abzug NPC Ad

### ISSUE THREAD

**Issue by XPeTerchenX** [Sundown-Rising/sundown-rising-issues#279]
**Beschreibe den Fehler**
Pferdeinformationen wird doppelt abgerufen -> Geld doppelt abgezogen + 2 Spawnpunkte auf der Map

**Nachstellbar | Auschließen Client Problemen**
JA, kein Client Problem.

Falls Ja, folgende Schritte:
1. Pferdeinfo kaufen bei NPC Armadillo
2. Geld wird doppelt abgezogen+ 2 Spawnpunkte auf der Map angezeigt

**Erwartetes Verhalten**
1x Pferdeinformation

**Screenshots/Videos**
NPC Armadillo: doppelter Abzug Info 1:
https://medal.tv/de?contentId=ifSCG6yfkFSLMwuNM&invite=cr-MSxCSGQsMjAzODE2MzM2LA&spok=d1337AJg1XZQ 
Map Spawnpunkte:
![image](https://github.com/user-attachments/assets/abdaf955-f6c9-4d62-9c2a-23661ee3602a)

Pferd an Spawnpunkt 1 nicht zu finden:
https://medal.tv/de/games/red-dead-2/clips/ifSS4Z9YDoIW1e5Bm/d1337dlbM2Xn?invite=cr-MSw4VkUsMjAzODE2MzM2LA2

Nachgestellt NPC Armadillo: doppelter Abzug Info 2:
https://medal.tv/games/red-dead-2/clips/iizOKCy2wZaxDQ5WH/d1337hH3bbRC?invite=cr-MSxyUHMsMTkzMTg4ODk2LA

**Kontaktdaten Melder**
 - IC-Name: Seto Daimon
 - Discord: 1145818448354607224
 - IC-Name: Nora Daimon
 - Discord: 450740906648272906

**Comment by fraupan** [comment]
Nicht reproduzierbar, alle Tests liefen korrekt ab
