### ISSUE TITLE
Tierfett

### ISSUE THREAD

**Issue by iTzAlca** [Sundown-Rising/sundown-rising-issues#28]
https://prnt.sc/XafAcNjLMfdI
Hallo liebe Developer.
Unser Lieber Helmard der für die Wirtschaft zuständig ist würde das geändert haben. Wir haben da abgestimmt untereinander siehe prnt Screen oder den Text den ich einfach poste.

Ich habe folgendes während meiner IC Zeit im Jagdbund festgestellt.

Der Outcome von Tierfell, Leder & Fleisch ist voll in Ordnung.
Jedoch ist der Outcome von Tierfett leider nicht im Verhältnis zu dem, was bestellt, gebraucht und geschossen wird.
Man bekommt aktuell Tierfett nur aus Großwild. Kein Vogelwild oder Kleinwild gibt im Moment Tierfett.
Aktuell benötigen meines Wissens nach folgende Gewerbe Tierfett :

- Ärzte
- Saloons
- Bäckerei
- Hufschmied
- Hunters Rest (Trapper)
- Kutschenbauer

Ich habe den Jagdbund nun eine Woche und konnte bisher alle Bestellungen abarbeiten.
Tierfett jedoch staut sich nun schon auf über 1200 bestellte Einheiten an und man kommt schlicht mit der "Produktion" nicht nach.
In der Theorie sind von einem Kadaver 25 % Fett, 15 % Organe, 15 % Fell und Knochen, 45 % Fleisch

Mein Vorschlag :

- Tierfett auch aus Vogel- und Kleinwild erhalten (je 2 Schalen)
- Tierfett aus Großwild (alles was hinten aufs Pferd gelegt wird: Hirsch, Fuchs, Kojote, Wildschwein, Alligator etc) auf 4 Schalen pro Tier erhöhen (aktuell 2)

**Comment by joybtw** [comment]
Ja, ist umsetzbar. Nächstes mal setzt dein Tag richtig und dann beantworten wir auch deine Frage

**Comment by iTzAlca** [comment]
Top

**Comment by Xuess22** [comment]
Ist zum 2 Uhr Restart gefixt, kann das jemand closen? @joybtw

**Comment by Twackerino** [comment]
Von Sabrina abgeändert
