### ISSUE TITLE
[BUG] Pferde der Sichtungen können nicht gefangen werden

### ISSUE THREAD

**Issue by DieBuu** [Sundown-Rising/sundown-rising-issues#280]
Pferde von den Sichtungen können nicht gefangen werden. Pferde laggen umher.

**Nachstellbar 
JA

Falls Ja, folgende Schritte:
1. Pferde Info holen
2. An den Ort gehen zum Pferd
3. Pferd versuchen zu fangen
4. Buggt nach vorne und zurück. 
5. lässt sich nicht fangen und verschwindet.

**Erwartetes Verhalten**
Pferd Bugt nicht vor und zurück und lässt sich fangen

**Screenshots/Videos**

https://github.com/user-attachments/assets/3daf0ebc-a01b-4a9c-a882-dc38ee354490

**Kontaktdaten Melder**
 - IC-Name: Penny Miller
 - Discord: Jenny2516

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by fraupan** [comment]
In Absprache mit der Spielerin schließe ich das Ticket. Das Problem kann nicht nachgestellt werden.
Liegt vermutlich am Sync, da die Sichtungen jeweils abends zur Primetime waren.
