### ISSUE TITLE
[BUG] Gus Missionen Fehlerhaft

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#281]
**Beschreibe den Fehler**
Wenn man einen Auftrag von Gus macht bricht am Ende der Auftrag ab da man das Fell direkt ins Inventar kriegt sobald man das Legendäre Tier häutet.

**Nachstellbar 
JA
1. Nimm einen Auftrag bei Gus an
2. Folge den Hinweisen um das Legendäre Tier zu finden.
3. Töte das Legendäre Tier
4. Häute das tote Tier
5. (Fehler) Auftrag bricht ab da man das Fell nicht zu Gus tragen kann (Fell geht direkt ins Inventar)

**Erwartetes Verhalten**
Ich bekomme das Fell als Prop um es dann bei Gus abliefern zu können.

**Screenshots/Videos**
https://medal.tv/games/red-dead-2/clips/ilrzaGYW7x8qjhlRD/d1337LkVXZz5?invite=cr-MSxxWnosMTYwMjQzMDA2LA
https://medal.tv/de/games/red-dead-2/clips/ilrQzjF4CmGFUUuVT/d1337txBQZiG?invite=cr-MSx0VHksMTkxMjM3Mzc4LA

**Kontaktdaten Melder**
 - IC-Name: Kate Walker
 - Discord: katetm
 
 - IC-Name: Aluna Hamilton
 - Discord: seyumii

**Comment by joybtw** [comment]
Der Clip existiert nicht mehr, bitte erneut senden <3

**Comment by SRIcely** [comment]
Der zweite existiert noch. Dort siehst du einen kompletten Auftrag. Kann es aber gerne nochmal wiederholen.

**Comment by XPeTerchenX** [comment]
### Beschreibe den Fehler:
Abbruch **WATSON** Auftrag 

**Nachstellbar
JA

1. Nimm einen Auftrag bei Watson an
2. Folge den Hinweisen um das Legendäre Tier zu finden.
3. Töte das Legendäre Tier
4. Häute das tote Tier
5. (Fehler) Auftrag bricht ab da man das Fell nicht zu Watson tragen kann (Fell geht ohne ICON direkt ins Inventar)

Erwartetes Verhalten:
Fell als Prop erhalten für die Abgabe

Screenshots/Videos
https://medal.tv/games/red-dead-2/clips/iqws5U17DO8kDq-VO/d1337PRucFqa?invite=cr-MSx2bE0sMjIwMTM1ODE4LA
https://medal.tv/games/red-dead-2/clips/iqwz3miprPw_s_Sgi/d1337kX4pXgr?invite=cr-MSxHUW4sMjIwMTM1ODE4LA


Kontaktdaten Melder

IC-Name: Santo Dalton
Discord:  463826133306048533
