### ISSUE TITLE
[BUG] Camp System - Native aufsteller wird keine Interaction gezeigt

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#282]
**Beschreibe den Fehler**
Der Native Spieler hatte 2 Camp Artikel aufgestellt und werden:
a. Nicht mit dem Boden gesynct.
b. Interaction zum Auf- & Abbauen wird nd gezeigt. (Auch im Firstperson)

**Nachstellbar | Auschließen Client Problemen**
JA

1. Nimm ein Native Camp Artikel und benutze sie
2. Stell ein Native Artikel auf
3. (FEHLER) Artikel schwebt in der Luft
4. (FEHLER) Interaction zum Auf- & Abbau wird nicht gezeigt

**Erwartetes Verhalten**
Das die Interaction wieder sichtbar ist und die Native Camp Artikel nicht in der Luft schweben

**Screenshots/Videos**
https://medal.tv/de/games/screen-capture/clips/imm0IzTyTDzLaVXxx/d1337udQfg04?invite=cr-MSxvbkgsMTk4NDcyNzc5LA

**Kontaktdaten Melder**
 - IC-Name: Sakima Maska (2462)
 - Discord: 364499001900269568 (Sakima Maska)

**Sonstiges**
Der Spieler hatte schon Cache gelöscht und der Fehler scheint bei anderen auch zu sein.

**Comment by aytoon** [comment]
Problem besteht auch bei einer anderen Spielerin. Sie hat ein Tipi ausgestellt und zeigt keinerlei Interactionen an zum An- und Abbauen.

**Screenshots/Videos**
https://youtu.be/ppbMabvWrvY

**Kontaktdaten Melder**
- IC-Namen: Toyatuku tue (1201)
- Discord: 229279031827103744

**Comment by MrBurns010** [comment]
@aytoon 

Wird durch neues Campingscript behoben.
_Geplanter Release: 17./18. oder 24./25. August 2024_

Bitte Spieler informieren :-)
