### ISSUE TITLE
[BUG] Ranch Buch - Buch Öffnet sich nicht

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#283]
**Beschreibe den Fehler**
Wenn man das Ranch Buch der Siedler öffnen will, geht er nicht auf (UI öffnet sich nicht)

**Nachstellbar | Auschließen Client Problemen**
JA

1. Nimm ein Ranch Buch (Siedler) in den Inventar
2. Doppelklick auf das Ranch Buch
3. (FEHLER) Seiten öffnen sich nicht

**Erwartetes Verhalten**
Das nach dem Doppelklick auf das Buch, die Seiten sich öffnen.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/ilEQ9SCUgorGI-zAC/d1337iS9bt8f?invite=cr-MSw5MkssMjIxNTc5OTMwLA

F8-Log Clip: https://medal.tv/games/red-dead-2/clips/im0DRI1Q9URinO6Hr/d1337l5oaioX?invite=cr-MSx0Y3MsMjIxNTc5OTMwLA

**Kontaktdaten Melder**
 - IC-Name: Elaine Winchester (4309)
 - Discord: 409740765946839041

**Sonstiges**
Spieler hatte bereits vorher Cache geleert und hatte es mehrfach versucht, trotz nach mehreren scheiterungen.

**Comment by fraupan** [comment]
@aytoon Video ist leider nicht verfügbar. Bitte manuell hochladen :)

**Comment by fraupan** [comment]
Ohne Clip nicht nachstellbar.
