### ISSUE TITLE
[BUG] Bison Jagd hat keine Wilderer

### ISSUE THREAD

**Issue by DieBuu** [Sundown-Rising/sundown-rising-issues#286]
**Beschreibe den Fehler**
Bei der Legendären Bisonjagd kommen keine Wilderer

**Nachstellbar | 
JA/
Nur als Native machbar.

Falls Ja, folgende Schritte:
1.Jagd annehmen für das Bison
2. Leiche nach Spuren absuchen
3.Wilderer tauchen nicht auf

**Erwartetes Verhalten**
 Dann Wilderer erlegen. Dann eine Spur finden wenn alle Wilderer tot sind - das tote Tier spawnt dann sobald alle Wilderer tot sind 
Dann Bison jagen. 

**Screenshots/Videos**

**Kontaktdaten Melder**
 - IC-Name: Noya Ahyoka
 - Discord: Cayris24

https://github.com/user-attachments/assets/b2d51091-d4d7-42c7-aa12-b96bc47940df

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by XPeTerchenX** [comment]
Gerade getestet : die Wilderer erscheinen bei mir

**Comment by fraupan** [comment]
Fehler anscheinend nicht vorhanden, bitte mal Cache leeren lassen.
