### ISSUE TITLE
[BUG] Armadillo Bank - Interaction nicht vorhanden & doppel NPC

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#287]
**Beschreibe den Fehler**
Der ganz rechte Cashier in der Bank in Armadillo ist nicht ansprechbar. Das erstellen eines Konto in Armadillo ist nicht möglich. Des Weiteren ist dieser zwei mal an seiner Position.

**Nachstellbar | Auschließen Client Problemen**
JA

1. Geh zum Armadillo Bank
2. (FEHLER) Interaction nicht sichtbar & NPC steht doppelt an selben stelle

**Erwartetes Verhalten**
Interaction sichtbar machen und 2ter NPC soll weg

**Screenshots/Videos**
![Screenshot_2024-07-29_154418](https://github.com/user-attachments/assets/729a8276-8a37-4228-8735-799b5370a816)

**Kontaktdaten Melder**
 - IC-Name: Jarrisson Kurt (6277)
 - Discord: 305036836336828416 (Jarrisson Kurt)

**Sonstiges**
Spieler hat schon mehrmals Cache geleert und trotz restarts, wird da nix angezeigt.

**Comment by Twackerino** [comment]
Zum Thema Kontoerstellen
https://discord.com/channels/1123352191751704606/1194353861201231942/1194353861201231942

Dort existiert nur ein interaktionspunkt für die bank und 1 für ausweis. Beide punkte funktionieren.
