### ISSUE TITLE
Muttraining[BUG]

### ISSUE THREAD

**Issue by ItsLanoo** [Sundown-Rising/sundown-rising-issues#288]
**Beschreibe den Fehler**
Kate Blackwood meint das Mut Training bei Pferde geht schneller als sonst

**Nachstellbar | Auschließen Client Problemen**
JA
Wurden Client-Fehler welche durch bspw. den Cache ausgelöst wurden ausgeschlossen (https://discord.com/channels/1123352191751704606/1131142465806675979 )
Falls Ja, folgende Schritte:
Nein 

**Erwartetes Verhalten**
Das Pferd braucht länger zum Training

**Screenshots/Videos**
Es gibt keine Vorhandenen Screenshots oder Videos

**Kontaktdaten Melder**
 - IC-Name: Kate Blackwood
 - Discord: 530897294443151390

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by fraupan** [comment]
Ohne Clips kann man das nicht nachvollziehen.
Man hat aktuell eine 70%ige Wahrscheinlichkeit, dass das Pferd beim Kontakt mit Wildtieren Mut+1 bekommt. 
Vermutlich hat sie einfach viel Glück.
