### ISSUE TITLE
[BUG] Leuchtturm Van Horn - Tür geht mit Leuchtturm Schlüssel nicht auf

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#289]
**Beschreibe den Fehler**
Der Spieler hat einen Leutturm Schlüssel und kann es nicht öffnen auch bei Doppelklick.

**Nachstellbar | Auschließen Client Problemen**
JA

1. Geh nach Van Horn zum Leuchtturm
2. Doppelklick auf Schlüssel / Versuch die Tür zu öffnen
3. (FEHLER) Tür geht nicht auf (Schlüssel bleibt im Inventar)

**Erwartetes Verhalten**
Das der Leuchtturm aufgeht

**Screenshots/Videos**
https://medal.tv/games/red-dead-2/clips/indTe1YIoAEzwLwOh/d13370cVJt0M?invite=cr-MSx6V1csMTI1MTE3NDM1LA

**Kontaktdaten Melder**
 - IC-Name:  Oscar Crowley (5267)
 - Discord: 860137322490363905 (Oscar Crowley)

**Sonstiges**
Der Spieler hatte sein Cache Ordner gelöscht, trotzdem geht das Turm nicht auf.

**Comment by joybtw** [comment]
Der Leuchtturm ist nicht mehr vorgesehen für eintretende Spieler
