### ISSUE TITLE
Legendärer Wolf [BUG]

### ISSUE THREAD

**Issue by xxLiiisaaaxx** [Sundown-Rising/sundown-rising-issues#29]
**Beschreibe den Fehler**
Eine klare Fehler beschreibung.
Die NPC Leichen geben keine Hinweise auf den Legendären Wolf.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Jagdauftrag annehmen
2. Ort anreiten
3. Leichen auf Hinweise durchsuchen
4. (FEHLER) Leichen geben keine Hinweise auf Aufenthaltsort.

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Hinweise auf den Aufenthaltsort des Legendären Wolfes.

**Screenshots/Videos**
https://youtu.be/Iwz8oW3ZgTE

**Kontaktdaten Melder**
 - IC-Name: Cassidy Blackbeard
 - Discord: 802470240705052682

**Sonstiges**

**Comment by MrBurns010** [comment]
gefixt

https://github.com/Sundown-Rising/sundown-rising-private/commit/d30fe9c9aa838135915b62aee2db9a718c32eca4
