### ISSUE TITLE
Federn werden nicht mehr benötigt für Rezept

### ISSUE THREAD

**Issue by SRBjoern** [Sundown-Rising/sundown-rising-issues#292]
Natives und Jagdbund

Jagdbund wird Federn nicht mehr los ewil diese Nicht mehr von Natives benötigt werden
![image](https://github.com/user-attachments/assets/e098e3b1-dbfe-48cd-9097-1b84e0553eba)

**Kontakt - Gewerbeamt**
Sabrina

**Kontakt - Gewerbe**
IC-Name: Luigi Patrov
Discord: 917516169144074261

**Comment by Twackerino** [comment]
Alte Federn von DB zu den anderen Federn austauschen lassen
