### ISSUE TITLE
[BUG] Ranch Book - Buch öffnet sich nicht

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#293]
**Beschreibe den Fehler**
Die Spielerin versucht ein Ranch Buch zu öffnen, doch es kommen Errors raus und die Ui öffnet sich nicht.

**Nachstellbar | Auschließen Client Problemen**
JA

1. Öffne ein Ranch Buch
2. (FEHLER) UI öffnet sich nicht und error zeigen sich im f8 log

**Erwartetes Verhalten**
Das beim Doppelklick auf das Ranch Buch, die UI sich öffnet und die Seiten angezeigt werden.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/inFmMZ2oqrG0Y8I0v/d1337GaXDu2J?invite=cr-MSxLZW4sMjIxNTc5OTMwLA

**Kontaktdaten Melder**
 - IC-Name: Seto Daimon (545
 - Discord: 1145818448354607224 (Seto Daimon)

**Sonstiges**
Spielerin hatte schon ihren Cache Ordner geleert, trotzdessen erscheint der Error mehrmals.

**Comment by fraupan** [comment]
Problem kann nicht nachgestellt werden
