### ISSUE TITLE
[BUG] Pferdestallproblem im Gemeinschaftsstall

### ISSUE THREAD

**Issue by SRMarcel** [Sundown-Rising/sundown-rising-issues#298]
**Beschreibe den Fehler**
viele von uns haben aktuell Probleme mit dem Gemeinschaftsstall. Wenn wir Pferde rausholen, können wir uns bewegen, aber die Sicht bewegt sich nicht mehr. Siehe Clip

**Nachstellbar | Auschließen Client Problemen**
Noch nicht selber versucht

Wurden Client-Fehler welche durch bspw. den Cache ausgelöst wurden ausgeschlossen 
-> Ja, Spielerin hat das Problem wohl wie einige andere seit 2 Tagen.
![Bild_2024-08-01_230704303](https://github.com/user-attachments/assets/b6c1017f-f4c6-4a48-acf7-e01833b16534)

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis? 
-> Kamera bewegt sich mit dem Spieler

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/inwilsRsOQQGIgynh/d1337pRB3XvM?invite=cr-MSw3QU0sMjI1ODczODQ1LA)
Bild: https://cdn.discordapp.com/attachments/1268264533445574676/1268606420224315413/image.png?ex=66ad094c&is=66abb7cc&hm=7542928515d97c6fa9c78049c7e37e2884368d66c855dfb5e3b3ea5a72d2cabe&

**Kontaktdaten Melder**
 - IC-Name:Kate Blackwood
 - Discord:  ID 530897294443151390

Gruß

Marcel

**Comment by fraupan** [comment]
Konnte weder auf dem Dev-Server noch auf dem Main-Server nachgestellt werden. Ticket wird in Absprache mit der Spielerin Kate Blackwood geschlossen.
