### ISSUE TITLE
[QoL] Jugendchars - Händler zugriff gewähren

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#299]
**Beschreibe die Verbesserung**
Eine Spielerin gibt einen Vorschlag für Jugendchars raus. In dem es beinhaltet, dass Jugendchars zugriff bekomme, um Sträuße bzw. Blumen anzupflanzen, damit die jugendchars Sträuße verkaufen könnten als nebenjob mäßig.

**Kontaktdaten Melder**
 - IC-Name: Jody McAllister (4139)
 - Discord: 323405522739134465 (Jody McAllister)

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
Das Blumenbuch hat kein lock. Verstehe bisher nicht was hier von uns gewollt wird.

**Comment by aytoon** [comment]
Sie meint, dass man als nicht Farmer den Händler nd ansprechen kann. Das man für Jugendchars das evt freischalten könnte.

**Comment by aytoon** [comment]
Um Samen für Blumen zu kaufen

**Comment by Twackerino** [comment]
Ist das auch mit den CM / Charcontrol abgesprochen?

**Comment by aytoon** [comment]
Nope, ich sprech ma mit den Char Control ma ab

**Comment by Xuess22** [comment]
@aytoon und?

**Comment by fraupan** [comment]
@aytoon Gibts da was Neues?

**Comment by aytoon** [comment]
Ich hatte mit der Charcontrol gesprochen und die fanden es entweder nd so prickelnd, da man nie verboten wird die bücher zu nutzen oder Blumen nd anzupflanzen. Sie muss dann halt die Samen kaufen und anpflanzen und im RP verkaufen.
