### ISSUE TITLE
[BUG] Dietriche Craften

### ISSUE THREAD

**Issue by Twackerino** [Sundown-Rising/sundown-rising-issues#3]
**Beschreibe den Fehler**
Bauanleitung Dietrich für Crimler mit Crimejob nicht funktionstüchtig. sie Video und Test.
Eisenbarren werden nur teilweise abgezogen
die Bauanimation dauert 1x 60sek dann, 15sek und 5sek
Abbruchanimation willkürlich
keine Dietriche erzeugbar

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Hab den Crimejob
2. Bau Dietriche
3. (FEHLER) Eine der oben beschriebenen Auskommen

**Erwartetes Verhalten**
Dietrich wird gecraftet

**Screenshots/Videos**
![grafik](https://github.com/Sundown-Rising/sundown-rising-issues/assets/58168452/ecd1d56a-f254-4a6b-b42b-53f5d5218016)
https://youtu.be/IB_NVGW5MXQ

**Kontaktdaten Melder**
 - IC-Name: Darko Montero
 - Discord: nephilimsebastian - 201091511444570123

**Comment by joybtw** [comment]
Hier wird noch auf Toto gewartet
~ Sabrina 26.05.2024

**Comment by MrBurns010** [comment]
Laut Changelog vom 24.05.2024 durch @fraupan gefixt :-)
