### ISSUE TITLE
Legendäres Widderfell 

### ISSUE THREAD

**Issue by XPeTerchenX** [Sundown-Rising/sundown-rising-issues#30]
**Beschreibe den Fehler**
Nach erfolgreicher Jagd bekommt man lediglich 
12$ 
8x Wildfleisch 
3x Tierfell
jedoch nicht das legendäre Widderfell

**Nachstellbar**
Ja
Falls Ja, folgende Schritte:
1. Geh zum Jagdautraggeber Benjamin
2. Wähle Auftrag Schaf
3. Suche totes Schaf
4. Töte die Wilderer
5. Töte das legendäre Schaf
6. Gib den Kadaver ab bei Benjamin
7. Fehler: man bekommt kein legendäres Widderfell

**Erwartetes Verhalten**
legendäres Widderfell als Erzeugnis im Inventar

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.

**Kontaktdaten Melder**
 - IC-Name: Elijah Clark
 - Discord:  424919721301901312

**Sonstiges**
hab es selbst einmal getestet

**Comment by XPeTerchenX** [comment]
[
![Bild_2024-05-29_095057256](https://github.com/Sundown-Rising/sundown-rising-issues/assets/143320133/307b02e6-3397-40f6-a3e7-4756db69ce35)
](url)

**Comment by XPeTerchenX** [comment]
https://medal.tv/de/games/red-dead-2/clips/2cmmExVAEjxLv2/d1337FitlCN3?invite=cr-MSxLNWgsMjAyMjc2NjQ5LA

**Comment by Xuess22** [comment]
fixed zu 21 Uhr @XPeTerchenX
