### ISSUE TITLE
Telefone funktionieren nicht [BUG]

### ISSUE THREAD

**Issue by xxLiiisaaaxx** [Sundown-Rising/sundown-rising-issues#301]
**Beschreibe den Fehler**
Die Telefone sind ausser Betrieb

**Nachstellbar | Auschließen Client Problemen**
JA
Falls Ja, folgende Schritte:
1. Gehen Sie ins Office oder eine Telefon Station
2. Versuchen Sie zu Telefonieren
3. (FEHLER) Telefone gehen nicht

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Das man andere Telefone Anrufen kann

**Screenshots/Videos**
https://youtu.be/JgJzA7i6CCQ

**Kontaktdaten Melder**
 - IC-Name: Louise Nowak
 - Discord: 739100310169059370

**Sonstiges**
Wir als CM Law, würden gerne das die Telefone gefixxt werden damit die Kommunikation innerhalb der Offices wieder schneller stattfinden kann.

Grüße Pony und Elite

**Comment by fraupan** [comment]
Erkenntnisse:
- Der Clip ist nicht aussagekräftig (Aufm Dev gemacht, wo Saltychat aus ist -> Kann per se nicht funktionieren^^)
- Ressource ist auf dem Main aus dem Autostart genommen, Recherche läuft, warum das so ist.

**Comment by fraupan** [comment]
Nach Absprache mit Toto:
Script darf nichtmehr verwendet werden, da der komplette Server crashed, wenn niemand abhebt. 
Aktuell gibt es allerdings auch keine Alternative.
