### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ItsLanoo** [Sundown-Rising/sundown-rising-issues#303]
**Beschreibe den Fehler**
Die Spielerin Delphine Petit hat das Problem dass sie ihr Pferd nicht mehr in den Stall kriegen kann. Wenn man versucht ihr es zu geben sei der Stall laut anzeige voll, obwohl sie nur 3 Pferde im Stall hat. Laut ihrer beschreibung hat sie auch ein Pferd abgegeben an einen Rancher und kriegt es nun nicht mehr zurück.

**Nachstellbar | Auschließen Client Problemen**
NEIN
Wurden Client-Fehler welche durch bspw. den Cache ausgelöst wurden ausgeschlossen (https://discord.com/channels/1123352191751704606/1131142465806675979 )
Falls Ja, folgende Schritte:

**Erwartetes Verhalten**
Das man der Spielerin wieder Pferde in den Stall stellen kann 

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/ioRkMf1GumhXQRZ2F/d1337AUnpFRm?invite=cr-MSxPQTEsMTc4OTQ2MzczLA
https://medal.tv/de/games/red-dead-2/clips/ioRkMzWWcdVGD2k8_/d1337rkOEKkv?invite=cr-MSxQWGQsMTgyNjYyNjYzLA

**Kontaktdaten Melder**
 - IC-Name: Delphine Petite
 - Discord: 329221078889136128

**Sonstiges**
Sie hat ihre Stall Kapazität noch nicht erreicht und müsste eigentlich noch Platz haben

**Comment by Twackerino** [comment]
Per DB prüfen lassen ob datenleichen existieren

**Comment by ItsLanoo** [comment]
Git hat sich erledigt da die Person das Ticket geschlossen hat
