### ISSUE TITLE
[Wunsch] Meldung bei Drogen verkauf an die Law

### ISSUE THREAD

**Issue by DieBuu** [Sundown-Rising/sundown-rising-issues#305]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Wenn Drogen verkauft werden auf der Straße an NPC´s geht keine Meldung an die Law raus.

**Beschreibe die gewünschte Lösung**
Das eine Benachrichtigung an die Law rausgeht wenn Drogen in einer Stadt verkauft werde. Die Stadt dann auch angegeben wird wo verkauft wurde. 

**Gibt es Alternativen die bereits überlegt wurden und warum reichen die nicht?**
Diese Nachrichten gingen früher schonmal und die Law hat diese auch Angegritten . So würde es wieder mehr für die Law geben weil Jose ja nicht so viel gemacht wird.

**Sonstiges**
Wurde mit Elite Getestet und würde er auch gut finden. So können Banden die Sachen in den Städten verkaufen ohne Konsequenzen. 
![image](https://github.com/user-attachments/assets/f805bed4-4965-4686-8ef2-0cad56663ea4)
 Sowas an die Law nur mit Illegalem Straßenverkauf gemeldet

**Comment by fraupan** [comment]
![image](https://github.com/user-attachments/assets/bd37de7d-d283-444b-aab5-d29f5f471d9b)

Es gibt so eine Meldung bereits. Diese wird allerdings nicht immer sofort ausgelöst, sondern erst nach ein paar erfolgreichen Käufen (je nach Stadt, in der Verkauft wird)
