### ISSUE TITLE
[Wunsch] Blättchen Joints

### ISSUE THREAD

**Issue by DieBuu** [Sundown-Rising/sundown-rising-issues#307]
Banden brauchen für ihre Joints die Blättchen um sie zu drehen. Wäre es nicht auch gut wenn man diese Blättchen auch für die Zivi Joints brauchen würde.
Die Banden haben Unmengen davon weil sie viele Herstellen müssen um Erfahrung zu bekommen. Wenn aber Zivis die Drogen machen die Blättchen bei den banden holen müssen, wäre das ja wieder mehr Crime Rp. 

**Beschreibe die gewünschte Lösung**
Blättchen zum Crafting der Zivis Joints hinzufügen. Bisher braucht man nur Blüten und Tabak und Valerien. 1 Blättchen pro Joint wäre gut im Rezept da man immer einen Herstellen kann

**Sonstiges**
Alles andere Hilfreiche

**Comment by MrBurns010** [comment]
Wessen Wunsch ist es? Der von der Community oder deiner? :-)

Die Community hat nahezu einstimmig entschieden, dass die Drogen für Zivis unabhängig sein sollen, ohne dass ein Handel stattfinden muss.

@DieBuu

**Comment by DieBuu** [comment]
Ich hatte mit der crime Rücksprache gehalten. Kann das aber gerne als Vorschlag einreichen ;)

**Comment by Twackerino** [comment]
https://discord.com/channels/1123352191751704606/1271035331600322651/1271171769855901709

Abstimmung von Medusa pausiert. Bei fertiger Ausarbeitung gerne von CM wieder anfragen.
