### ISSUE TITLE
[BUG] Fleischer und Fellhändler in Annesburg fehlen

### ISSUE THREAD

**Issue by DieBuu** [Sundown-Rising/sundown-rising-issues#309]
**Beschreibe den Fehler**
Der Fleischer steht an der stelle aber ohne Funktion. Man kann keine Kadaver und Felle abgeben

**Nachstellbar | 
JA/

Falls Ja, folgende Schritte:
1.Gehe zum Schlachter Tisch mit Kadaver in der Hand
2. Man kann den Kadavaver nicht abgeben

**Erwartetes Verhalten**
Man kann den Kadaver abgeben oder auch die Jagdaufträge annehmen

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1268883802315558932/1268917322534621285/image.png?ex=66b56b19&is=66b41999&hm=7cac9aa4523e11654b43f4d1be15d113fb5d2e40accffdef726ef1b0cda162ec&

https://github.com/user-attachments/assets/da57ea65-48b2-4999-a38f-277f3803ef85

**Kontaktdaten Melder**
 - IC-Name: Robert Blue
 - Discord: bluecher1967

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Xuess22** [comment]
@DieBuu ist zu 12 Uhr gefixt. Steht in den Changelogs.
