### ISSUE TITLE
Underground Medic [Gewerbe]

### ISSUE THREAD

**Issue by Twacker2** [Sundown-Rising/sundown-rising-issues#31]
**Welches Gewerbe?**
Underground Medic

**Problem / Anfrage**

Neue Rezepte: 
Morphiumzäpfchen
-> Gleich wie das Koka-Kaugummi der Ärzte

Heilkräuterbalsam
-> Gleich wie die Aktiv Salbe der Ärzte

Vitalis Salbe
-> Gleich wie die Wundsalbe der Ärzte

Kurpfuschers Sud
-> Gleich wie der Beruhigungstee der Ärzte

Hilfe Koffer wie Medic-Script

**Kontakt - Gewerbeamt**
Bspw. Sabrina

**Kontakt - Gewerbe**
IC-Name: Mirella Edison
Discord: 884021556404166676

**Sonstiges**
nichts

**Comment by Twacker2** [comment]
Hallu,
ich wollte mal Fragen wie hier der Stand ist?

Da ich aktuell keine Schmerzmittel habe und die Leute ausschließlich nur mit Tourniquets behandeln kann und halt auch nichts rausgeben kann, würde ich gerne noch diese mit aufnehmen:

- Belladonna
-> Gleich wie Schmerzmittel der Ärzte

**Comment by Relegatos** [comment]
hallo liebe Defs , wie ist der Stand was Underground Medic angeht ? wann bekommt der U-Medic seine Items ?

Gruß Rele - CM Medic

**Comment by Twackerino** [comment]
Design Anfragen bei Design eingestellt.
Items zu 21 ggf ohne Design live

**Comment by Twacker2** [comment]
Huhu,

die Sachen sind nicht im Buch drin für die Herstellung:
Morphium, 1. Hilfe Koffer und Belladonna

**Comment by Twacker2** [comment]
Hallooo,
leider machen die Sachen immernoch Probleme. 

1. Morphiumzäpfchen soll in Morphiumtablette umbenannt werden. 
2. Die Zutat bei Morphiumtablette ist "undefined"
2. Die Zutat bei Belladonna ist "undefined" und beinhaltet Tablettenpulver, dass wir nicht herstellen können und auch nicht von der Apotheke bekommen da wir keine Ärzte sind.

**Comment by Twackerino** [comment]
Sollte zu 2 alles passen

**Comment by Twacker2** [comment]
Hallöchen,

der 1. Hilfe Koffer funktioniert nicht. Auch für dich zur Info @Relegatos 
Leider ist es nur ein Item, dass man nicht nutzen kann. Da steht dann: Du kannst das nicht benutzen. :/

Falls sich das irgendwie beheben lässt wäre das super @Twackerino c:

**Comment by Twacker2** [comment]
Hallo,
das Problem besteht immernoch. Gibts hier schon eine Lösung? IC warten einige immernoch die Teile endlich benutzen zu können. :/

**Comment by MrBurns010** [comment]
@Twackerino kannst du hier noch mal schauen, bitte?
