### ISSUE TITLE
Minenlizenz ertrag in der Mine

### ISSUE THREAD

**Issue by SRBjoern** [Sundown-Rising/sundown-rising-issues#311]
Es gibt seit der Umstellung auf das neue Ausweisscript weniger Ertrag in der Mine wenn man eine Minenlizenz hat.

**Nachstellbar | Auschließen Client Problemen**
JA

**Erwartetes Verhalten**
Man sollte anstatt maximal 3 bis zu 6 Erz bekommen.
**Screenshots/Videos**
https://medal.tv/games/red-dead-2/clips/irbOLCpKfCEnuRg7C/d1337tveL544?invite=cr-MSx5Q2wsNDExNDAzNzQs

**Kontaktdaten Melder**
 - IC-Name: Blake Dalton
 - Discord: 158519103311708160

**Comment by Twackerino** [comment]
behoben
