### ISSUE TITLE
Abbau in der Mine

### ISSUE THREAD

**Issue by Lenemortis** [Sundown-Rising/sundown-rising-issues#313]
**Bergbau-Minenarbeit**

Kein Abbau mehr in den Minen möglich.
mehrere Spieler melden, dass er den Marker zwar sieht, jedoch nichts mehr abbauen kann.

**Nachstellbar | Ausschließen Client Problemen**
JA

Falls Ja, folgende Schritte:
1. geh in die Mine
2. geh zum Minenabbau-Punkt
3. ausführen des Prozesses
4. (FEHLER) Kein Erfolg, Punkt verschwindet ohne Fehlermeldung in den Logs

**Erwartetes Verhalten**
In die Mine gehen und wieder craften können

![image](https://github.com/user-attachments/assets/cc63ce1b-6ddc-4404-914d-5b0148151843)
https://medal.tv/de/games/red-dead-2/clips/is2Qr776n78HpWizm/d1337L902Rm4?invite=cr-MSxqMUQsMjU3MzIyMDA3LA

**Kontaktdaten Melder**
 - IC-Name: Chayton Taylor
 - Discord: 342387885351370752

**Comment by Twackerino** [comment]
behoben
