### ISSUE TITLE
[Wunsch] Steve der Fischer

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#315]
Einen wunderschönen.

Wir Community Manager haben uns letztens über die Vorschlage unterhalten und fanden den Vorschlag gut einen zweiten Steve der Fischer NPC ins Land zu bringen.

Aktuell gibt es nur einen NPC der die Fische gegen die Münzen tauscht bzw Münzen gegen Fischfilet.

Daher die Frage ob es möglich wäre einen weiteren NPC im Hafengebiet von Saint Denise hinzustellen.
Falls ja kann ich gerne schauen wo es am meisten Sinn macht und euch die Koordinaten zukommen lassen.

**Comment by Twackerino** [comment]
ja,gib coords und noch besser namen

**Comment by joybtw** [comment]
Fixed by Nephii
Auf Dev-Server getestet und funktionierte...
