### ISSUE TITLE
[BUG] Drogen Rezept - Opium wurde unbenannt

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#316]
**Beschreibe den Fehler**
Die Banden können keine Schlafmohnsamen Mischungen herstellen, da das Rezept geändert wurde mit Opiumknospen anstatt Opium.
Siehe Bilder!

**Nachstellbar | Auschließen Client Problemen**
JA

1. Geh zum Tisch in Thieves Landing
2. Öffne das Rezept Buch
3. (FEHLER) Rezept wurde von Opium zum Opiumknospe unbenannt, ohne das es dieses Item gibt

**Erwartetes Verhalten**
Entweder das Item zu Opium knospe umbenennen oder das Rezept umschreiben zu Opium anstatt Opiumknospe

**Screenshots/Videos**
![image23](https://github.com/user-attachments/assets/345bcf95-0713-4d5d-a27e-56c2b09b7a7e)
![image34](https://github.com/user-attachments/assets/660ed8af-5ddf-4672-b2d2-f885968efe75)

**Kontaktdaten Melder**
 - IC-Name: Rafael Rogers (4456)
 - Discord: 405385722351321089 (SR | Büchse)

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by fraupan** [comment]
notiz für mich: opium_crop -> opium
