### ISSUE TITLE
LOGS

### ISSUE THREAD

**Issue by Lenemortis** [Sundown-Rising/sundown-rising-issues#317]
Da der Log **nss_players_snapshot** momentan ziemlich fehlerhaft.
Manche Logs werden nicht angezeigt und können wenn überhaupt nur durch Umwege in Erfahrung gebracht werden.
Ich bitte daher darum, sich diesen Bot einmal anzuschauen und seine Fehler ggf. beheben zu lassen.

Liebe Grüße
SR I Floki

P.S.: Ich Devs macht wirklich super Arbeit und ich ziehe vor euch meinen Hut! (:

**Comment by Twackerino** [comment]
![grafik](https://github.com/user-attachments/assets/906c491b-47ed-46b6-9f8d-61651c9427d9)
Sind alle da. Beschwerden über das Discord API Limit bitte an Discord.
