### ISSUE TITLE
[BUG] Purple Kush Joints haben schon wieder keinen Effekt

### ISSUE THREAD

**Issue by xPantherx2** [Sundown-Rising/sundown-rising-issues#32]
**Beschreibe den Fehler**
Purple Kush Joints haben schon wieder keinen Effekt

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
eine verschwommene sicht

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/2fP60bzDF3XJ2C/d1337O1dTMe2?invite=cr-MSxtakssMjAyMjc2NjQ5LA

**Kontaktdaten Melder**
 - IC-Name: Elijah Clark
 - Discord: 424919721301901312

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
behoben
