### ISSUE TITLE
[BUG] Jagd Script - Kein Ertrag von klein Tieren

### ISSUE THREAD

**Issue by aytoon** [Sundown-Rising/sundown-rising-issues#320]
**Beschreibe den Fehler**
Der Spieler hatte eine Ratte und Frösche aufgehoben und bekommt kein Ertrag von den Tieren.

**Nachstellbar | Auschließen Client Problemen**
JA

1. Ratte und Frösche suchen
2. (FEHLER) Nimm die Ratte und den Frosch in die Hand (Häuten)
 
**Erwartetes Verhalten**
Das man von den Tieren Ertrag bekommt, da man sonst kein Essen und Köder herstellen kann.

**Screenshots/Videos**
https://medal.tv/games/red-dead-2/clips/itrsSWZP5UqEO4TZo/d1337q7ZEsiB?invite=cr-MSw2S0UsMTk4NDcyNzc5LA
https://medal.tv/de/games/red-dead-2/clips/itrsSWZP5UqEO4TZo/d1337PVEyhI4?invite=cr-MSxpRGwsMTk4NDcyNzc5LA

**Kontaktdaten Melder**
 - IC-Name:  Dominik Lupus (5537)
 - Discord: 211277840950362112

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Twackerino** [comment]
doppelt #251
