### ISSUE TITLE
Bei den neuen Samen gibt es kleine Probleme 

### ISSUE THREAD

**Issue by xPantherx2** [Sundown-Rising/sundown-rising-issues#33]
**Beschreibe den Fehler**
Eine klare Fehler beschreibung.
Beispiel: Bei den neuen Samen gibt es kleine Probleme 
wenn Muskartnuss abgeerntet  wird ist nix in der Tasche , Paprika können nur 10/10 getragen werden und Kolanuss hat kein bild

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Fisch als Item im Inventar

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.

**Kontaktdaten Melder**
 - IC-Name: John Bwalker
 - Discord: 1056840389723701258

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by joybtw** [comment]
Paprika sollen nur 10/10 getragen werden
Kolanuss -> nach 21 Uhr wieder ein Bild (datei cola_fruit.png zu cola_crop.png umbenannt)

**Comment by joybtw** [comment]
Wie soll der Fehler reproduzierbar sein @xPantherx2 ?

**Comment by joybtw** [comment]
Rest ist behoben.

**Comment by xPantherx2** [comment]
Sorry  kein fisch :D  (arbeite das erste mal mit git)  man bekommt wenn Muskartnuss erntet nix ins Inventar denke das ist das Problem   Sorry für den Fisch
