### ISSUE TITLE
[BUG]Gewerbelampe geht nicht AD bäckerei Tierarzt Heartlands

### ISSUE THREAD

**Issue by SRBjoern** [Sundown-Rising/sundown-rising-issues#336]
**Beschreibe den Fehler**
Lampe lässt sich nicht einschalten punkt fehlt

**Nachstellbar | Auschließen Client Problemen**
JA/

**Erwartetes Verhalten**
das der pubnkt zum lampe einschalten da ist.
**Screenshots/Videos**
![image](https://github.com/user-attachments/assets/c824ae38-eac6-40ee-b498-5185ad9e24aa)

**Kontaktdaten Melder**
 - IC-Name: Ezra McAllister
 - Discord:  320989578745872396

**Comment by SRBjoern** [comment]
Werkzeugmacher in Blackwater geht auch nicht.

**Comment by SRKing-Sup** [comment]
Obere Heartland ist auch weg

**Comment by xxLiiisaaaxx** [comment]
Bestatter Rhodes ist der Trigger für die Lampe ebenfalls weg.

**Comment by SRKing-Sup** [comment]
BW Ranch ist auch weg

**Comment by DieBuu** [comment]
Mine Annesburg
