### ISSUE TITLE
Farmer samen kann jeder benutzen wen im inventar

### ISSUE THREAD

**Issue by xPantherx2** [Sundown-Rising/sundown-rising-issues#34]
**Beschreibe die Verbesserung**
Eine klare Beschreibung.
Beispiel:  Uns ist allerdings aufgefallen dass die (Farm) Samen jeder benutzen kann wenn sie im Inventar sind.

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.

**Kontaktdaten Melder**
 - IC-Name: Unkas Nashoba
 - Discord: 994097079204986910

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by joybtw** [comment]
Für den Spieler: 
Wir warten auf ein neues, besseres farming-script. Aktuell ist dieser Bug nicht behebar, da Script teils verschlüsselt.
