### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SRBjoern** [Sundown-Rising/sundown-rising-issues#340]
**Beschreibe den Fehler**
Man kann keine Kadaver in die (Große) Jagdkutsche einladen, getestet wurde nur die große Jagdkutsche da die kleineren nicht im Stall vorhanden sind.

**Nachstellbar | Auschließen Client Problemen**
JA

**Erwartetes Verhalten**
Das die Große Kutsche mit Tieren beladen werden kann.

**Screenshots/Videos**
https://youtu.be/lClmStc1vX0

**Kontaktdaten Melder**
 - IC-Name: Luigi Patrov
 - Discord: 917516169144074261

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by fraupan** [comment]
Ist schon seit 12 Uhr gefixt :p
