### ISSUE TITLE
[Wunsch] Schlachter soll keine Nutztiere annehmen

### ISSUE THREAD

**Issue by DieBuu** [Sundown-Rising/sundown-rising-issues#345]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
In den Serverregeln ist es Verboten Nutztiere zu Töten wird aber vom Schlachter verlangt durch die Aufträge.
![image](https://github.com/user-attachments/assets/5fcad311-371e-4a6e-a817-269ba0806815)

**Beschreibe die gewünschte Lösung**
Der Schlachtertisch in den Städten solle keine Nutztiere vergeben. (Ziegen, Hühner, Schweine, Kühe,) nicht die Wildschweine
Ebenso sollten Tiere die nicht getragen werden können entfernt werden 
(Bison, Wapiti tiere, Bären, Braun Bären, Aligatoren, Krokodile, Elche, Wildschweine)

**Sonstiges**
Alles andere Hilfreiche

**Comment by Twackerino** [comment]
Im Screenshot steht "sinnloses anschießen ist verboten" nicht Nutztiere.

Die anderen Tiere sind mit Absicht drin um ruhe perioden zu forcen.
