### ISSUE TITLE
Haustier (Biber) behält die "beigebrachte" Erfahrung nicht

### ISSUE THREAD

**Issue by xPantherx2** [Sundown-Rising/sundown-rising-issues#36]
**Beschreibe den Fehler**
 Haustier (Biber) behält die "beigebrachte" Erfahrung nicht 
Sobald auf ein anderes Tier gewechselt wird sind die Erfahrungspunkte wieder auf null.

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Das der Biber seine  "beigebrachte" Erfahrung  behält 

**Kontaktdaten Melder**
 - IC-Name: Simon Corvus
 - Discord: 246765524766294016

**Comment by Twackerino** [comment]
Fehler von unserer Seite nicht behebar liegt an der Synchronisationsrate von GUM_PETS. 
@MrBurns010 Könntest du da mit GUM in kontakt treten, dass die Erfahrung teils nicht behalten wird, Fehler tritt aus Erfahrung auch bei anderen Tieren auch und als workaround ist bisher nur ein längeres draußen lassen der Tiere bekannt, welches nur teils wirkt.
