### ISSUE TITLE
Thieves Landing Saloon

### ISSUE THREAD

**Issue by xPantherx2** [Sundown-Rising/sundown-rising-issues#38]
**Beschreibe den Fehler**
Thieves Landing Saloon Pokertisch, ab einer Anzahl ab 5 Personen sitzt eine Person Zwischen den Stühlen verkehrt herum.

**Kontaktdaten Melder**
 - IC-Name: Rose Turner
 - Discord: 366371349108621312

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by MrBurns010** [comment]
Bitte Clip @xPantherx2

**Comment by MrBurns010** [comment]
@xPantherx2

**Comment by xPantherx2** [comment]
Kümmere ich mich drum

**Comment by xPantherx2** [comment]
einmal der link zum clip   https://medal.tv/de/games/red-dead-2/clips/hYdXAlHGHAMu_Haym/d1337YNIxK0T?invite=cr-MSxNR1ksMTc3MjY1MjAyLA

**Comment by MrBurns010** [comment]
@xPantherx2 
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/1a60151c-f079-49f3-9dbb-20055a9ab0b8)

**Comment by xPantherx2** [comment]
einmal die Koordinaten:  {x=-1395.67, y=-2313.75, z=42.15, heading=228.12}

**Comment by MrBurns010** [comment]
korrigiert @xPantherx2
