### ISSUE TITLE
Anwendung Wundsalbe 

### ISSUE THREAD

**Issue by XPeTerchenX** [Sundown-Rising/sundown-rising-issues#39]
**Beschreibe den Fehler**
Sync Anzeige  Gesichtsverletzungen

**Nachstellbar**
JA

### Falls Ja, folgende Schritte:
  1. Verletzungen im Gesicht
  2. Wundsalbe nehmen
  3. Gesichtsverletzungen verschwinden für andere Spieler, aber  nicht für einen Selbst (FEHLER)

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Keine optischen Verletzungen im Gesicht, wenn Gesichtsschaden durch Wundsalbe nichtig gemacht wird. 

**Screenshots/Videos**

**Kontaktdaten Melder**
 - IC-Name:  ICH
 - Discord:  965182212884541481

**Sonstiges**

**Comment by Twackerino** [comment]
Durch Entfernung des Scriptes nicht mehr relevant.
