### ISSUE TITLE
Wäre es möglich da ich als CM-Medic eine liste bekommen könnte welches IC-Item wieviel % Heilung bringt ?[Frage]

### ISSUE THREAD

**Issue by Relegatos** [Sundown-Rising/sundown-rising-issues#41]
**Schreib das Anliegen**
Aktuell ist es wohl so das die KräuterBonbon´s keine Wirkung mehr haben , da ich aber nicht weiß wie/was die mal geheilt haben kann ich da nix nachvollziehen . Deshalb bitte einmal Prüfen was mit den Kräuter Bonbons ist und mal schauen ob da ein Fehler ist .
Und mir ggf eine Liste zukommen lassen wo für mich als CM ersichtlich ist welches Item welche Wirkung hat und wieviel Heilung diese generieren.

Danke 
Gruß Rele

**Comment by Twackerino** [comment]
https://discord.com/channels/1123352191751704606/1244038703110688861/1244040296438829076
https://docs.google.com/spreadsheets/d/1GQvzxZ9CMf3CaXzGg-850Heo4y4FF7PlPbYQlezSKZw/edit#gid=0
