### ISSUE TITLE
Anpassen der Bandagen im Medic-Script nach CM Abstimmung[Frage]

### ISSUE THREAD

**Issue by Relegatos** [Sundown-Rising/sundown-rising-issues#42]
wie, die MC´s haben am 25.05. eine Anpassung der Medic-Items ( Heilung ) ausgearbeitet und darüber abgestimmt . Diese Abstimmung wurde mit der erforderlichen Mehrheit zugestimmt.
Somit bitte ich die ausgearbeiteten Anpassungen im Medic-Script zu ändern.
https://docs.google.com/document/d/155qzdE14tcD9VIkljHqm5xZszn_ckSzYAQXoEsFJH84/edit?hl=de

bitte bedenken auch die Items das Indianer ( Bandagen ) nicht zu vergessen.

Danke , gruß Rele

**Comment by Twackerino** [comment]
Normalerweise hat eine Frage auch ein Fragezeichen irgendwo 😂

**Comment by Relegatos** [comment]
-> ? <- , da haste eins ;-)
