### ISSUE TITLE
[Gewerbe] Tierarzt Heartland Gemeinschaftsstall Kapazität erhöhen

### ISSUE THREAD

**Issue by Xuess22** [Sundown-Rising/sundown-rising-issues#43]
**Welches Gewerbe?**
Tierarztpraxis Heartland

**Problem / Anfrage**
Gemeinschaftsstall steht auf 5, Wunsch wurde geäußert diesen zu erhöhen

**Kontakt - Gewerbeamt**
Sabrina

**Kontakt - Gewerbe**
IC-Name: Yvi Corvus
Discord: 711235218396414022

**Sonstiges**
Kapazität eventuell auf 50 anheben falls dies möglich ist

**Comment by fraupan** [comment]
gefixt https://github.com/Sundown-Rising/sundown-rising-private/commit/23af736de51569788faf2bbff7fbaa58b42a14af
