### ISSUE TITLE
Angebotsanpassung Rhodes Trapperhändler / Fischer Steve (BW)

### ISSUE THREAD

**Issue by Helmard** [Sundown-Rising/sundown-rising-issues#44]
Hallo,

Wir CM Wirtschaft haben in Zusammenarbeit mit den Jägern eine Umarbeitung des Trapperhändlerangebots in Rhodes erarbeitet.
Wir bitten das Angebot des Trappers, wie im Screenshot abzuändern.
Der Verkauf der Items soll, genau wie an der Flatneck Station, **_Jobgebunden_** sein. Wichtig !

Das heißt, jeder Zivilist kann seine Kadaver (aus Kleintier,- Vogel, -und Reptilienfallen dort gegen "Jagdmünzen" (in der Tabelle JM) eintauschen aber **nichts** aus dem niedergeschriebenen Angebot kaufen.
Die Münzen sollen bei den Jägern gegen Waren eingetauscht werden.
Jede weitere hier beschriebene Funktion soll ausschließlich für Jäger zugänglich sein.

Ein Jäger soll bei diesem Trapper nicht nur Krebsfleisch, Fischfilets und Fallen im Tausch gegen "Jägermünzen" bekommen, sondern kann/soll hier auch seine Waren gegen $ verkaufen können (Preisgleich wie der NPC Händler in Sant Denis; wie im Screenshot/Liste zu sehen). Dafür soll der NPC Händler in Sant Denis wegfallen.

Zusätzlich brauchen wir noch einen Trapper, mit dem selben Parametern, in der Gegend um Armadillo/Mc Farnles Ranch/Blackwater, damit die Jäger aus Armadillo und Mexico nicht bis nach Rhodes reiten müssen.

Vielen Dank.
Bei Fragen, einfach melden.

Hier der google.docs Link zur Liste : https://docs.google.com/spreadsheets/d/1uxGtCYjBgDJ65tPlIXRjYrssEVyMh2Qqox6uXDR9Cjw/edit#gid=0

![Screenshot_6](https://github.com/Sundown-Rising/sundown-rising-issues/assets/171489342/e20d3814-f35e-4918-9d1d-02176196d007)

**Comment by Twackerino** [comment]
Selbes Spiel wie im Issue von Rele... Eine Frage hat ein Fragezeichen.

**Comment by Twackerino** [comment]
```
Wir bitten das Angebot des Trappers, wie im Screenshot abzuändern.
Der Verkauf der Items soll, genau wie an der Flatneck Station, Jobgebunden sein. Wichtig !
```
Momentan ist entweder der gesamte Shop Jobgebunden oder gar nicht.

`Das heißt, jeder Zivilist kann seine Kadaver (aus Kleintier,- Vogel, -und Reptilienfallen dort gegen "Jagdmünzen" (in der Tabelle JM) eintauschen aber nichts aus dem niedergeschriebenen Angebot kaufen.`
Dafür bräuchten wir ggf 2 Händler, aus oben genannten gründen

`Ein Jäger soll bei diesem Trapper nicht nur Krebsfleisch, Fischfilets und Fallen im Tausch gegen "Jägermünzen" bekommen, sondern kann/soll hier auch seine Waren gegen $ verkaufen können (Preisgleich wie der NPC Händler in Sant Denis; wie im Screenshot/Liste zu sehen). Dafür soll der NPC Händler in Sant Denis wegfallen.`
Händler kann momentan nur eine Währung.
`
Zusätzlich brauchen wir noch einen Trapper, mit dem selben Parametern, in der Gegend um Armadillo/Mc Farnles Ranch/Blackwater, damit die Jäger aus Armadillo und Mexico nicht bis nach Rhodes reiten müssen.`
Bitte um coord4 koordinaten

**Comment by Twackerino** [comment]
Änderung des Shopangebots (Anzahl der Waren und Preise) ist lokal schon erfolgt.
Fallen sind momentan nicht über den Hunter kaufbar sondern von Hunters Rest craftbar. Bitte um bestätigung die dort auch kaufbar zu machen

**Comment by Helmard** [comment]
In dem Falle den Trapper jobgebunden für Jäger machen.
Fallen bitte **nicht** zum Eintauschen gegen die Münzen einstellen. Hunters Rest genügt.

Wäre es ein grosser Aufwand noch einen zweiten händlerblip zu setzen um den Ankauf der Jagderzeugnisse möglich zu machen ?

**Comment by Twackerino** [comment]
`Wäre es ein grosser Aufwand noch einen zweiten händlerblip zu setzen um den Ankauf der Jagderzeugnisse möglich zu machen ?`

Meinst du Trapper2 oder SD händler kopieren?

**Comment by Helmard** [comment]
Du meintest dass der aktuelle Trapper in Rhodes nur eine währung kann und man einen weiteren händler setzen müsste.
Das meinte ich. Der Trapper kauft für die münzen die Kadaver aus den Fallen an (Ratte zb) und man kann dort dann für die münzen das Krebsfleisch und die Fischfilets kaufen.
Der andere (zu setzende) händler kauft die Jagderzeugnisse an wie oben beschrieben für $.
Der in Sant Denis könnte dann gelöscht werden.

Eine Koordinate damit man diese beiden händler dann nach Armadillo kopieren kann, muss ich noch suchen

**Comment by Helmard** [comment]
@Twackerino 
Ich habe eine Position für den zweiten Trapperhändler im Westen gefunden.
Nahe Thiefes Landing an einer kleinen Hütte. 
Passt ganz gut.

hier die Coords:

{x=-1814.26, y=-2393.87, z=42.16, heading=122.28}

auch hier bräuchten wir quasi 2 Stellen. Eine zum Ankauf der Kadaver und Verkauf der Dinge für die Jagdmünzen und einen zum Ankauf der Jagderzeugnisse für $. Genau das selbe eben wie in Rhodes.

![Screenshot_1](https://github.com/Sundown-Rising/sundown-rising-issues/assets/171489342/21ed5f28-cf3a-4c1b-b6e7-3f5bb754eb80)

**Comment by Helmard** [comment]
@Twackerino 
Das ist nur bedingt durchgeführt.

Der neue Handelspunkt nahe Thiefs Landing ist richtig.

Bitte den Kauf der Waren so einstellen wie es in der Liste steht. Bei beiden Verkaufspunkten (Rhodes/Thiefs Landing) Ausschließlich diese Produkte.
Vogelleber, Tierfell, Tierfett, Vogelköder, Fischköder, Reptilienköder, Kleintierköder, Leder, Hirschleber, Vogelfleisch nicht zum Kauf vorgesehen.
![Screenshot_2](https://github.com/Sundown-Rising/sundown-rising-issues/assets/171489342/f4e44ecd-07af-476b-96c0-f70b7143d358)

Hier fehlen die aufgeschriebenen Fallen und die Fischfilets der verschiedenen Fische.

Weiterhin habe ich nach einem zweiten Blip gefragt bzw ein zweiter NPCring an jedem Standort, da laut Deiner Aussage ja nur mit einer Währung pro "Auslage" gehandelt werden kann.
So benötigen wir einen zweiten Ring/Npc an den jeweiligen Standorten damit die Jäger hier Ihre Tierfelle, Tierfette, Leder, Wildfleisch, Vogelfleisch, Schlangenhaut und sämtliche legendären Tierhäute verkaufen können um $ zu bekommen

Ich bitte ergo um Korrektur.
Danke

**Comment by Helmard** [comment]
Ich bitte aus oben genannten Gründen das Ticket wieder zu öffnen

**Comment by MrBurns010** [comment]
@Twackerino

**Comment by Twackerino** [comment]
> Hier fehlen die aufgeschriebenen Fallen[...]

> Fallen bitte nicht zum Eintauschen gegen die Münzen einstellen. Hunters Rest genügt.
❓ Irgendwie wiedersprüchlich.

> und die Fischfilets der verschiedenen Fische
Fisch ist bei Steve dem Fischer, auch angepasst wie gewünscht.

> Wäre es ein grosser Aufwand noch einen zweiten händlerblip zu setzen um den Ankauf der Jagderzeugnisse möglich zu machen ?
Steht einer... Habe den aus Saint Denis verschoben, der steht aber nicht neben Trapper oder Mike Jagger. Empfehle mal nach Riggs zu schauen, wie du im Discord mit beobachtet hattest beim einrichten.

> Bitte den Kauf der Waren so einstellen wie es in der Liste steht. Bei beiden Verkaufspunkten (Rhodes/Thiefs Landing) Ausschließlich diese Produkte. Vogelleber, Tierfell, Tierfett, Vogelköder, Fischköder, Reptilienköder, Kleintierköder, Leder, Hirschleber, Vogelfleisch nicht zum Kauf vorgesehen

Bitte beim nächsten mal mit in die Listen integrieren oder genau erwähnen dass nur noch diese gewünscht sind. Abändern bedeutet in der Regel nicht Alles vorher auf 0 zu setzen.

Angebot zu 2 angepasst.

**Comment by Helmard** [comment]
Habe alles getestet.
Funktioniert und ist so wie gewünscht.

Vielen Dank für Deine Mühe <3
