### ISSUE TITLE
Fallen [BUG]

### ISSUE THREAD

**Issue by xxLiiisaaaxx** [Sundown-Rising/sundown-rising-issues#47]
**Beschreibe den Fehler**
Bei den Reptilien und Krabbenfallen wird nichts gefangen obwohl Köder drin sind.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Platziere eine Falle
2. Köder hineinlegen
3. Warten
4. (FEHLER) Keine Schlangen oder Krabben.

**Erwartetes Verhalten**
Das Reptilien oder Krabben gefangen werden.

**Screenshots/Videos**
Bitte Screenshots oder Videos, mit der F8 Konsole.

**Kontaktdaten Melder**
 - IC-Name: Wesley Moon
 - Discord: 701472126959353968

**Sonstiges**
Fischfallen funktionieren einwandfrei

**Comment by Twackerino** [comment]
Fallen funktionieren. Anwender sollte andere Orte probieren
