### ISSUE TITLE
bei den Ölfeldern fällt man unter die Map [BUG]

### ISSUE THREAD

**Issue by xxLiiisaaaxx** [Sundown-Rising/sundown-rising-issues#48]
**Beschreibe den Fehler**
in einem Radius um die Ölfelder fällt man durch die Map.
Meistens Spawnen oben in dem Raum wo man die Companyjobs annimmt auch extrem viele NPC´s.

**Nachstellbar**
Ja, aber nicht immer.

**Erwartetes Verhalten**
nicht durch die Map zu fallen.

**Screenshots/Videos**
https://youtu.be/sNcvsVwg4ts
https://medal.tv/de/games/red-dead-2/clips/hZjFObol8im2fcwYc/d1337nOfoVcN?invite=cr-MSxLT1UsNjY2NTM2MDIs
https://medal.tv/de/games/red-dead-2/clips/hZjDkU0j8QZlc_iW4/d1337tbEQ6bY?invite=cr-MSxyelAsNjY2NTM2MDIs
**Kontaktdaten Melder**
 - IC-Name: Nasu Aite Waani / Josephine Gautier
 - Discord: 1139910451245891804 / 401089324801851392

**Sonstiges**

**Comment by MrBurns010** [comment]
Bei mir lässt sich dieser Fehler leider nicht reproduzieren. Ich habe es an genau den gleichen Orten mit Pferd, ohne Pferd und mit Kutsche versucht. Es wäre hilfreich, jemanden zu finden, der diesen Fehler reproduzieren kann, damit ich den Ursachen auf den Grund gehen kann.

**Comment by xxLiiisaaaxx** [comment]
Also ich selbst hatte da auch schon Probleme.. Ich glaube das liegt daran das da oben in dem Raum 20 oder mehr npc spawnen.. meist vor den Restarts.. ich werde das ebenfalls beobachten da ich RP bedingt da auch öfters hin muss.

**Comment by MrBurns010** [comment]
@xxLiiisaaaxx 

Ist der Fehler nochmal ausgetreten? Wurde es von dir mal geprüft?

**Comment by xxLiiisaaaxx** [comment]
Seid dem die NPC´s dort nicht mehr doppelt spawnen ist bei mir der Fehler nicht mehr aufgetreten.
