### ISSUE TITLE
Haustierkauf mit Federn [BUG]

### ISSUE THREAD

**Issue by xxLiiisaaaxx** [Sundown-Rising/sundown-rising-issues#49]
**Beschreibe den Fehler**
Wenn die Natives Haustiere mit Federn kaufen wollen, das gekaufte Tier erscheint nicht in der Liste sondern es werden 500$ ins Inventar gepackt.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. gehe zum Tierhändler ( für Natives )
2. Kaufe eine Eule
3. (FEHLER) keine Eule sondern 500$

**Erwartetes Verhalten**
Das man die Eule als Haustier rufen kann.

**Screenshots/Videos**
https://youtu.be/1VMWFQGMSjI

**Kontaktdaten Melder**
 - IC-Name: Ayasha Nakai
 - Discord: 408613115140374548

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by Helmard** [comment]
Zu erwähnen sei hier noch, dass 500 Feder Währung abgezogen werden.
