### ISSUE TITLE
Jagen [BUG]

### ISSUE THREAD

**Issue by xxLiiisaaaxx** [Sundown-Rising/sundown-rising-issues#50]
**Beschreibe den Fehler**
Tiere können nicht geschossen werden. ( Fallen nicht um )
Erschossene Tiere verschwinden einfach.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Tier ausfindig machen
2. Tier schiessen
3. (FEHLER) Tiere fallen nicht um bzw. despawnen einfach .

**Erwartetes Verhalten**
Tiere fallen um bzw. können in die Kutsche getan werden.

**Screenshots/Videos**
https://medal.tv/de/games/imported-clips/clips/hZrbqxjTI2k5EC2Tr/d1337hKVfczS?invite=cr-MSxHR1YsMjExNzc2NzgxLA
https://medal.tv/de/games/red-dead-2/clips/hZqYauZnpBfta7RKE/d1337TffhM70?invite=cr-MSxYV1AsMjExNzc2NzgxLA
https://medal.tv/de/games/red-dead-2/clips/hZFdPuvhL9SzqlbM_/d1337lkWQVzQ?invite=cr-MSxrSTgsMjExNzc2NzgxLA
https://medal.tv/de/games/red-dead-2/clips/hZHZrftV9EOAJQCXb/d1337PTodYxC?invite=cr-MSxCemcsMjA3MTQzNTU3LA
https://medal.tv/de/games/red-dead-2/clips/hZFflJjXdnplNO90U/d1337BpKjdE6?invite=cr-MSxuSm0sMjExNzc2NzgxLA
https://medal.tv/de/games/red-dead-2/clips/hZI1I2wHsO3-tWHgd/d133729EwF0r?invite=cr-MSxGYXksMjA3MTQzNTU3LA
https://medal.tv/de/games/red-dead-2/clips/hZI7uPuOOQUde8_lj/d1337yDJIc7Q?invite=cr-MSxzNE0sMjA3MTQzNTU3LA
https://medal.tv/de/games/red-dead-2/clips/hZI5rFd3danQbkLdH/d1337gX9mwgO?invite=cr-MSxwWUYsMjA3MTQzNTU3LA

**Kontaktdaten Melder**
 - IC-Name: Mika Tay
 - Discord: 867128131219226664

**Comment by MrBurns010** [comment]
Das ist ein ganz bekanntes Problem bei RedM. Dies hat mit dem Sync zu tun und kann leider nicht verhindert werden. @xxLiiisaaaxx
