### ISSUE TITLE
[BUG] Aprikosenbüsche nicht erntbar

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#51]
Nördlich von Rhodes sind Aprikosenbüsche. Allerdings sind das 2 verschiedene. 
Die einen sind erntbar bei den anderen kommt nur die Meldung dass man den falschen Job hat.
Das ganze hat ein Native gemeldet mit dem Collector Job.

**Screenshots/Videos**
https://youtu.be/UtbslEMcS2E
![Screenshot_2024-06-03_181321](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170888142/b1c1d3e7-b22c-4462-b963-4a03a3c32d22)
![Screenshot_1](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170888142/d75ab17d-e1f7-4fbf-9b04-c98aeccfc502)

**Kontaktdaten Melder**
 - IC-Name: Miakoda Hevantaneo
 - Discord: melli1979

**Comment by MrBurns010** [comment]
@SRIcely 
Dieser Busch kann nur von Medics geerntet werden. "Frische Aprikosen" werden nur für die Tierdüfte der Medics benötigt.
