### ISSUE TITLE
[BUG] Bootsanleger Annesburg

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#52]
Die meldende Person beschreibt dass Sie und mehrere Personen keine Boote am Anleger in Annesburg rausholen können.
Das Menü verschwindet einfach wenn Sie "G" für Meine Boote drückt.

Bei manchen Personen geht es. Bei manchen nicht. 
Habe es auf dem Dev-Server getestet mit dem selben Boot und da ging es.

https://medal.tv/de/games/red-dead-2/clips/hZMPVntTaoo9D8v9Q/e2XLzMmjKGW9?invite=cr-MSxVVGUsMjI5OTMwNzAwLA
https://medal.tv/de/games/red-dead-2/clips/hZebyTwZsA65kFm3X/4xh2GsntjsRq?invite=cr-MSw4Z0YsMjI5OTMwNzAwLA

 - IC-Name: Viona Mertens
 - Discord: roccatc

**Comment by SRIcely** [comment]
Eine weitere Person meldete das selbe Problem nun vom Anleger bei der Braithwaite Manor.

Clip hierzu: https://youtu.be/aARHgpzFruM

IC-Name: Peter D. Maverick
Discord: x_peterchen_x

**Comment by MrBurns010** [comment]
Script wird in kürze ersetzt

**Comment by MrBurns010** [comment]
Hier gibt es in Kürze ein neues Script. Daher kein Fix für diesen Bug
