### ISSUE TITLE
[Frage] Sammelnfleck entfernen vorm Kopfgeldbrett in Rhods

### ISSUE THREAD

**Issue by iTzAlca** [Sundown-Rising/sundown-rising-issues#53]
Hey und zwar wenn man ans Kopfgeldbrett ran will kann man da nicht zugreifen weil dort ein Sammelbusch mit Thymian ist.
https://prnt.sc/tin73eKR441m
Die Coords dazu um es nachzuprüfen  {1353.4558, -1304.8405, 76.8329, 340.6527}

Hoffentlich passt diesmal mein Tag 😆

**Comment by Twackerino** [comment]
@MrBurns010 Kannst du das Brett unten rum rasieren?

**Comment by MrBurns010** [comment]
Brett rasiert :-)
