### ISSUE TITLE
[BUG] Soborno Alkohol nur noch einzeln herstellbar

### ISSUE THREAD

**Issue by Helmard** [Sundown-Rising/sundown-rising-issues#54]
**Beschreibe den Fehler**
Die Baumeister können in den Destillen den Soborno Alkohol nur noch Flaschenweise einzeln herstellen.
Früher waren es je Rezeptausführung 10 Flaschen.
Aufgefallen vor ca 5-7 Tagen.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Gehe zur Destille
2. Wähle das Rezept Soborno Alkohol
3. (FEHLER) Nur noch 1 Flasche wird gebrannt statt 10

**Erwartetes Verhalten**
Die ursprüngliche Verfahrensweise brachte 10 Alkohol

**Screenshots/Videos**
https://discord.com/channels/1123352191751704606/1246032238588592199

**Kontaktdaten Melder**
 - IC-Name: Mitchell Lewis
 - Discord: 810133059503915049

**Sonstiges**
Eventuell würde das Rezept ausversehen geändert.
Oder es ist Tatsache ein Bug.

**Comment by MrBurns010** [comment]
Rezept angepasst

**Comment by Helmard** [comment]
![Screenshot_7](https://github.com/Sundown-Rising/sundown-rising-issues/assets/171489342/8dae9da6-2730-4765-b668-a0cd5fab539c)


Problem besteht noch immer

**Comment by Helmard** [comment]
https://www.youtube.com/watch?v=Z3t_L_5AHkI
