### ISSUE TITLE
[BUG]Bankeröffnung SB

### ISSUE THREAD

**Issue by Lenemortis** [Sundown-Rising/sundown-rising-issues#55]
**Beschreibe den Fehler**
Spielerin wollte in Strawberry ein Bankkonto eröffnen und erhielt die Meldung, dass es in dieser Stadt nicht möglich ist.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Betreten der Bank in SB
2. Sprich den Dude an/geht allerdings nicht da dann das Spiel ein freeze bekommt
3. über das Command-Menü auch nicht möglich.
4. (FEHLER) Konto wird nicht eröffnet, Geld bleibt aber bestehen

**Erwartetes Verhalten**
Die Möglichkeit einer Kontoeröffnung und -schließung ohne freeze

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/hZULWI1Z6IvPLarat/d1337zbR0WLb?invite=cr-MSxTOXYsMTc3MjY1MjAyLA

**Kontaktdaten Melder**
 - IC-Name: Rose Turner
 - Discord: 366371349108621312

**Comment by Twackerino** [comment]
Fehler beim Spieler.
[sb] ❌ 
sb ✔️
