### ISSUE TITLE
[BUG] Lagerkiste der Crime Fehlerhaft

### ISSUE THREAD

**Issue by SR-Medusa** [Sundown-Rising/sundown-rising-issues#59]
**Beschreibe den Fehler**
Die Mitglieder einer Bande ( Totengräber / Frontline ) können keine Gegenstände mehr aus der Flaggen eigenen Lagerkiste mehr nehmen, obwohl in den Taschen genug Platz ist und nur 1 was verschoben werden soll.
Ist da ein Fehler im Skript ?

**Erwartetes Verhalten**
Es wäre schön, wenn im Skript mal nachgeschaut werden könnte. Die Bande, die dieses Problem hat, kann Momentan nicht auf das eigene Lagerinventar zugreifen, was super ärgerlich ist.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i06loVyIQRwslU4tZ/k6jGHq2d1v6m?invite=cr-MSxpWlgsMTQ3NDAyMDUwLA?mobilebypass=true

**Kontaktdaten Melder**
 - IC-Name: Jesse Scott
 - Discord: 1217886695681429564

**Comment by MrBurns010** [comment]
![image](https://github.com/Sundown-Rising/sundown-rising-issues/assets/137956678/9a2b9a1e-f918-47c4-af1e-32c4a5b0b56e)

Besteht der Fehler noch? @SR-Medusa

**Comment by SR-Medusa** [comment]
Ja, das Problem besteht noch. Habe eben nochmal im Ticket nachgefragt.

**Comment by MrBurns010** [comment]
> Ja, das Problem besteht noch. Habe eben nochmal im Ticket nachgefragt.

Kannst du dann nochmal nach einem Clip fragen? Ich kann den Fehler nicht reproduzieren.

**Comment by SR-Medusa** [comment]
https://medal.tv/de/games/red-dead-2/clips/i2zN4GL7K2spQZi_L/d1337NuoX32J?invite=cr-MSxDTEssMjMxNzQ4ODg5LA

Hab ich. Ich hab den Clip sonst auch nochmal gespeichert, falls der irgendwann weg sein sollte.

**Comment by fraupan** [comment]
Hallo @SR-Medusa,
die Items werden in der Flagge gespeichert, weshalb ich das bei meinem Pflanzen-Update übersehen hatte.
Sollte ab jetzt wieder funktionieren, ich habe die items (z.B. "cherry" zu "cherry_crop") angepasst :)

Grüße!

**Comment by SR-Medusa** [comment]
Hallo @fraupan 

Danke für die fixe Behebung des Problems  :)
Nur hat der User gerade das Problem, dass Flagge, Lager und Co alles weg ist.
Wenn du Zeit hast, kannst du da nochmal einen Blick drüber werfen ?
