### ISSUE TITLE
Legendäre Aligatorhaut [BUG]

### ISSUE THREAD

**Issue by xxLiiisaaaxx** [Sundown-Rising/sundown-rising-issues#63]
**Beschreibe den Fehler**
Die Mission wo man den Legendären Alligator jagen muss um die Legendäre Alligator Haut zu bekommen.
Die Jagd an sich funktioniert, nur leider wenn man den Alligator dann häutet verschwindet die Haut und man kann die Mission ohne die Haut nicht beenden. 

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Jagd annehmen
2. Tier finden und schiessen
3. (FEHLER) Haut verschwindet

**Erwartetes Verhalten**
Das man die Haut beim Auftraggeber abgeben kann um die Mission zu beenden.

**Screenshots/Videos**
https://youtu.be/NuxxnCiPk6g

**Kontaktdaten Melder**
 - IC-Name: Bayar Batjargal 
 - Discord: 282905517318471681

**Comment by Twackerino** [comment]
Duplikat von Sundown-Rising/sundown-rising-issues#2
