### ISSUE TITLE
[BUG]Pferdemedizin

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#65]
**Beschreibe den Fehler**
Die Pferdemedizin von Siedlern kann aktuell nicht hergestellt werden.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Buch öffnen
2. Versuchen es herzustellen

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Herstellung Pferdemedizin

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1248216794791936050/1248222625747042364/20240606_123036.jpg?ex=6662e168&is=66618fe8&hm=4d29f65bdb908cc6ada9f307d360a15b70bb6e6bdd0481c69fdc59450d3d13fc&

**Kontaktdaten Melder**
 - IC-Name: Yvi Corvus
 - Discord: yvi1994

**Comment by fraupan** [comment]
Hallo @SRCaesar,

ich habe neue Hopfen-Samen hinzugefügt (auch im Farmers-Store), damit sollte das dann funktionieren :)

Grüße,
Pan
