### ISSUE TITLE
[BUG]Drogenfeld Pflanzen 

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#66]
**Beschreibe den Fehler**
Die Pflanzen sind nicht erreichbar. Siehe Video.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Geh zu den Pflanzen und schaue es an.

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Das die zu ernteten Pflanzen erreichbar sind. 

**Screenshots/Videos**
https://youtu.be/jikKWc-oCY8

**Kontaktdaten Melder**
 - IC-Name: Cassidy Blackbeard
 - Discord: black_buddy

**Comment by MrBurns010** [comment]
Spawnpunkt etwas versetzt, damit die Pflanzen nicht an der Seite vom Berg spawnen
