### ISSUE TITLE
[BUG] Sargmenü Bestatter Rhodes öffnet sich nicht

### ISSUE THREAD

**Issue by SRIcely** [Sundown-Rising/sundown-rising-issues#67]
**Beschreibe den Fehler**
Das Menü des Bestatters öffnet sich nicht mehr um eine Person in den Sarg zu legen.

**Erwartetes Verhalten**
Das Menü für den Sarg sollte sich nach dem betätigen der Taste "G" öffnen.
https://medal.tv/de/games/red-dead-2/clips/2e3CuPYgqHFIaH/d1337GDpCChI?invite=cr-MSw3NEIsMjAzMzk1MjA1LA

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i0EMtkJLOMgYXK0Ss/d1337gdE9NVl?invite=cr-MSwzMmosMjAzMzk1MjA1LA

**Kontaktdaten Melder**
 - IC-Name: Louise Nowak
 - Discord: xxliiisaaaxx

**Comment by Xuess22** [comment]
ist gefixt worden zu 21 Uhr :) @SRIcely
