### ISSUE TITLE
Frauenwäsche [Frage]

### ISSUE THREAD

**Issue by xxLiiisaaaxx** [Sundown-Rising/sundown-rising-issues#68]
Hallo ihr Lieben,

Laut der Abstimmung vom 01.05 wurde abgestimmt das die Frauenwäsche rausgenommen wird, damit man keine Buggy Anziehsachen mehr hat.

Wie ist da der Stand ? 
Wird das noch übernommen?

Liebe Grüße Pony

**Comment by Twackerino** [comment]
Changelog zu 2 beachten
