### ISSUE TITLE
[Frage]Flagge kann vom Spieler nicht gesetzt werden.

### ISSUE THREAD

**Issue by SR-Medusa** [Sundown-Rising/sundown-rising-issues#69]
**Schreib das Anliegen**
Hallo ihr Lieben.

Und zwar geht es um folgendes: 
Der Leader der Kupferbanditen wollte seine Base verlagern. Da er selbst die Flagge nicht umstellen konnte, hab ich das weiter an die Datenbank gegeben, damit da die Flagge umgestellt werden kann.
Spaddy hat den Fall bearbeitet, aber die Flagge war dann weg. Er hat sie wohl gelöscht.
Auf bitten von Ihm habe ich dem Leader der Frak eine neue Flagge gegeben, diese kann aber nicht gesetzt werden.
Da kommt die Meldung, er sei in einer Bande.

Könnte da mal jemand drüberschauen ? Das wäre super lieb von euch. Ich Danke euch dafür schonmal im vorraus.

Hier der Link zum Ticket, falls Ihr da nochmal nachlesen wollt.
https://discord.com/channels/1123352191751704606/1245844348894056509

**Comment by Twackerino** [comment]
Problem im Ticket gelöst
