### ISSUE TITLE
[Wunsch] Betäubungspfeile

### ISSUE THREAD

**Issue by Twackerino** [Sundown-Rising/sundown-rising-issues#7]
**Ist die Funktion an ein Problem gebunden? Falls ja welches Problem ist es?**
Natives wollen ungerne Tiere töten. Ein Pfeil der am ende betäubt wäre prima.

**Beschreibe die gewünschte Lösung**
Pfeile die Tiere betäuben hinzufügen.

**Gibt es Alternativen die bereits überlegt wurden und warum reichen die nicht?**
Keine.

**Sonstiges**
Alles andere Hilfreiche

**Comment by Twackerino** [comment]
Wunsch durch CM Natives - Aqua

**Comment by MrBurns010** [comment]
Derzeit ist es leider seitens RedM nicht möglich, Munition (Pfeile gehören dazu) vom Schaden zu verändern. Somit ist eine Anpassung technisch bedauerlicherweise unmöglich, dass es keine Betäubungspfeile im Spiel gibt.
