### ISSUE TITLE
[BUG]Munitionskiste

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#71]
**Beschreibe den Fehler**
Die Munitionskiste wird leer angezeigt, obwohl Munition vorhanden ist.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Geh ins Inventar und schaue die Munitionskiste an

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Leere Kiste ist zusehen.

**Screenshots/Videos**
https://cdn.discordapp.com/attachments/1248352120269181060/1248549810898731040/20240606210450_1.jpg?ex=6664121f&is=6662c09f&hm=3390813aa12d2eca286e4f8cff5f6e0513495c75e7a04ebc81d8ecedf4f902d2&

**Kontaktdaten Melder**
 - IC-Name: Dominik Lupus
 - Discord: vlad4404

**Comment by SRIcely** [comment]
Die Meldung kam ebenfalls von einem anderen Spieler.

Die Munitionskiste wird als leer angezeigt und es ist nicht möglich neue Munitionspäckchen zu öffnen.

Clip: https://medal.tv/de/games/red-dead-2/clips/i1qu3D85rgbU5uVRk/d13375pUsiFM?invite=cr-MSxrWXIsMTk4NDcyNzc5LA

Fehlermeldung bei F8:
![Screenshot_2](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170888142/3403e6a6-32c4-4e80-93ca-f576f306bc7e)


Bilder: 
![sZOgONi](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170888142/2871e4aa-fbbe-4457-a444-ce1c933920d5)
![5YVMHO6](https://github.com/Sundown-Rising/sundown-rising-issues/assets/170888142/34ed8065-c284-4428-b808-31eb1ea40da4)

IC-Name: Kleiner Fels
Discord: aytoon
