### ISSUE TITLE
Keine Waffen geben und bekommen [BUG]

### ISSUE THREAD

**Issue by xxLiiisaaaxx** [Sundown-Rising/sundown-rising-issues#73]
**Beschreibe den Fehler**
Es ist momentan nicht möglich Waffen zu bewegen. 
Weder vom Pferd ins Inventar noch von Inventar zu Inventar.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Person 1 gibt person 2 eine Waffe
2. (FEHLER) nicht möglich.

**Erwartetes Verhalten**
Die Waffen normal weiterzugeben.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i0YT8IdxVcpaQuB5z/d1337a6TGAxI?invite=cr-MSw5TlMsMTk4NDcyNzc5LA

**Kontaktdaten Melder**
 - IC-Name: kleiner Fels
 - Discord: 714573318602358786

**Comment by fraupan** [comment]
Hallo @xxLiiisaaaxx, 
der User hat bereits 10 Waffen im Inventar, mehr kann er nicht tragen^^ Er muss erst Waffen ablegen, damit er wieder andere Waffen tragen kann.

Grüße,
Pan
