### ISSUE TITLE
Schinken Tragekapazität

### ISSUE THREAD

**Issue by Helmard** [Sundown-Rising/sundown-rising-issues#74]
Hallo,

in einem Ticket wurde der berechtigte Wunsch geäußert die Tragekapazität von dem neuen Item "ham" (Schinken) auf 100 zu erhöhen (aktuell 50).
Salami und Leberwurst liegen, als verarbeitete Jägerprodukte ja auch schon bei 100 Tragekapazität.

Danke

Viele Grüße

https://discord.com/channels/1123352191751704606/1248580623648559114

**Comment by Twackerino** [comment]
Geändert
