### ISSUE TITLE
töne ändern[Wunsch] 

### ISSUE THREAD

**Issue by Relegatos** [Sundown-Rising/sundown-rising-issues#75]
ist es möglich das es ein Ton für Notfalltaube und einen für Praxisklingel gibt ? und kann man einen cooldown für die Praxisklingeln einführen das nicht alle 2 sek geklingelt wird ? Danke  Rele

**Beschreibe die gewünschte Lösung**
Eine klare und verständliche Beschreibung der gewünschten Lösung.

**Gibt es Alternativen die bereits überlegt wurden und warum reichen die nicht?**
Welche Alternativen wurden bereits überlegt.

**Sonstiges**
Alles andere Hilfreiche

**Comment by Twackerino** [comment]
@Relegatos 

Wie ich dir bereits damals sagte, JA wenn du die geändert haben willst kannst mir ja auch gerne einen Sound zu kommen lassen sonst such ich den später selbst.

Zum Thema Cooldown schaue ich mir an

**Comment by Relegatos** [comment]
ein einfacher DingDong oder so für die Klingel würde schon reichen

**Comment by Twackerino** [comment]
60 sekunden cooldown noch zusätzlich eingebaut

**Comment by Relegatos** [comment]
danke für die schnelle lösung , lieb von euch
