### ISSUE TITLE
Anpassung Haustierpreise

### ISSUE THREAD

**Issue by Helmard** [Sundown-Rising/sundown-rising-issues#76]
Hallo,

anbei eine Liste mit den überarbeiteten Haustierpreisen der Tierarztpraxis Valentine.
Bitte die Preise, so wie sie hier stehen übernehmen.
Das ganze wurde im Ticket vorgeschlagen und abgenommen.

https://discord.com/channels/1123352191751704606/1247135877252255796

Vielen Dank. <3

[Tierpreise Valentine Tierarzt.docx](https://github.com/user-attachments/files/15745722/Tierpreise.Valentine.Tierarzt.docx)

**Comment by Helmard** [comment]
@Twackerino definiere Jobtiere.
Die Auflistung zeigt alle HausTiere die die Tierarztpraxis verkauft.

**Comment by Twackerino** [comment]
> @Twackerino definiere Jobtiere. Die Auflistung zeigt alle HausTiere die die Tierarztpraxis verkauft.

Die haben 2 Preise für manche Tiere. Kannst die ja notfalls mal fragen ^^

**Comment by Twackerino** [comment]
also einen öffentlichen Preis der höher ist und einen für die Jobs, damit die die billiger kriegen als Stechus Kaktus

**Comment by Helmard** [comment]
@Twackerino Also das sind keine Job/privat Preise.

Die günstigere Variante war für Freunde/Familie.
Das möchte sie gerne rausnehmen lassen.

https://prnt.sc/_PWDfIgYHMCG

**Comment by Twackerino** [comment]
Ähhh doch die mit - J sind Job preise damit die mehr machen können Preislich als ein Npc kauf. Rp fördern und so und die sollen auf bitte eines Tierarztes raus?

**Comment by Helmard** [comment]
Laut Bitte der Tierärzte sollen die raus.
Lass sie einfach drin und Pass sie entsprechend an.
Wir sagen ihr man kann dir nicht rausnehmen und dass sie Handelsspielraum hat zb für Gewerbetreibende.
Kann sie ja dann auch so bewerben

**Comment by Xuess22** [comment]
Zu 12 Uhr angepasst @Helmard wie im Ticket besprochen
