### ISSUE TITLE
[BUG]Pilz-Bug

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#77]
**Beschreibe den Fehler**
Buchenpilz wurde gekauft aber in der Tasche sind dann Steinpilze.

**Nachstellbar**
NEIN

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Buchenpilz auch in der Tasche.

**Screenshots/Videos**
https://medal.tv/games/red-dead-2/clips/i1mYzhglZFEkaK9BS/d1337257GcAd?invite=cr-MSxWZHcsMTQ0NTg5MTQwLA

**Kontaktdaten Melder**
 - IC-Name: Grace McNair
 - Discord: angelofthelord25 (293380522963501068)

**Comment by Xuess22** [comment]
fixed sundown-rising-issues#77 zu 21 Uhr

**Comment by Xuess22** [comment]
@Twackerino habs gefixt, check den command noch nicht xD

**Comment by Xuess22** [comment]
ah kanns selbst closen, LOL, bin blond, sorry
