### ISSUE TITLE
[BUG] Crime Crafting nicht zu öffnen

### ISSUE THREAD

**Issue by Lenemortis** [Sundown-Rising/sundown-rising-issues#79]
**Beschreibe den Fehler**
In der Crime gibt es momentan ein Problem.
Manche können scheinbar mit dem Crimejob nicht die Werkbänke nutzen.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Der Werg zur Werkbank
2. Drücken der Space-Taste
3. Keine Veränderung
4. (FEHLER) Werkbank-Tool öffnet sich nicht

**Erwartetes Verhalten**
Was würde man erwarten für ein Ergebnis?
Überprüfung der Werkbänke mit dem Crimejob

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i2cbmr6EURAx9MK-x/d1337eIkoh93?invite=cr-MSxFOWcsNDQxOTYyNDcs
https://medal.tv/de/games/red-dead-2/clips/i2cK7rKsffZbFUbKH/d1337J97lAlU?invite=cr-MSxEV3YsNDQxOTYyNDcs

**Kontaktdaten Melder**
 - IC-Name: Mina Montero
 - Discord: 323822654312415232

**Comment by MrBurns010** [comment]
https://streamable.com/xago02

Werkbank funktioniert. @Lenemortis bitte die Spieler immer nach /myjob fragen um zu überprüfen ob der crimejob vorhanden ist. Ansonsten ist diese Werkbank nicht nutzbar.
