### ISSUE TITLE
[BUG]Guarma Rum brauen nicht möglich

### ISSUE THREAD

**Issue by SRHannah-Sundown** [Sundown-Rising/sundown-rising-issues#80]
**Beschreibe den Fehler**
Crimler auf Guarma kann keinen Rum brauen.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Geht zum Brautisch
2. Wählt Einfachen Rum aus
3. Fehler: Meldung kommt: "Du hast nicht genug Erfahrung!"

Siehe Ticket "bugrep-guarma_brennerei_buchse" bei Discord

**Screenshots/Videos**

https://github.com/Sundown-Rising/sundown-rising-issues/assets/172209363/1f49513b-b487-483c-8201-1ae5e83e1ded

**Kontaktdaten Melder**
 - IC-Name: Rafael Rogers
 - Discord: buchse

**Comment by Twackerino** [comment]
Zu 2 behoben.
