### ISSUE TITLE
Munition füllt sich nach Relog wieder auf

### ISSUE THREAD

**Issue by Helmard** [Sundown-Rising/sundown-rising-issues#83]
**Beschreibe den Fehler**
Nach Relog ist die eingelegte Munition in allen Waffen wieder aufgefüllt.

**Nachstellbar**
JA

nach einloggen schießen
reloggen
selbe Waffe erneut ausrüsten
und Munition ist wieder voll

**Erwartetes Verhalten**
Muniton ist nach Relog auf dem Stand nach dem Schuss (Verbrauch wird gespeichert)

**Screenshots/Videos**

https://prnt.sc/zhyVjGd-URBe

**Kontaktdaten Melder**
 - IC-Name: John Clarkson
 - Discord: 337672416803422219

**Comment by Twackerino** [comment]
Duplikat. Fehlerhafte Munikiste. Siehe #71
