### ISSUE TITLE
Soborno Alkohol

### ISSUE THREAD

**Issue by Helmard** [Sundown-Rising/sundown-rising-issues#84]
https://github.com/Sundown-Rising/sundown-rising-issues/issues/54

Das Problem besteht weiterhin.

**Comment by Twackerino** [comment]
@MrBurns010 Kannst du morgen bitte auf dev testen? Änderung in Client.lua grad hochgeladen, keine kraft zum selbsttest

**Comment by MrBurns010** [comment]
Nun hat man mit dem Brauereijob garkeine Brauerei Rezepte mehr .....
 @Twackerino

**Comment by MrBurns010** [comment]
### FIXED BY @Twackerino
