### ISSUE TITLE
Anpassung Alligatorfleisch / Schildkrötenfleisch

### ISSUE THREAD

**Issue by Helmard** [Sundown-Rising/sundown-rising-issues#85]
Es müsste bitte im vorp_hunting Script der Spawn für Alligatorfleisch & Schildkrötenfleisch angepasst werden.

aktuell bekommt man bei einer Tötung bzw Häutung von 1x Alligator/Krokodil Wildfleisch ins Inventar.
Wenn man Glück hat und die Haut **nicht** despawnt und man sie bei einem NPC verkaufen kann, dann bekommt man 1 Alligatorfleisch.
Da die Haut des Krokodils/Alligators jedoch immer despawnt, ist es praktisch nicht möglich an Alligatorfleisch zu kommen, da man ja die Haut abgeben muss.

Der Saloon Van Horn hat zb ein Rezept mit Alligatorfleisch. 
Ebenfalls hat der Saloon Van Horn ein Rezept mit Schildkrötenfleisch. 
Hier könnte die Spawnrate vom Fleisch erhöht werden, um nicht alle Schildkröten auf dem Server töten zu müssen um eine Bestellung von zb 300 Stk abzuarbeiten.

Lösungsvorschlag:

Die Fleischspawns in den Krokodilen/Alligatoren vom Item Wildfleisch auf Alligatorfleisch zu ändern. Spawnrate darf die selbe bleiben.
Schuldkrötenfleisch gerne um 2 Fleisch erhöhen.

**Comment by Xuess22** [comment]
@Helmard zu 2 Uhr gefixt
