### ISSUE TITLE
Gewerbetelegramme

### ISSUE THREAD

**Issue by Xuess22** [Sundown-Rising/sundown-rising-issues#89]
**Welches Gewerbe?**
Alle mit Gewerbetelegrammen

**Problem / Anfrage**
Howdy,

vor einiger Zeit haben wir eine Gewerbe-Telegrammnummer beantragt und die fällige Gebühr von 100$ sofort entrichtet.

Leider wurde das Anliegen bislang nicht wie versprochen umgesetzt.

Wir sind zwar in der Lage Telegramme von unserem Gewerbe zu versenden, sind aber über den übermittelten Absender "Hunters Rest" nicht erreichbar. Auf die uns angegebene Telegramm-Nummer "huntersrest" erreichen uns keine Telegramme.

Wir bitten um dringende Bearbeitung oder Rückerstattung der Kosten.

**Kontakt - Gewerbeamt**
Bspw. Sabrina

**Kontakt - Gewerbe**
IC-Name:
Discord:

**Sonstiges**
Bedeutet, man kann auf die Gewerbetelegramme nicht antworten. Kann man das umsetzen?

**Comment by Xuess22** [comment]
Fehler ist bei allen Gewerbetelegrammen vorhanden

**Comment by Xuess22** [comment]
leider immer noch vorhanden der fehler @Twackerino https://discord.com/channels/1123352191751704606/1249708964854370304

**Comment by Twackerino** [comment]
Deren Telegrammnummer ist buechsenmacherstrawberry......
