### ISSUE TITLE
[Gewerbe] Glücksspiel für Thieves Landing

### ISSUE THREAD

**Issue by Twackerino** [Sundown-Rising/sundown-rising-issues#9]
**Welches Gewerbe?**
Saloon Thieves Landing

**Problem / Anfrage**
Poker/Blackjacktisch & Umkleide

**Kontakt - Gewerbeamt**
Sabrina

**Kontakt - Gewerbe**
IC-Name: James Walker
Discord: john_conor - 640639252732051476

**Sonstiges**
Sonstige Informationen

**Comment by MrBurns010** [comment]
Pokertisch hinzugefügt + Umkleide
