### ISSUE TITLE
[BUG]Blackbook und andere Bücher öffnen sich nicht 

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#90]
**Beschreibe den Fehler**
Die Blackbooks können nicht mehr geöffnet werden

**Nachstellbar**
JA/
Falls Ja, folgende Schritte:
1. Gehe ins Inventar und versuche das Buch zu öffnen

**Erwartetes Verhalten**
Buch öffnet sich

**Screenshots/Videos**
[Bitte Screenshots oder Videos, mit der F8 Konsole.](https://medal.tv/de/games/red-dead-2/clips/i2Y9axC6LNnDa3AcP/d1337wuFKxzL?invite=cr-MSxSMGYsMjI3ODIwMjk0LA)

**Kontaktdaten Melder**
 - IC-Name: Renfry Avery
 - Discord: cayris24 (404681425913249792)

**Comment by Twackerino** [comment]
Kein Fehler.

Buch wurde für Alternativen ausgeschalten
