### ISSUE TITLE
[BUG]Purple und Kulka Joint funktionieren nicht mit Effekt

### ISSUE THREAD

**Issue by SRCaesar** [Sundown-Rising/sundown-rising-issues#91]
**Beschreibe den Fehler**
Beide Drogen haben kein Effekt. 

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Einen von beiden Joints probieren

**Erwartetes Verhalten**
Sollten soweit ich weiß das Herz stärker machen.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i2mtg2tDeNOj1_-kT/d1337woLM0j6?invite=cr-MSxMbHEsMjAyMjc2NjQ5LA

**Kontaktdaten Melder**
 - IC-Name: Elijah Clark
 - Discord: doggy1509 (424919721301901312)

**Comment by Twackerino** [comment]
Öhmmmm...... Das Herz wird doch Golden???
