### ISSUE TITLE
[BUG]Syn-Clan Fellabgabe

### ISSUE THREAD

**Issue by SRHannah-Sundown** [Sundown-Rising/sundown-rising-issues#93]
**Beschreibe den Fehler**
Beim Fleischertisch in Fort Wallace können keine Tierfelle abgegeben werden.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Geh zum Fleischertisch
2. Haben Fell in der Hand
3. Versuchen abzugeben
4. (FEHLER) Fell wird nicht angenommen, von mehreren unterschiedlichen Personen

**Erwartetes Verhalten**
Fell wird abgegeben, Münzen werden gezahlt

**Screenshots/Videos**

https://youtu.be/6jhyNuTpWc0

**Kontaktdaten Melder**
 - IC-Name: Cassidy Blackbeard
 - Discord: black_buddy

**Comment by MrBurns010** [comment]
wurde wieder aktiviert
