### ISSUE TITLE
[BUG]Jagdauftrag-Siedler-Biber-funktioniert-nicht

### ISSUE THREAD

**Issue by SRHannah-Sundown** [Sundown-Rising/sundown-rising-issues#94]
**Beschreibe den Fehler**

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Geh zum Siedler-Auftragshändler
2. Nimm den Biber Jagdauftrag an
3. Erhalte den Hinweis Spuren zu finden
4. Reite zum auf der Map angezeigten Kreis
5. Finde den toten Biber
6. Halte G gedrückt um zu untersuchen
7. Erhalte den Auftrag zur gekennzeichneten Stelle zu gehen
8. Reite zur mit X markierten Stelle
9. (FEHLER) Es wird kein weiteres Event getriggert, der Auftrag kann nicht fort geführt werden

**Erwartetes Verhalten**
Es wird ein Event getriggert und der Auftrag kann zu Ende geführt werden.

**Screenshots/Videos**
https://medal.tv/de/games/red-dead-2/clips/i32csEA99rmw3T6wJ/d13377EvsLDj?invite=cr-MSxqVFcsMjQxOTE4NzMwLA
https://i.gyazo.com/1045a81cf178119e5dbf065ca2653006.png

**Kontaktdaten Melder**
 - IC-Name: Bill Blake
 - Discord: travoltino.

**Sonstiges**
Der Spieler hat den Auftrag schon mehrere male durchgeführt, siehe Ticket.

**Comment by EllyFou** [comment]
Fehler ebenfalls vorhanden bei 
IC Name : "John Watson"
Discord Name : impileebjorn
Clip : https://medal.tv/de/games/red-dead-2/clips/i2Ca9lJhnKYqgxQWH/d1337FzK3ruD?invite=cr-MSxnZ2UsMjAwOTkyNjU0LA

**Comment by MrBurns010** [comment]
Fehler behoben:
https://discord.com/channels/1123352191751704606/1123558498127585321/1250473541401444462
