### ISSUE TITLE
[BUG]Jagdauftrag-Alligator-Buggy

### ISSUE THREAD

**Issue by SRHannah-Sundown** [Sundown-Rising/sundown-rising-issues#95]
**Beschreibe den Fehler**
Es sollte ein totes Reh auffindbar sein durch den Jagdauftrag Alligator. Es waren aber an die 100 "Zombie-Rehe" die dort rum liefen. Jagdauftrag konnte nicht beendet werden.

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. Nach Auftragsannahme zum Spawn Punkt für das tote Reh geritten
2. Spawnpunkt erreicht
3. (FEHLER) Statt einem toten Reh, 100erte Zombie Rehe auf einer Stelle

**Erwartetes Verhalten**
Ein totes Reh am Boden, nächste Aufgabe für den Jagdauftrag

**Screenshots/Videos**
F8 Konsole hat keine Meldung gegeben laut Spieler
https://medal.tv/de/games/red-dead-2/clips/i35eqEJk5vYySvIET/d1337wf02rNn?invite=cr-MSxnV2YsMjExNzc2NzgxLA

**Kontaktdaten Melder**
 - IC-Name: Mika Tay
 - Discord: p.d.m.official

**Sonstiges**
Es sind mehrere Jagdaufträge verbuggt, aber das so viele "tote" lebendige Tiere an der Auftragsstelle spawnen fand ich ungewöhnlich, deswegen hab ich hierfür einen neuen Report gemacht.

**Comment by MrBurns010** [comment]
@SRHannah-Sundown 
Der Clip muss länger sein. Wir brauchen einen Clip von Start zum zum Fehler inkl. F8 Console. (Vorgabe vom Entwickler damit wir einen Bug melden können)

Bitte hier nochmal einen Clip senden lassen

**Comment by MrBurns010** [comment]
Fehler behoben:
https://discord.com/channels/1123352191751704606/1123558498127585321/1250473541401444462
