### ISSUE TITLE
Büchsenmacher Strawberry

### ISSUE THREAD

**Issue by Xuess22** [Sundown-Rising/sundown-rising-issues#96]
**Welches Gewerbe?**
Büchsenmacher SB

**Problem / Anfrage**
Kann man die Telegrammadresse in gunsmithsb ändern?

**Kontakt - Gewerbeamt**
Sabrina

**Kontakt - Gewerbe**
IC-Name: Bill Blake
Discord: 254734475835998208

**Sonstiges**
Sonstige Informationen

**Comment by Twackerino** [comment]
ja. Telegramme werden nicht neu gemappt. alle erhalten gehen verloren. Bitte Bestätigen @Xuess22

**Comment by Xuess22** [comment]
Genehmigt @Twackerino
