### ISSUE TITLE
Bestatterkutsche geht nicht

### ISSUE THREAD

**Issue by Xuess22** [Sundown-Rising/sundown-rising-issues#99]
**Beschreibe den Fehler**
Wenn ich T drücke und /hearse eingebe, steht da, dass ich nicht den erforderlichen Job habe. Den habe ich aber :D

**Nachstellbar**
JA
Falls Ja, folgende Schritte:
1. drücke t /hearse
2. Hab den Job nicht

**Erwartetes Verhalten**
Kutsche soll spawnen

**Screenshots/Videos**
haben in synexchanges geguckt, in MM_hearse. Find den Fehler nicht.
F8 kommt nix außer: Du hast nicht den erforderlichen Job

**Kontaktdaten Melder**
 - IC-Name: Sabrina
 - Discord: SR Sabrina

**Sonstiges**
Wenn es weiteres gibt bitte hinzufügen.

**Comment by MrBurns010** [comment]
funktionstest erfolgreich abgeschlossen
